"""
ApiProviderSettings database model for storing API provider configuration
- Portions generated by AI
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime

from ..core.database import Base


class ApiProviderSettings(Base):
    """
    Singleton-style model for API provider configuration.
    Only one row with id=1 should exist.
    
    Attributes:
        active_provider: "massive" or "alpaca"
        use_midpoint_pricing: Whether to use (bid+ask)/2 for Alpaca quotes
    """
    __tablename__ = "api_provider_settings"
    
    id = Column(Integer, primary_key=True, default=1)
    active_provider = Column(String(20), default="massive", nullable=False)
    use_midpoint_pricing = Column(Boolean, default=True, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<ApiProviderSettings provider={self.active_provider}>"
    
    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return {
            "active_provider": self.active_provider,
            "use_midpoint_pricing": self.use_midpoint_pricing,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
