"""
CacheSettings database model for storing cache configuration
- Portions generated by AI
"""

from datetime import datetime
from sqlalchemy import Column, Integer, Boolean, DateTime

from ..core.database import Base


class CacheSettings(Base):
    """
    Singleton-style model for cache configuration.
    Only one row with id=1 should exist.
    """
    __tablename__ = "cache_settings"
    
    id = Column(Integer, primary_key=True, default=1)
    cache_enabled = Column(Boolean, default=True, nullable=False)
    ttl_stock_price = Column(Integer, default=180, nullable=False)      # 3 minutes
    ttl_options_chain = Column(Integer, default=300, nullable=False)    # 5 minutes
    ttl_news = Column(Integer, default=900, nullable=False)             # 15 minutes
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<CacheSettings enabled={self.cache_enabled}>"
    
    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return {
            "cache_enabled": self.cache_enabled,
            "ttl_stock_price": self.ttl_stock_price,
            "ttl_options_chain": self.ttl_options_chain,
            "ttl_news": self.ttl_news,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
