"""
TradeIdea database model for storing curated watchlists
- Portions generated by AI
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, DateTime, Text, ForeignKey, Index, Integer
from sqlalchemy.orm import relationship

from ..core.database import Base


class TradeIdea(Base):
    """TradeIdea model for storing curated watchlists with descriptive names"""
    __tablename__ = "trade_ideas"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    
    # System vs user trade idea
    is_system = Column(Boolean, default=False, nullable=False)
    is_default = Column(Boolean, default=False, nullable=False)  # Only one system trade idea can be default
    display_order = Column(Integer, default=0, nullable=False)  # For ordering in UI
    
    # Owner (null for system trade ideas)
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)
    
    # Symbols (comma-separated string for simplicity)
    symbols = Column(Text, nullable=False)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship
    user = relationship("User", back_populates="trade_ideas")
    
    # Index for efficient queries
    __table_args__ = (
        Index('idx_trade_ideas_system', 'is_system'),
        Index('idx_trade_ideas_default', 'is_system', 'is_default'),
    )
    
    def __repr__(self):
        return f"<TradeIdea {self.name} (system={self.is_system})>"
    
    def get_symbols_list(self) -> list:
        """Get symbols as a list"""
        if not self.symbols:
            return []
        return [s.strip() for s in self.symbols.split(",") if s.strip()]
    
    def set_symbols_list(self, symbols: list) -> None:
        """Set symbols from a list"""
        self.symbols = ",".join(symbols)
    
    def to_dict(self) -> dict:
        """Convert trade idea to dictionary"""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "is_system": self.is_system,
            "is_default": self.is_default,
            "display_order": self.display_order,
            "user_id": self.user_id,
            "symbols": self.get_symbols_list(),
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
