"""
User and UserSettings database models
- Portions generated by AI
"""

import uuid
from datetime import datetime, date
from sqlalchemy import Column, String, Integer, Float, Date, DateTime, Text, ForeignKey, Index
from sqlalchemy.orm import relationship

from ..core.database import Base


class User(Base):
    """User model for database"""
    __tablename__ = "users"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    clerk_user_id = Column(String(255), unique=True, nullable=False, index=True)
    email = Column(String(255), unique=True, index=True)
    subscription_status = Column(String(20), default="free")  # free, pro, cancelled
    stripe_customer_id = Column(String(255), index=True)
    screens_today = Column(Integer, default=0)
    last_screen_date = Column(Date)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship to settings
    settings = relationship("UserSettings", back_populates="user", uselist=False, cascade="all, delete-orphan")
    
    # Relationships to filters and trade ideas
    filters = relationship("Filter", back_populates="user", cascade="all, delete-orphan")
    trade_ideas = relationship("TradeIdea", back_populates="user", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<User {self.email}>"


class UserSettings(Base):
    """User settings model for database"""
    __tablename__ = "user_settings"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    
    # Watchlist
    symbols = Column(Text, default="AAPL,MSFT,GOOGL,SPY,QQQ")  # Comma-separated
    
    # Options strategy
    max_dte = Column(Integer, default=45)
    min_dte = Column(Integer, default=15)
    min_volume = Column(Integer, default=10)
    min_open_interest = Column(Integer, default=10)
    
    # Screening criteria
    min_annualized_return = Column(Float, default=20.0)
    max_assignment_probability = Column(Integer, default=20)
    
    # New: Selected filter and trade idea (nullable for backward compatibility)
    selected_filter_id = Column(String(36), ForeignKey("filters.id", ondelete="SET NULL"), nullable=True)
    selected_trade_idea_id = Column(String(36), ForeignKey("trade_ideas.id", ondelete="SET NULL"), nullable=True)
    
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship to user
    user = relationship("User", back_populates="settings")
    
    # Relationships to selected filter and trade idea
    selected_filter = relationship("Filter", foreign_keys=[selected_filter_id])
    selected_trade_idea = relationship("TradeIdea", foreign_keys=[selected_trade_idea_id])
    
    def __repr__(self):
        return f"<UserSettings for user_id={self.user_id}>"
    
    def to_dict(self) -> dict:
        """Convert settings to dictionary (legacy format for backward compatibility)"""
        symbols_list = [s.strip() for s in self.symbols.split(",") if s.strip()] if self.symbols else []
        return {
            "symbols": symbols_list,
            "max_dte": self.max_dte,
            "min_dte": self.min_dte,
            "min_volume": self.min_volume,
            "min_open_interest": self.min_open_interest,
            "min_annualized_return": self.min_annualized_return,
            "max_assignment_probability": self.max_assignment_probability,
            "selected_filter_id": self.selected_filter_id,
            "selected_trade_idea_id": self.selected_trade_idea_id,
        }
