/**
 * ApiProviderCard component for admin API provider configuration
 * - Portions generated by AI
 */

import { useState, useEffect, useCallback } from 'react';
import { Cloud, Save, RefreshCw, CheckCircle, XCircle, Zap } from 'lucide-react';
import apiClient from '@/api/client';
import type { ApiProviderSettings } from '@/types';

interface ApiProviderCardProps {
  isReady: boolean;
}

export function ApiProviderCard({ isReady }: ApiProviderCardProps) {
  const [settings, setSettings] = useState<ApiProviderSettings | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  // Form state
  const [activeProvider, setActiveProvider] = useState<'massive' | 'alpaca'>('massive');
  const [useMidpointPricing, setUseMidpointPricing] = useState(true);

  // Load settings
  useEffect(() => {
    if (!isReady) return;

    const loadSettings = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await apiClient.getApiProviderSettings();
        setSettings(data);
        setActiveProvider(data.active_provider);
        setUseMidpointPricing(data.use_midpoint_pricing);
      } catch (err: any) {
        console.error('Failed to load API provider settings:', err);
        setError('Failed to load API provider settings');
      } finally {
        setLoading(false);
      }
    };

    loadSettings();
  }, [isReady]);

  // Save settings
  const handleSave = useCallback(async () => {
    setSaving(true);
    setError(null);
    setSuccess(false);

    try {
      const updated = await apiClient.updateApiProviderSettings({
        active_provider: activeProvider,
        use_midpoint_pricing: useMidpointPricing,
      });
      setSettings(updated);
      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      console.error('Failed to save API provider settings:', err);
      setError(err.response?.data?.detail || 'Failed to save API provider settings');
    } finally {
      setSaving(false);
    }
  }, [activeProvider, useMidpointPricing]);

  // Check if form has changes
  const hasChanges =
    settings &&
    (activeProvider !== settings.active_provider ||
      useMidpointPricing !== settings.use_midpoint_pricing);

  if (loading) {
    return (
      <div className="card">
        <div className="flex items-center gap-2 mb-4">
          <Cloud size={20} className="text-primary-400" />
          <h2 className="text-xl font-semibold">API Provider</h2>
        </div>
        <div className="flex items-center justify-center py-8 text-gray-400">
          <RefreshCw size={20} className="animate-spin mr-2" />
          Loading...
        </div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Cloud size={20} className="text-primary-400" />
          <h2 className="text-xl font-semibold">API Provider</h2>
        </div>
        {settings?.updated_at && (
          <span className="text-xs text-gray-500">
            Last updated: {new Date(settings.updated_at).toLocaleString()}
          </span>
        )}
      </div>

      {error && (
        <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">
          {error}
        </div>
      )}

      {success && (
        <div className="mb-4 p-3 bg-green-500/10 border border-green-500/30 rounded-lg text-green-400 text-sm">
          API provider settings saved successfully!
        </div>
      )}

      <div className="space-y-4">
        {/* Provider Selection */}
        <div className="space-y-3">
          <label className="block text-sm font-medium text-white">Select Data Provider</label>
          
          {/* Massive Option */}
          <div
            onClick={() => settings?.massive_api_configured && setActiveProvider('massive')}
            className={`p-4 rounded-lg border-2 transition-all cursor-pointer ${
              activeProvider === 'massive'
                ? 'border-primary-500 bg-primary-500/10'
                : settings?.massive_api_configured
                ? 'border-white/10 bg-dark-800 hover:border-white/20'
                : 'border-white/5 bg-dark-800 opacity-50 cursor-not-allowed'
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-white">Massive.com API</span>
                  {settings?.massive_api_configured ? (
                    <span className="flex items-center gap-1 text-xs text-green-400">
                      <CheckCircle size={12} />
                      Configured
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-xs text-red-400">
                      <XCircle size={12} />
                      Not Configured
                    </span>
                  )}
                </div>
                <p className="text-sm text-gray-400 mt-1">
                  Options data with 15-minute delay. Uses Yahoo Finance for stock prices.
                </p>
              </div>
              <div
                className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                  activeProvider === 'massive'
                    ? 'border-primary-500 bg-primary-500'
                    : 'border-gray-600'
                }`}
              >
                {activeProvider === 'massive' && (
                  <div className="w-2 h-2 rounded-full bg-white" />
                )}
              </div>
            </div>
          </div>

          {/* Alpaca Option */}
          <div
            onClick={() => settings?.alpaca_api_configured && setActiveProvider('alpaca')}
            className={`p-4 rounded-lg border-2 transition-all cursor-pointer ${
              activeProvider === 'alpaca'
                ? 'border-primary-500 bg-primary-500/10'
                : settings?.alpaca_api_configured
                ? 'border-white/10 bg-dark-800 hover:border-white/20'
                : 'border-white/5 bg-dark-800 opacity-50 cursor-not-allowed'
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-white">Alpaca API</span>
                  <span className="flex items-center gap-1 text-xs text-yellow-400">
                    <Zap size={12} />
                    Real-time
                  </span>
                  {settings?.alpaca_api_configured ? (
                    <span className="flex items-center gap-1 text-xs text-green-400">
                      <CheckCircle size={12} />
                      Configured
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-xs text-red-400">
                      <XCircle size={12} />
                      Not Configured
                    </span>
                  )}
                </div>
                <p className="text-sm text-gray-400 mt-1">
                  Real-time stock and options data with bid/ask quotes and Greeks.
                  Requires Algo Trader Plus subscription.
                </p>
              </div>
              <div
                className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                  activeProvider === 'alpaca'
                    ? 'border-primary-500 bg-primary-500'
                    : 'border-gray-600'
                }`}
              >
                {activeProvider === 'alpaca' && (
                  <div className="w-2 h-2 rounded-full bg-white" />
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Mid-point Pricing Toggle (Alpaca only) */}
        <div
          className={`p-3 bg-dark-800 rounded-lg transition-opacity ${
            activeProvider !== 'alpaca' ? 'opacity-50 pointer-events-none' : ''
          }`}
        >
          <div className="flex items-center justify-between">
            <div>
              <label className="font-medium text-white">Use Mid-point Pricing</label>
              <p className="text-xs text-gray-500 mt-0.5">
                Calculate prices as (bid + ask) / 2 for more accurate values
              </p>
            </div>
            <button
              onClick={() => setUseMidpointPricing(!useMidpointPricing)}
              className={`relative w-12 h-6 rounded-full transition-colors ${
                useMidpointPricing ? 'bg-primary-500' : 'bg-gray-600'
              }`}
            >
              <span
                className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${
                  useMidpointPricing ? 'left-7' : 'left-1'
                }`}
              />
            </button>
          </div>
        </div>

        {/* Save Button */}
        <button
          onClick={handleSave}
          disabled={saving || !hasChanges}
          className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-lg font-medium transition-colors ${
            hasChanges
              ? 'bg-primary-500 hover:bg-primary-600 text-white'
              : 'bg-gray-700 text-gray-400 cursor-not-allowed'
          }`}
        >
          {saving ? (
            <>
              <RefreshCw size={16} className="animate-spin" />
              Saving...
            </>
          ) : (
            <>
              <Save size={16} />
              Save Changes
            </>
          )}
        </button>
      </div>
    </div>
  );
}
