/**
 * BreakoutScannerCard - admin UI for the Momentum Stocks breakout scanner
 * - Portions generated by AI
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Rocket,
  Save,
  RefreshCw,
  Play,
  CheckCircle,
  XCircle,
  AlertTriangle,
  TrendingUp,
  Zap,
  Eye,
  Users,
  Flame,
  Gauge,
  ChevronDown,
  ChevronRight,
  Sliders,
  RotateCcw,
  Clock,
  CalendarClock,
} from 'lucide-react';
import apiClient from '@/api/client';
import type {
  BreakoutScannerSettings,
  BreakoutScanResultItem,
} from '@/types';
import { formatMarketTime } from '@/utils/marketTime';

interface BreakoutScannerCardProps {
  isReady: boolean;
  /** Called when a scan finishes so the parent can refresh the Trade Ideas list. */
  onScanComplete?: () => void;
}

const SETUP_LABELS: Record<string, string> = {
  bull_flag: 'Bull Flag',
  tight_at_pivot: 'Tight at Pivot',
  squeeze_breakout_setup: 'Squeeze + Pivot',
  volatility_squeeze: 'Volatility Squeeze',
  vcp_base: 'VCP Base',
  flat_base: 'Flat Base',
  ascending_base: 'Ascending Base',
  consolidation: 'Consolidation',
};

/** Display order and labels for the scoring factor groups. */
const FACTOR_GROUPS: { key: string; label: string; hint: string }[] = [
  { key: 'compression_vcp', label: 'Compression / VCP', hint: 'Bollinger squeeze, contraction, volume dry-up, base quality' },
  { key: 'base_construction', label: 'Base Construction', hint: 'Base maturity, up/down volume accumulation, tight closes' },
  { key: 'pivot', label: 'Pivot Proximity', hint: 'How close price is to the breakout pivot, measured in ATRs' },
  { key: 'leadership', label: 'Leadership', hint: 'Relative strength vs SPY and sector, 52-week-high proximity' },
  { key: 'flow_oi', label: 'Flow + OI', hint: 'Bullish options flow and call open-interest accumulation' },
  { key: 'darkpool_smart', label: 'Dark Pool + Smart Money', hint: 'Institutional block prints, insider and congress buying' },
  { key: 'gex', label: 'Dealer Gamma', hint: 'Short dealer gamma accelerates breakouts' },
];

/** Python weekday() numbering, which is what the backend stores. */
const DAY_LABELS: { value: number; label: string }[] = [
  { value: 0, label: 'Mon' },
  { value: 1, label: 'Tue' },
  { value: 2, label: 'Wed' },
  { value: 3, label: 'Thu' },
  { value: 4, label: 'Fri' },
  { value: 5, label: 'Sat' },
  { value: 6, label: 'Sun' },
];

/** Common zones. Any valid IANA name the backend already has is appended. */
const TIMEZONE_OPTIONS = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'UTC',
  'Europe/London',
  'Asia/Kolkata',
  'Asia/Singapore',
  'Asia/Tokyo',
  'Australia/Sydney',
];

/** "in 3h 20m" / "in 2d" for the next scheduled run, or null if it has passed. */
function formatCountdown(iso: string | null): string | null {
  if (!iso) return null;
  const ms = new Date(iso).getTime() - Date.now();
  if (Number.isNaN(ms)) return null;
  if (ms <= 0) return 'due now';
  const minutes = Math.round(ms / 60000);
  if (minutes < 60) return `in ${minutes}m`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `in ${hours}h ${minutes % 60}m`;
  const days = Math.floor(hours / 24);
  return `in ${days}d ${hours % 24}h`;
}

const REGIME_STYLES: Record<string, { label: string; cls: string }> = {
  risk_on: { label: 'Risk On', cls: 'bg-green-500/15 text-green-300 border-green-500/30' },
  neutral: { label: 'Neutral', cls: 'bg-yellow-500/15 text-yellow-300 border-yellow-500/30' },
  risk_off: { label: 'Risk Off', cls: 'bg-red-500/15 text-red-300 border-red-500/30' },
};

function fearGreedLabel(score: number): string {
  if (score >= 75) return 'Extreme Greed';
  if (score >= 60) return 'Greed';
  if (score >= 40) return 'Neutral';
  if (score >= 25) return 'Fear';
  return 'Extreme Fear';
}

function parseUniverse(text: string): string[] {
  return Array.from(
    new Set(
      text
        .split(/[\s,]+/)
        .map((s) => s.trim().toUpperCase())
        .filter(Boolean)
    )
  );
}

function scoreColorClass(score: number): string {
  if (score >= 70) return 'text-green-400';
  if (score >= 50) return 'text-yellow-400';
  return 'text-gray-400';
}

function formatPct(value: number | null, digits = 1): string {
  if (value == null) return '—';
  return `${value > 0 ? '+' : ''}${value.toFixed(digits)}%`;
}

function formatMoney(value: number | null, digits = 2): string {
  if (value == null) return '—';
  return `$${value.toFixed(digits)}`;
}

/**
 * Per-candidate score explanation: how each weighted factor group contributed
 * to the final 0-100 Breakout Readiness Score.
 */
function FactorBreakdown({
  result,
  weights,
}: {
  result: BreakoutScanResultItem;
  weights: Record<string, number>;
}) {
  const breakdown = result.factor_breakdown || {};
  const penalty = breakdown.penalty ?? 0;
  const regimeScale = breakdown.regime_scale ?? 1;

  const rows = FACTOR_GROUPS.filter((g) => breakdown[g.key] != null).map((g) => {
    const value = breakdown[g.key];
    const weight = weights[g.key] ?? 0;
    return { ...g, value, weight, contribution: value * weight };
  });

  if (rows.length === 0) {
    return (
      <p className="text-xs text-gray-500">
        No factor breakdown was stored for this candidate.
      </p>
    );
  }

  const base = rows.reduce((sum, r) => sum + r.contribution, 0);

  return (
    <div className="space-y-3">
      <div className="space-y-1.5">
        {rows.map((row) => (
          <div key={row.key} className="grid grid-cols-[1fr_auto] gap-x-3 items-center">
            <div className="min-w-0">
              <div className="flex items-baseline justify-between gap-2">
                <span className="text-[11px] text-gray-300 truncate" title={row.hint}>
                  {row.label}
                </span>
                <span className="text-[10px] text-gray-500 shrink-0">
                  {(row.value * 100).toFixed(0)} x {(row.weight * 100).toFixed(0)}%
                </span>
              </div>
              <div className="h-1.5 mt-1 bg-dark-700 rounded-full overflow-hidden">
                <div
                  className="h-full bg-primary-500/70 rounded-full"
                  style={{ width: `${Math.max(0, Math.min(100, row.value * 100))}%` }}
                />
              </div>
            </div>
            <span className="text-[11px] font-medium text-white tabular-nums w-10 text-right">
              {(row.contribution * 100).toFixed(1)}
            </span>
          </div>
        ))}
      </div>

      <div className="pt-2 border-t border-white/5 space-y-1 text-[11px]">
        <div className="flex justify-between text-gray-400">
          <span>Weighted base</span>
          <span className="tabular-nums text-gray-200">{(base * 100).toFixed(1)}</span>
        </div>
        {penalty > 0 && (
          <div className="flex justify-between text-red-300">
            <span>Penalties</span>
            <span className="tabular-nums">-{(penalty * 100).toFixed(1)}</span>
          </div>
        )}
        <div className="flex justify-between text-gray-400">
          <span>Market regime</span>
          <span className="tabular-nums text-gray-200">x{regimeScale.toFixed(2)}</span>
        </div>
        <div className="flex justify-between font-semibold text-white pt-1 border-t border-white/5">
          <span>Score</span>
          <span className="tabular-nums">{result.score.toFixed(1)}</span>
        </div>
      </div>
    </div>
  );
}

/** Context a CSP seller needs that is not already a column. */
function CandidateContext({ result }: { result: BreakoutScanResultItem }) {
  const items: { label: string; value: string }[] = [
    { label: 'Pivot', value: formatMoney(result.pivot_price) },
    { label: 'To pivot', value: formatPct(result.pct_to_pivot, 2) },
    { label: 'From 52wk high', value: result.pct_from_52wk_high != null ? `-${result.pct_from_52wk_high.toFixed(1)}%` : '—' },
    { label: 'Implied move', value: result.implied_move != null ? `${result.implied_move.toFixed(2)}%` : '—' },
    { label: 'IV vs realized', value: result.iv_vs_realized != null ? `${result.iv_vs_realized.toFixed(2)}x` : '—' },
    { label: 'Volume vs 50d', value: result.volume_expansion != null ? `${result.volume_expansion.toFixed(2)}x` : '—' },
    { label: 'Gamma wall', value: formatMoney(result.gamma_wall) },
    { label: 'Max pain', value: formatMoney(result.max_pain) },
    { label: 'Next earnings', value: result.next_earnings_date || '—' },
  ];

  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-1.5">
      {items.map((item) => (
        <div key={item.label} className="flex justify-between gap-2 text-[11px]">
          <span className="text-gray-500 truncate">{item.label}</span>
          <span className="text-gray-200 tabular-nums shrink-0">{item.value}</span>
        </div>
      ))}
    </div>
  );
}

function CandidateDetail({
  result,
  weights,
}: {
  result: BreakoutScanResultItem;
  weights: Record<string, number>;
}) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 p-3 bg-dark-800/60 rounded-lg border border-white/5">
      <div>
        <h4 className="text-[11px] font-semibold text-gray-400 uppercase tracking-wide mb-2">
          Score Breakdown
        </h4>
        <FactorBreakdown result={result} weights={weights} />
      </div>
      <div>
        <h4 className="text-[11px] font-semibold text-gray-400 uppercase tracking-wide mb-2">
          Context
        </h4>
        <CandidateContext result={result} />
      </div>
    </div>
  );
}

function BreakoutResultSignals({ result }: { result: BreakoutScanResultItem }) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      {(result.bullish_flow_score ?? 0) > 0 && (
        <span className="inline-flex items-center gap-1 text-[10px] text-yellow-300">
          <Zap size={12} className="text-yellow-400 shrink-0" aria-hidden />
          Flow
        </span>
      )}
      {result.gex_regime === 'short_gamma' && (
        <span className="inline-flex items-center gap-1 text-[10px] text-green-300">
          <TrendingUp size={12} className="text-green-400 shrink-0" aria-hidden />
          Short gamma
        </span>
      )}
      {result.dark_pool_accum && (
        <span className="inline-flex items-center gap-1 text-[10px] text-blue-300">
          <Eye size={12} className="text-blue-400 shrink-0" aria-hidden />
          Dark pool
        </span>
      )}
      {result.smart_money && (
        <span className="inline-flex items-center gap-1 text-[10px] text-purple-300">
          <Users size={12} className="text-purple-400 shrink-0" aria-hidden />
          Smart money
        </span>
      )}
      {result.earnings_flag && (
        <span className="inline-flex items-center gap-1 text-[10px] text-red-300">
          <AlertTriangle size={12} className="text-red-400 shrink-0" aria-hidden />
          Earnings
        </span>
      )}
    </div>
  );
}

function BreakoutResultSignalsCompact({ result }: { result: BreakoutScanResultItem }) {
  return (
    <div className="flex items-center justify-center gap-1.5">
      {(result.bullish_flow_score ?? 0) > 0 && <Zap size={12} className="text-yellow-400" aria-label="Bullish flow" />}
      {result.gex_regime === 'short_gamma' && <TrendingUp size={12} className="text-green-400" aria-label="Short gamma" />}
      {result.dark_pool_accum && <Eye size={12} className="text-blue-400" aria-label="Dark pool accumulation" />}
      {result.smart_money && <Users size={12} className="text-purple-400" aria-label="Smart money" />}
      {result.earnings_flag && <AlertTriangle size={12} className="text-red-400" aria-label="Earnings within CSP window" />}
    </div>
  );
}

function BreakoutResultCard({
  result,
  weights,
  expanded,
  onToggle,
}: {
  result: BreakoutScanResultItem;
  weights: Record<string, number>;
  expanded: boolean;
  onToggle: () => void;
}) {
  const setupLabel = SETUP_LABELS[result.setup_type || ''] || result.setup_type || '—';

  return (
    <div className="bg-dark-800/50 rounded-xl border border-white/10 p-3 sm:p-4">
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-500">#{result.rank}</span>
            <span className="text-lg font-bold text-white">{result.symbol}</span>
          </div>
          <p className="text-xs text-gray-400 mt-0.5 truncate" title={setupLabel}>
            {setupLabel}
          </p>
        </div>
        <span className={`shrink-0 px-2.5 py-1 rounded-full text-sm font-semibold bg-dark-700 border border-white/10 ${scoreColorClass(result.score)}`}>
          {result.score.toFixed(0)}
        </span>
      </div>

      <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
        <div className="flex justify-between gap-2">
          <span className="text-gray-500">Price</span>
          <span className="text-white font-medium">{formatMoney(result.current_price)}</span>
        </div>
        <div className="flex justify-between gap-2">
          <span className="text-gray-500">IVR</span>
          <span className="text-white font-medium">
            {result.iv_rank != null ? result.iv_rank.toFixed(0) : '—'}
          </span>
        </div>
        <div className="flex justify-between gap-2">
          <span className="text-gray-500">Pivot</span>
          <span className="text-white font-medium">{formatMoney(result.pivot_price)}</span>
        </div>
        <div className="flex justify-between gap-2">
          <span className="text-gray-500">To pivot</span>
          <span className="text-white font-medium">{formatPct(result.pct_to_pivot, 2)}</span>
        </div>
        <div className="col-span-2 flex justify-between gap-2 border-t border-white/5 pt-2">
          <span className="text-gray-500">CSP Strike</span>
          <span className="text-primary-300 font-medium">
            {result.suggested_put_strike != null ? `$${result.suggested_put_strike}` : '—'}
          </span>
        </div>
      </div>

      <div className="mt-3 pt-3 border-t border-white/5">
        <BreakoutResultSignals result={result} />
      </div>

      <button
        onClick={onToggle}
        aria-expanded={expanded}
        className="mt-3 w-full flex items-center justify-center gap-1 text-[11px] text-gray-400 hover:text-white py-1.5 rounded-lg bg-dark-700/50 transition-colors"
      >
        {expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
        {expanded ? 'Hide' : 'Why this score?'}
      </button>

      {expanded && (
        <div className="mt-3">
          <CandidateDetail result={result} weights={weights} />
        </div>
      )}
    </div>
  );
}

export function BreakoutScannerCard({ isReady, onScanComplete }: BreakoutScannerCardProps) {
  const [settings, setSettings] = useState<BreakoutScannerSettings | null>(null);
  const [results, setResults] = useState<BreakoutScanResultItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  // Form state
  const [universeText, setUniverseText] = useState('');
  const [universeMode, setUniverseMode] = useState<'curated' | 'auto'>('curated');
  const [autoUniverseSize, setAutoUniverseSize] = useState(300);
  const [topN, setTopN] = useState(15);
  const [deepDiveN, setDeepDiveN] = useState(40);
  const [useUw, setUseUw] = useState(true);
  const [enabled, setEnabled] = useState(true);
  const [minPrice, setMinPrice] = useState(10);
  const [maxPrice, setMaxPrice] = useState(600);
  const [minVolume, setMinVolume] = useState(500000);
  const [requireSma200, setRequireSma200] = useState(false);
  const [cspDte, setCspDte] = useState(35);
  const [weights, setWeights] = useState<Record<string, number>>({});
  const [showWeights, setShowWeights] = useState(false);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [autoScanEnabled, setAutoScanEnabled] = useState(false);
  const [autoScanTime, setAutoScanTime] = useState('16:30');
  const [autoScanTimezone, setAutoScanTimezone] = useState('America/New_York');
  const [autoScanDays, setAutoScanDays] = useState<number[]>([0, 1, 2, 3, 4]);

  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const applySettings = useCallback((data: BreakoutScannerSettings) => {
    setSettings(data);
    setUniverseText(data.universe.join(', '));
    setUniverseMode((data.universe_mode as 'curated' | 'auto') || 'curated');
    setAutoUniverseSize(data.auto_universe_size || 300);
    setTopN(data.top_n);
    setDeepDiveN(data.deep_dive_n);
    setUseUw(data.use_unusual_whales);
    setEnabled(data.enabled);
    setMinPrice(data.min_price);
    setMaxPrice(data.max_price);
    setMinVolume(data.min_avg_volume);
    setRequireSma200(data.require_above_sma200);
    setCspDte(data.typical_csp_dte);
    setAutoScanEnabled(data.auto_scan_enabled);
    setAutoScanTime(data.auto_scan_time);
    setAutoScanTimezone(data.auto_scan_timezone);
    setAutoScanDays(data.auto_scan_days);
    // Seed the editor from the effective weights so sliders always start from
    // what the scanner actually applied, not an empty override map.
    setWeights({ ...data.effective_weights });
  }, []);

  const toggleScanDay = useCallback((day: number) => {
    setAutoScanDays((prev) =>
      prev.includes(day) ? prev.filter((d) => d !== day) : [...prev, day].sort()
    );
  }, []);

  const toggleExpanded = useCallback((symbol: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(symbol)) next.delete(symbol);
      else next.add(symbol);
      return next;
    });
  }, []);

  const loadResults = useCallback(async () => {
    try {
      const res = await apiClient.getBreakoutResults();
      setResults(res.results);
    } catch (err) {
      console.error('Failed to load breakout results:', err);
    }
  }, []);

  // Initial load
  useEffect(() => {
    if (!isReady) return;
    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await apiClient.getBreakoutSettings();
        applySettings(data);
        await loadResults();
      } catch (err) {
        console.error('Failed to load breakout settings:', err);
        setError('Failed to load breakout scanner settings');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [isReady, applySettings, loadResults]);

  // Poll while a scan is running
  const startPolling = useCallback(() => {
    if (pollRef.current) clearInterval(pollRef.current);
    pollRef.current = setInterval(async () => {
      try {
        const data = await apiClient.getBreakoutSettings();
        setSettings(data);
        if (data.last_run_status !== 'running') {
          if (pollRef.current) clearInterval(pollRef.current);
          pollRef.current = null;
          await loadResults();
          // Tell the parent to refresh its Trade Ideas list (Momentum Stocks
          // was just republished by the backend).
          onScanComplete?.();
        }
      } catch {
        /* keep polling */
      }
    }, 4000);
  }, [loadResults, onScanComplete]);

  useEffect(() => {
    if (settings?.last_run_status === 'running' && !pollRef.current) {
      startPolling();
    }
    return () => {
      if (pollRef.current) {
        clearInterval(pollRef.current);
        pollRef.current = null;
      }
    };
  }, [settings?.last_run_status, startPolling]);

  const handleSave = useCallback(async () => {
    setSaving(true);
    setError(null);
    setSuccess(null);
    try {
      const updated = await apiClient.updateBreakoutSettings({
        enabled,
        universe: parseUniverse(universeText),
        universe_mode: universeMode,
        auto_universe_size: autoUniverseSize,
        top_n: topN,
        deep_dive_n: deepDiveN,
        use_unusual_whales: useUw,
        weights,
        min_price: minPrice,
        max_price: maxPrice,
        min_avg_volume: minVolume,
        require_above_sma200: requireSma200,
        typical_csp_dte: cspDte,
        auto_scan_enabled: autoScanEnabled,
        auto_scan_time: autoScanTime,
        auto_scan_timezone: autoScanTimezone,
        auto_scan_days: autoScanDays,
      });
      applySettings(updated);
      setSuccess('Settings saved');
      setTimeout(() => setSuccess(null), 3000);
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to save settings');
    } finally {
      setSaving(false);
    }
  }, [enabled, universeText, universeMode, autoUniverseSize, topN, deepDiveN, useUw, weights, minPrice, maxPrice, minVolume, requireSma200, cspDte, autoScanEnabled, autoScanTime, autoScanTimezone, autoScanDays, applySettings]);

  const handleRun = useCallback(async () => {
    setError(null);
    setSuccess(null);
    try {
      const res = await apiClient.runBreakoutScan();
      if (res.status === 'error') {
        setError(res.message);
        return;
      }
      setSuccess(res.message);
      setSettings((prev) => (prev ? { ...prev, last_run_status: 'running' } : prev));
      startPolling();
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to start scan');
    }
  }, [startPolling]);

  const handleReset = useCallback(async () => {
    setError(null);
    setSuccess(null);
    if (pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
    try {
      const updated = await apiClient.resetBreakoutStatus();
      setSettings(updated);
      setSuccess('Status reset');
      setTimeout(() => setSuccess(null), 3000);
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to reset status');
    }
  }, []);

  const universeCount = parseUniverse(universeText).length;
  // Explanations must reflect the weights the scan actually used, not unsaved
  // slider edits, so read them from the persisted settings.
  const effectiveWeights = settings?.effective_weights ?? {};
  const isRunning = settings?.last_run_status === 'running';
  const canRun = universeMode === 'auto' || universeCount > 0;
  const canReset =
    settings?.last_run_status === 'running' || settings?.last_run_status === 'error';
  // The backend rejects an empty day set; block the save rather than surfacing a 422.
  const scheduleInvalid = autoScanEnabled && autoScanDays.length === 0;

  if (loading) {
    return (
      <div className="card">
        <div className="flex items-center gap-2 mb-4">
          <Rocket size={20} className="text-primary-400" />
          <h2 className="text-xl font-semibold">Breakout Scanner</h2>
        </div>
        <div className="flex items-center justify-center py-8 text-gray-400">
          <RefreshCw size={20} className="animate-spin mr-2" />
          Loading...
        </div>
      </div>
    );
  }

  return (
    <div className="card min-w-0 overflow-hidden">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between mb-4">
        <div className="flex flex-wrap items-center gap-2 min-w-0">
          <Rocket size={20} className="text-primary-400 shrink-0" />
          <h2 className="text-xl font-semibold">Breakout Scanner</h2>
          <span className="text-xs px-1.5 py-0.5 rounded bg-primary-500/20 text-primary-300">
            Momentum Stocks
          </span>
        </div>
        {settings?.unusual_whales_configured ? (
          <span className="flex items-center gap-1 text-xs text-green-400 shrink-0">
            <CheckCircle size={12} /> Unusual Whales
          </span>
        ) : (
          <span className="flex items-center gap-1 text-xs text-yellow-400 shrink-0">
            <AlertTriangle size={12} /> No UW key
          </span>
        )}
      </div>

      <p className="text-xs text-gray-500 mb-4">
        Scans your ticker universe for pre-breakout setups (volatility squeeze, VCP,
        relative strength, bullish flow, dark-pool & smart-money accumulation) and
        publishes the top picks to the "Momentum Stocks" trade idea.
      </p>

      {error && (
        <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">
          {error}
        </div>
      )}
      {success && (
        <div className="mb-4 p-3 bg-green-500/10 border border-green-500/30 rounded-lg text-green-400 text-sm">
          {success}
        </div>
      )}

      <div className="space-y-4">
        {/* Universe Mode */}
        <div>
          <label className="text-sm font-medium text-white block mb-2">Universe Source</label>
          <div className="flex gap-2 mb-3">
            <button
              onClick={() => setUniverseMode('curated')}
              className={`flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-colors border ${
                universeMode === 'curated'
                  ? 'bg-primary-500/20 border-primary-500/50 text-primary-300'
                  : 'bg-dark-700 border-white/10 text-gray-400 hover:text-white'
              }`}
            >
              Curated
            </button>
            <button
              onClick={() => setUniverseMode('auto')}
              className={`flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-colors border ${
                universeMode === 'auto'
                  ? 'bg-primary-500/20 border-primary-500/50 text-primary-300'
                  : 'bg-dark-700 border-white/10 text-gray-400 hover:text-white'
              }`}
            >
              Auto (UW)
            </button>
          </div>

          {universeMode === 'auto' && (
            <div className="mb-3 p-3 bg-dark-800 rounded-lg border border-white/5">
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-medium text-gray-300">Max symbols to scan</label>
                <span className="text-xs text-gray-500">{autoUniverseSize} tickers</span>
              </div>
              <input
                type="number"
                min={50}
                max={500}
                step={50}
                value={autoUniverseSize}
                onChange={(e) => setAutoUniverseSize(Math.max(50, Math.min(500, parseInt(e.target.value) || 300)))}
                className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
              />
              <p className="text-xs text-gray-500 mt-1.5">
                Fetches the top optionable US equities by options volume from Unusual Whales. Requires UW API key.
              </p>
            </div>
          )}

          {/* Curated tickers — in auto mode these are supplemental additions */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-medium text-gray-300">
                {universeMode === 'auto' ? 'Additional tickers (always included)' : 'Tickers'}
              </label>
              {universeCount > 0 && (
                <span className="text-xs text-gray-500">{universeCount} tickers</span>
              )}
            </div>
            <textarea
              value={universeText}
              onChange={(e) => setUniverseText(e.target.value)}
              rows={universeMode === 'auto' ? 2 : 4}
              placeholder={universeMode === 'auto' ? 'Optional: AAPL, NVDA, ...' : 'AAPL, NVDA, PLTR, AMD, ...'}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500 font-mono"
            />
            <p className="text-xs text-gray-500 mt-1">
              Separate with commas, spaces, or new lines.
            </p>
          </div>
        </div>

        {/* Numeric config grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="block text-xs font-medium text-gray-300 mb-1">Top N picks</label>
            <input
              type="number" min={1} max={50} value={topN}
              onChange={(e) => setTopN(Math.max(1, parseInt(e.target.value) || 1))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-300 mb-1">Earnings window (DTE)</label>
            <input
              type="number" min={0} max={120} value={cspDte}
              onChange={(e) => setCspDte(Math.max(0, parseInt(e.target.value) || 0))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-300 mb-1">Min price ($)</label>
            <input
              type="number" min={0} value={minPrice}
              onChange={(e) => setMinPrice(Math.max(0, parseFloat(e.target.value) || 0))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-300 mb-1">Max price ($)</label>
            <input
              type="number" min={0} value={maxPrice}
              onChange={(e) => setMaxPrice(Math.max(0, parseFloat(e.target.value) || 0))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-300 mb-1">Min avg volume</label>
            <input
              type="number" min={0} step={50000} value={minVolume}
              onChange={(e) => setMinVolume(Math.max(0, parseInt(e.target.value) || 0))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
          <div>
            <label
              className="block text-xs font-medium text-gray-300 mb-1"
              title="How many of the strongest structures get the expensive per-ticker Unusual Whales calls"
            >
              Deep-dive count
            </label>
            <input
              type="number" min={1} max={200} value={deepDiveN}
              onChange={(e) => setDeepDiveN(Math.max(1, parseInt(e.target.value) || 1))}
              className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
            />
          </div>
        </div>

        {/* Factor weights */}
        <div className="bg-dark-800 rounded-lg">
          <button
            onClick={() => setShowWeights((v) => !v)}
            aria-expanded={showWeights}
            className="w-full p-3 flex items-center justify-between gap-3 text-left"
          >
            <div className="flex items-center gap-2 min-w-0">
              <Sliders size={14} className="text-primary-400 shrink-0" />
              <div className="min-w-0">
                <span className="font-medium text-white text-sm">Factor weights</span>
                <p className="text-xs text-gray-500 mt-0.5">
                  Relative importance of each scoring group
                </p>
              </div>
            </div>
            {showWeights ? (
              <ChevronDown size={16} className="text-gray-400 shrink-0" />
            ) : (
              <ChevronRight size={16} className="text-gray-400 shrink-0" />
            )}
          </button>

          {showWeights && (
            <div className="px-3 pb-3 space-y-3">
              <p className="text-xs text-gray-500">
                Weights are renormalized to 100% when the scan runs, so only the ratios
                between them matter. Set a group to 0 to disable it entirely.
              </p>
              {FACTOR_GROUPS.map((group) => {
                const value = weights[group.key] ?? 0;
                return (
                  <div key={group.key}>
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <label className="text-xs text-gray-300 truncate" title={group.hint}>
                        {group.label}
                      </label>
                      <span className="text-xs text-gray-400 tabular-nums shrink-0">
                        {(value * 100).toFixed(0)}%
                      </span>
                    </div>
                    <input
                      type="range"
                      min={0}
                      max={50}
                      step={1}
                      value={Math.round(value * 100)}
                      onChange={(e) =>
                        setWeights((prev) => ({
                          ...prev,
                          [group.key]: parseInt(e.target.value) / 100,
                        }))
                      }
                      className="w-full accent-primary-500"
                      aria-label={`${group.label} weight`}
                    />
                  </div>
                );
              })}
              <button
                onClick={() => settings && setWeights({ ...settings.effective_weights })}
                className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white transition-colors"
              >
                <RotateCcw size={12} />
                Revert to saved
              </button>
            </div>
          )}
        </div>

        {/* Toggles */}
        <div className="p-3 bg-dark-800 rounded-lg flex items-center justify-between gap-3">
          <div className="min-w-0 flex-1">
            <label className="font-medium text-white text-sm">Scanner enabled</label>
            <p className="text-xs text-gray-500 mt-0.5">
              Turn off to block both manual and scheduled scans
            </p>
          </div>
          <button
            onClick={() => setEnabled(!enabled)}
            className={`relative shrink-0 w-12 h-6 rounded-full transition-colors ${enabled ? 'bg-primary-500' : 'bg-gray-600'}`}
          >
            <span className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${enabled ? 'left-7' : 'left-1'}`} />
          </button>
        </div>

        {/* Automatic scan schedule */}
        <div className="bg-dark-800 rounded-lg">
          <div className="p-3 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <Clock size={14} className="text-primary-400 shrink-0" />
              <div className="min-w-0">
                <label className="font-medium text-white text-sm">Automatic scan</label>
                <p className="text-xs text-gray-500 mt-0.5">
                  Runs on a schedule. Run Scan stays available either way.
                </p>
              </div>
            </div>
            <button
              onClick={() => setAutoScanEnabled(!autoScanEnabled)}
              aria-label="Toggle automatic scan"
              className={`relative shrink-0 w-12 h-6 rounded-full transition-colors ${autoScanEnabled ? 'bg-primary-500' : 'bg-gray-600'}`}
            >
              <span className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${autoScanEnabled ? 'left-7' : 'left-1'}`} />
            </button>
          </div>

          {autoScanEnabled && (
            <div className="px-3 pb-3 space-y-3 border-t border-white/5 pt-3">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-gray-300 mb-1">Time</label>
                  <input
                    type="time"
                    value={autoScanTime}
                    onChange={(e) => setAutoScanTime(e.target.value)}
                    className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-300 mb-1">Timezone</label>
                  <select
                    value={autoScanTimezone}
                    onChange={(e) => setAutoScanTimezone(e.target.value)}
                    className="w-full bg-dark-700 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-primary-500"
                  >
                    {(TIMEZONE_OPTIONS.includes(autoScanTimezone)
                      ? TIMEZONE_OPTIONS
                      : [autoScanTimezone, ...TIMEZONE_OPTIONS]
                    ).map((tz) => (
                      <option key={tz} value={tz}>{tz}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-300 mb-1.5">Days</label>
                <div className="flex flex-wrap gap-1.5">
                  {DAY_LABELS.map((day) => {
                    const active = autoScanDays.includes(day.value);
                    return (
                      <button
                        key={day.value}
                        onClick={() => toggleScanDay(day.value)}
                        aria-pressed={active}
                        className={`px-2.5 py-1.5 rounded-lg text-xs font-medium transition-colors border ${
                          active
                            ? 'bg-primary-500/20 border-primary-500/50 text-primary-300'
                            : 'bg-dark-700 border-white/10 text-gray-400 hover:text-white'
                        }`}
                      >
                        {day.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {autoScanDays.length === 0 ? (
                <p className="text-xs text-yellow-400 flex items-center gap-1.5">
                  <AlertTriangle size={12} className="shrink-0" />
                  Select at least one day.
                </p>
              ) : (
                <p className="text-xs text-gray-500">
                  Default 16:30 America/New_York is 30 minutes after the US equities
                  close, once the daily bar has settled. NYSE holidays are skipped
                  using Alpaca's market calendar.
                </p>
              )}

              {settings?.next_auto_run_at && (
                <div className="flex items-center gap-1.5 text-xs text-gray-400">
                  <CalendarClock size={12} className="text-primary-400 shrink-0" />
                  <span>
                    Next run {formatMarketTime(settings.next_auto_run_at)}
                    {(() => {
                      const countdown = formatCountdown(settings.next_auto_run_at);
                      return countdown ? <span className="text-gray-600"> · {countdown}</span> : null;
                    })()}
                  </span>
                </div>
              )}
              {settings?.last_auto_run_at && (
                <p className="text-xs text-gray-600">
                  Last automatic run {formatMarketTime(settings.last_auto_run_at)}
                </p>
              )}
              {!enabled && (
                <p className="text-xs text-yellow-400 flex items-center gap-1.5">
                  <AlertTriangle size={12} className="shrink-0" />
                  Scanner is disabled, so nothing will run on this schedule.
                </p>
              )}
            </div>
          )}
        </div>

        <div className="p-3 bg-dark-800 rounded-lg flex items-center justify-between gap-3">
          <div className="min-w-0 flex-1">
            <label className="font-medium text-white text-sm">Use Unusual Whales</label>
            <p className="text-xs text-gray-500 mt-0.5">Flow, OI, GEX, dark pool & smart money</p>
          </div>
          <button
            onClick={() => setUseUw(!useUw)}
            className={`relative shrink-0 w-12 h-6 rounded-full transition-colors ${useUw ? 'bg-primary-500' : 'bg-gray-600'}`}
          >
            <span className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${useUw ? 'left-7' : 'left-1'}`} />
          </button>
        </div>

        <div className="p-3 bg-dark-800 rounded-lg flex items-center justify-between gap-3">
          <div className="min-w-0 flex-1">
            <label className="font-medium text-white text-sm">Require above 200-day avg</label>
            <p className="text-xs text-gray-500 mt-0.5">Optional uptrend gate (off by default)</p>
          </div>
          <button
            onClick={() => setRequireSma200(!requireSma200)}
            className={`relative shrink-0 w-12 h-6 rounded-full transition-colors ${requireSma200 ? 'bg-primary-500' : 'bg-gray-600'}`}
          >
            <span className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-transform ${requireSma200 ? 'left-7' : 'left-1'}`} />
          </button>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleSave}
            disabled={saving || scheduleInvalid}
            title={scheduleInvalid ? 'Select at least one day for the automatic scan' : undefined}
            className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg font-medium bg-dark-700 hover:bg-dark-600 text-white transition-colors disabled:opacity-50"
          >
            {saving ? <RefreshCw size={16} className="animate-spin" /> : <Save size={16} />}
            Save
          </button>
          <button
            onClick={handleRun}
            disabled={isRunning || !canRun}
            className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg font-medium bg-primary-500 hover:bg-primary-600 text-white transition-colors disabled:bg-gray-700 disabled:text-gray-400 disabled:cursor-not-allowed"
          >
            {isRunning ? <RefreshCw size={16} className="animate-spin" /> : <Play size={16} />}
            {isRunning ? 'Scanning...' : 'Run Scan'}
          </button>
        </div>

        {/* Run status */}
        {settings?.last_run_status && settings.last_run_status !== 'idle' && (
          <div className="text-xs text-gray-400 flex items-start gap-2">
            {settings.last_run_status === 'success' && <CheckCircle size={14} className="text-green-400 mt-0.5" />}
            {settings.last_run_status === 'error' && <XCircle size={14} className="text-red-400 mt-0.5" />}
            {settings.last_run_status === 'running' && <RefreshCw size={14} className="text-primary-400 mt-0.5 animate-spin" />}
            <span className="flex-1">
              {settings.last_run_message}
              {settings.last_run_at && (
                <span className="text-gray-600"> · {formatMarketTime(settings.last_run_at)}</span>
              )}
            </span>
            {canReset && (
              <button
                onClick={handleReset}
                className="text-gray-400 hover:text-white underline whitespace-nowrap"
                title="Clear a stuck or failed scan status so you can run again"
              >
                Reset
              </button>
            )}
          </div>
        )}
      </div>

      {/* Market context / regime banner */}
      {settings?.market_context && settings.market_context.regime && (
        (() => {
          const mc = settings.market_context!;
          const regime = REGIME_STYLES[mc.regime || 'neutral'] || REGIME_STYLES.neutral;
          const fg = Math.round(mc.fear_greed ?? 50);
          return (
            <div className={`mt-6 p-3 rounded-lg border ${regime.cls}`}>
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-center gap-2 min-w-0">
                  <Gauge size={16} className="shrink-0" />
                  <span className="text-sm font-semibold">Market Regime: {regime.label}</span>
                </div>
                <span className="text-xs flex flex-wrap items-center gap-1">
                  <Flame size={12} className="shrink-0" /> Fear/Greed: <span className="font-semibold">{fg}</span>
                  <span className="opacity-70">({fearGreedLabel(fg)})</span>
                </span>
              </div>
              <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] opacity-80">
                {mc.regime_scale != null && <span>Score x{mc.regime_scale.toFixed(2)}</span>}
                {mc.spy_trend != null && <span>SPY trend {(mc.spy_trend * 100).toFixed(0)}</span>}
                {mc.qqq_trend != null && <span>QQQ trend {(mc.qqq_trend * 100).toFixed(0)}</span>}
                {mc.breadth != null && <span>Breadth {(mc.breadth * 100).toFixed(0)}%</span>}
                {mc.vix != null && <span>VIX {mc.vix.toFixed(1)}</span>}
                {mc.market_tide != null && <span>Tide {(mc.market_tide * 100).toFixed(0)}</span>}
              </div>
            </div>
          );
        })()
      )}

      {/* Results */}
      {results.length > 0 && (
        <div className="mt-6 min-w-0">
          <h3 className="text-sm font-semibold text-white mb-2">Latest Results</h3>

          <p className="text-xs text-gray-500 mb-2">
            Select a row to see how the score was built.
          </p>

          {/* Mobile: card layout */}
          <div className="md:hidden space-y-3">
            {results.map((r) => (
              <BreakoutResultCard
                key={r.symbol}
                result={r}
                weights={effectiveWeights}
                expanded={expanded.has(r.symbol)}
                onToggle={() => toggleExpanded(r.symbol)}
              />
            ))}
          </div>

          {/* Desktop: table layout */}
          <div className="hidden md:block overflow-x-auto rounded-xl border border-white/5">
            <table className="w-full text-xs min-w-[760px]">
              <thead>
                <tr className="text-gray-500 border-b border-white/10">
                  <th className="w-6 py-2 pl-3" />
                  <th className="text-left py-2 px-3">#</th>
                  <th className="text-left py-2 px-3">Symbol</th>
                  <th className="text-right py-2 px-3">Score</th>
                  <th className="text-left py-2 px-3">Setup</th>
                  <th className="text-right py-2 px-3">Price</th>
                  <th className="text-right py-2 px-3">Pivot</th>
                  <th className="text-right py-2 px-3" title="Percent still to travel to reach the pivot">
                    To Pivot
                  </th>
                  <th className="text-right py-2 px-3">IVR</th>
                  <th className="text-right py-2 px-3">CSP Strike</th>
                  <th className="text-center py-2 px-3">Signals</th>
                </tr>
              </thead>
              <tbody>
                {results.map((r) => {
                  const isOpen = expanded.has(r.symbol);
                  return (
                    <React.Fragment key={r.symbol}>
                      <tr
                        onClick={() => toggleExpanded(r.symbol)}
                        className="border-b border-white/5 hover:bg-white/5 cursor-pointer"
                      >
                        <td className="py-2 pl-3 text-gray-500">
                          {isOpen ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                        </td>
                        <td className="py-2 px-3 text-gray-500">{r.rank}</td>
                        <td className="py-2 px-3 font-semibold text-white">{r.symbol}</td>
                        <td className="py-2 px-3 text-right">
                          <span className={`font-medium ${scoreColorClass(r.score)}`}>
                            {r.score.toFixed(0)}
                          </span>
                        </td>
                        <td className="py-2 px-3 text-gray-300">{SETUP_LABELS[r.setup_type || ''] || r.setup_type}</td>
                        <td className="py-2 px-3 text-right text-gray-300">{formatMoney(r.current_price)}</td>
                        <td className="py-2 px-3 text-right text-gray-300">{formatMoney(r.pivot_price)}</td>
                        <td className="py-2 px-3 text-right text-gray-300 tabular-nums">{formatPct(r.pct_to_pivot, 2)}</td>
                        <td className="py-2 px-3 text-right text-gray-300">{r.iv_rank != null ? r.iv_rank.toFixed(0) : '—'}</td>
                        <td className="py-2 px-3 text-right text-primary-300">{r.suggested_put_strike != null ? `$${r.suggested_put_strike}` : '—'}</td>
                        <td className="py-2 px-3">
                          <BreakoutResultSignalsCompact result={r} />
                        </td>
                      </tr>
                      {isOpen && (
                        <tr className="border-b border-white/5 bg-dark-900/40">
                          <td colSpan={11} className="p-3">
                            <CandidateDetail result={r} weights={effectiveWeights} />
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className="hidden md:flex flex-wrap gap-x-4 gap-y-1 mt-2 text-[10px] text-gray-500">
            <span className="flex items-center gap-1"><Zap size={10} className="text-yellow-400" /> Bullish flow</span>
            <span className="flex items-center gap-1"><TrendingUp size={10} className="text-green-400" /> Short gamma</span>
            <span className="flex items-center gap-1"><Eye size={10} className="text-blue-400" /> Dark pool</span>
            <span className="flex items-center gap-1"><Users size={10} className="text-purple-400" /> Smart money</span>
            <span className="flex items-center gap-1"><AlertTriangle size={10} className="text-red-400" /> Earnings soon</span>
          </div>
        </div>
      )}
    </div>
  );
}

export default BreakoutScannerCard;
