/**
 * ChipSelector component for selecting filters and trade ideas
 * Uses app's purple gradient color scheme
 * - Portions generated by AI
 */

import { Plus, Pencil, X } from 'lucide-react';

interface ChipProps {
  label: string;
  selected: boolean;
  isSystem: boolean;
  isDefault?: boolean;
  onClick: () => void;
  onEdit?: () => void;
  onDelete?: () => void;
  disabled?: boolean;
}

export function Chip({
  label,
  selected,
  isSystem,
  isDefault,
  onClick,
  onEdit,
  onDelete,
  disabled,
}: ChipProps) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`
        group inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium
        transition-all duration-200 whitespace-nowrap
        ${selected
          ? 'bg-gradient-to-r from-primary-500 to-secondary-500 text-white shadow-lg shadow-primary-500/25'
          : isSystem
            ? 'bg-dark-800 text-gray-300 hover:bg-dark-700 hover:text-white border border-white/5'
            : 'bg-dark-800/50 text-gray-400 hover:bg-dark-700 hover:text-gray-200 border border-dashed border-white/20 hover:border-primary-500/50'
        }
        ${disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
        snap-start flex-shrink-0
      `}
      title={isDefault ? `${label} (Default)` : label}
    >
      {/* Default star indicator */}
      {isDefault && (
        <span className={`text-xs ${selected ? 'text-yellow-300' : 'text-yellow-500'}`}>★</span>
      )}
      
      {/* Label with truncation */}
      <span className="truncate max-w-[140px]">{label}</span>
      
      {/* Edit/Delete actions for user items */}
      {!isSystem && (onEdit || onDelete) && (
        <span className="flex items-center gap-0.5 ml-0.5">
          {onEdit && (
            <span
              onClick={(e) => {
                e.stopPropagation();
                onEdit();
              }}
              className={`p-1 rounded transition-colors ${
                selected 
                  ? 'hover:bg-white/20 text-white/80 hover:text-white' 
                  : 'hover:bg-primary-500/20 text-gray-500 hover:text-primary-400'
              }`}
              title="Edit"
            >
              <Pencil size={12} />
            </span>
          )}
          {onDelete && (
            <span
              onClick={(e) => {
                e.stopPropagation();
                onDelete();
              }}
              className={`p-1 rounded transition-colors ${
                selected
                  ? 'hover:bg-red-500/30 text-white/80 hover:text-red-300'
                  : 'hover:bg-red-500/20 text-gray-500 hover:text-red-400'
              }`}
              title="Delete"
            >
              <X size={12} />
            </span>
          )}
        </span>
      )}
    </button>
  );
}

interface ChipSelectorProps<T extends { id: string; name: string; is_system: boolean; is_default: boolean }> {
  label: string;
  items: T[];
  selectedId: string | null;
  onSelect: (item: T) => void;
  onCreateNew?: () => void;
  onEdit?: (item: T) => void;
  onDelete?: (item: T) => void;
  loading?: boolean;
  className?: string;
}

export function ChipSelector<T extends { id: string; name: string; is_system: boolean; is_default: boolean }>({
  label,
  items,
  selectedId,
  onSelect,
  onCreateNew,
  onEdit,
  onDelete,
  loading,
  className = '',
}: ChipSelectorProps<T>) {
  // Separate system and user items
  const systemItems = items.filter((item) => item.is_system);
  const userItems = items.filter((item) => !item.is_system);

  return (
    <div className={`flex flex-col gap-2 ${className}`}>
      {/* Label */}
      <span className="text-xs font-semibold text-primary-400 uppercase tracking-wider">
        {label}
      </span>
      
      {/* Chips container - horizontal scroll on mobile */}
      <div className="flex flex-nowrap sm:flex-wrap gap-2 items-center overflow-x-auto pb-1 -mx-1 px-1 snap-x snap-mandatory scroll-smooth">
        {loading ? (
          <div className="flex items-center gap-2 text-gray-500 py-2">
            <svg className="animate-spin h-4 w-4 text-primary-500" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            <span className="text-sm">Loading...</span>
          </div>
        ) : (
          <>
            {/* System items */}
            {systemItems.map((item) => (
              <Chip
                key={item.id}
                label={item.name}
                selected={selectedId === item.id}
                isSystem={true}
                isDefault={item.is_default}
                onClick={() => onSelect(item)}
              />
            ))}
            
            {/* User items */}
            {userItems.map((item) => (
              <Chip
                key={item.id}
                label={item.name}
                selected={selectedId === item.id}
                isSystem={false}
                isDefault={false}
                onClick={() => onSelect(item)}
                onEdit={onEdit ? () => onEdit(item) : undefined}
                onDelete={onDelete ? () => onDelete(item) : undefined}
              />
            ))}
            
            {/* Create new button */}
            {onCreateNew && (
              <button
                onClick={onCreateNew}
                className="
                  inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium
                  bg-transparent border border-dashed border-primary-500/50
                  text-primary-400 hover:text-primary-300
                  hover:bg-primary-500/10 hover:border-primary-400
                  transition-all duration-200
                  snap-start flex-shrink-0
                "
              >
                <Plus size={16} />
                <span>New</span>
              </button>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default ChipSelector;
