/**
 * PWA Install Prompt Component
 * Shows a banner prompting users to install the app
 * - Portions generated by AI
 */

import { useState, useEffect } from 'react';
import { Download, X, Share } from 'lucide-react';

// Extended window interface for beforeinstallprompt event
interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>;
}

// Detect iOS Safari
function isIOSSafari(): boolean {
  const ua = navigator.userAgent;
  const isIOS = /iPad|iPhone|iPod/.test(ua);
  const isWebkit = /WebKit/.test(ua);
  const isChrome = /CriOS/.test(ua);
  const isFirefox = /FxiOS/.test(ua);
  // iOS Safari is WebKit-based but not Chrome or Firefox
  return isIOS && isWebkit && !isChrome && !isFirefox;
}

// Check if already running as installed PWA
function isStandalone(): boolean {
  return window.matchMedia('(display-mode: standalone)').matches ||
         (window.navigator as { standalone?: boolean }).standalone === true;
}

const DISMISS_KEY = 'pwa-install-dismissed';
const DISMISS_DURATION = 7 * 24 * 60 * 60 * 1000; // 7 days

export function InstallPrompt() {
  const [deferredPrompt, setDeferredPrompt] = useState<BeforeInstallPromptEvent | null>(null);
  const [showBanner, setShowBanner] = useState(false);
  const [showIOSInstructions, setShowIOSInstructions] = useState(false);

  useEffect(() => {
    // Don't show if already installed
    if (isStandalone()) return;

    // Check if user dismissed recently
    const dismissedAt = localStorage.getItem(DISMISS_KEY);
    if (dismissedAt) {
      const dismissTime = parseInt(dismissedAt, 10);
      if (Date.now() - dismissTime < DISMISS_DURATION) {
        return; // Still within dismiss period
      }
    }

    // iOS Safari: Show manual instructions
    if (isIOSSafari()) {
      setShowIOSInstructions(true);
      setShowBanner(true);
      return;
    }

    // Chrome/Edge/Android: Listen for beforeinstallprompt
    const handleBeforeInstall = (e: Event) => {
      e.preventDefault();
      setDeferredPrompt(e as BeforeInstallPromptEvent);
      setShowBanner(true);
    };

    window.addEventListener('beforeinstallprompt', handleBeforeInstall);

    // Also listen for app installed event to hide banner
    const handleAppInstalled = () => {
      setShowBanner(false);
      setDeferredPrompt(null);
    };

    window.addEventListener('appinstalled', handleAppInstalled);

    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstall);
      window.removeEventListener('appinstalled', handleAppInstalled);
    };
  }, []);

  const handleInstall = async () => {
    if (!deferredPrompt) return;

    await deferredPrompt.prompt();
    const result = await deferredPrompt.userChoice;
    
    if (result.outcome === 'accepted') {
      setShowBanner(false);
    }
    setDeferredPrompt(null);
  };

  const handleDismiss = () => {
    localStorage.setItem(DISMISS_KEY, Date.now().toString());
    setShowBanner(false);
  };

  if (!showBanner) return null;

  return (
    <div className="fixed bottom-0 left-0 right-0 z-50 p-3 sm:p-4 bg-dark-900/95 backdrop-blur-sm border-t border-white/10 shadow-2xl">
      <div className="max-w-2xl mx-auto">
        {showIOSInstructions ? (
          // iOS Safari instructions
          <div className="flex items-start gap-3 sm:gap-4">
            <div className="flex-shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-xl bg-gradient-to-br from-primary-500 to-purple-600 flex items-center justify-center">
              <span className="text-white text-xl sm:text-2xl font-bold">P</span>
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-white font-medium text-sm sm:text-base mb-1">
                Install Put Options Screener
              </p>
              <p className="text-gray-400 text-xs sm:text-sm flex items-center gap-1.5 flex-wrap">
                Tap <Share size={14} className="inline text-primary-400" /> then "Add to Home Screen"
              </p>
            </div>
            <button
              onClick={handleDismiss}
              className="flex-shrink-0 p-2 text-gray-500 hover:text-white transition-colors"
              aria-label="Dismiss"
            >
              <X size={20} />
            </button>
          </div>
        ) : (
          // Chrome/Edge/Android install prompt
          <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4">
            <div className="flex items-center gap-3 flex-1 min-w-0">
              <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-gradient-to-br from-primary-500 to-purple-600 flex items-center justify-center">
                <span className="text-white text-xl font-bold">P</span>
              </div>
              <div className="min-w-0">
                <p className="text-white font-medium text-sm sm:text-base truncate">
                  Install Put Options Screener
                </p>
                <p className="text-gray-400 text-xs sm:text-sm">
                  Quick access from your home screen
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2 sm:gap-3">
              <button
                onClick={handleDismiss}
                className="flex-1 sm:flex-none px-4 py-2.5 text-sm text-gray-400 hover:text-white transition-colors min-h-[44px]"
              >
                Not now
              </button>
              <button
                onClick={handleInstall}
                className="flex-1 sm:flex-none px-5 py-2.5 bg-primary-500 hover:bg-primary-600 text-white font-medium rounded-lg transition-colors flex items-center justify-center gap-2 min-h-[44px]"
              >
                <Download size={18} />
                Install
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
