/**
 * News section component
 * - Portions generated by AI
 */

import { useQuery } from '@tanstack/react-query';
import { ExternalLink } from 'lucide-react';
import apiClient from '@/api/client';

interface NewsSectionProps {
  symbol: string;
}

export function NewsSection({ symbol }: NewsSectionProps) {
  const { data, isLoading, error } = useQuery({
    queryKey: ['news', symbol],
    queryFn: () => apiClient.getNews(symbol, 10, 7),
    enabled: !!symbol && symbol !== 'Summary',
    staleTime: 1000 * 60 * 5, // 5 minutes
  });

  if (!symbol || symbol === 'Summary') {
    return null;
  }

  return (
    <div className="card mt-6">
      <h4 className="text-xs font-semibold text-primary-400 uppercase tracking-wider mb-4">
        Latest News (Last 7 Days)
      </h4>
      
      {isLoading && (
        <div className="text-gray-400 text-sm">Loading news...</div>
      )}
      
      {error && (
        <div className="text-gray-400 text-sm">Failed to load news</div>
      )}
      
      {data && data.news && data.news.length > 0 ? (
        <div className="space-y-3">
          {data.news.map((item, index) => (
            <div 
              key={index} 
              className="py-2 border-b border-white/5 last:border-0"
            >
              <a
                href={item.url}
                target="_blank"
                rel="noopener noreferrer"
                className="group flex items-start gap-2 text-gray-300 hover:text-primary-400 transition-colors"
              >
                <span className="flex-1">
                  {item.date_display && (
                    <span className="text-primary-400 font-semibold text-sm mr-2">
                      {item.date_display}
                    </span>
                  )}
                  <span className="text-sm">— {item.title}</span>
                </span>
                <ExternalLink size={14} className="mt-1 opacity-0 group-hover:opacity-100 transition-opacity" />
              </a>
            </div>
          ))}
        </div>
      ) : (
        !isLoading && (
          <div className="text-gray-500 text-sm">
            No recent news in the last 7 days
          </div>
        )
      )}
    </div>
  );
}
