/**
 * Sidebar component with screening settings
 * - Portions generated by AI
 */

import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, Save, Minus, Plus, Loader2 } from 'lucide-react';
import { useAppStore } from '@/stores/useAppStore';
import { useSaveSettings } from '@/hooks/useAuthSync';

interface NumberInputProps {
  label: string;
  value: number;
  onChange: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
}

function NumberInput({ label, value, onChange, min = 0, max = 999, step = 1 }: NumberInputProps) {
  // Local state allows typing any value; validation happens on blur
  const [localValue, setLocalValue] = useState(value.toString());
  const [isFocused, setIsFocused] = useState(false);

  // Sync local value when external value changes (and not focused)
  React.useEffect(() => {
    if (!isFocused) {
      setLocalValue(value.toString());
    }
  }, [value, isFocused]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    // Allow any input while typing
    setLocalValue(e.target.value);
  };

  const handleBlur = () => {
    setIsFocused(false);
    // Validate and apply on blur
    const newValue = parseFloat(localValue);
    if (!isNaN(newValue)) {
      // Clamp to min/max range
      const clampedValue = Math.min(max, Math.max(min, newValue));
      onChange(clampedValue);
      setLocalValue(clampedValue.toString());
    } else {
      // Reset to current value if invalid
      setLocalValue(value.toString());
    }
  };

  const handleFocus = () => {
    setIsFocused(true);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.currentTarget.blur(); // Trigger blur to validate
    }
  };

  const increment = () => {
    const newValue = Math.min(max, value + step);
    onChange(newValue);
    setLocalValue(newValue.toString());
  };

  const decrement = () => {
    const newValue = Math.max(min, value - step);
    onChange(newValue);
    setLocalValue(newValue.toString());
  };

  return (
    <div className="flex flex-col gap-1">
      <label className="text-xs text-gray-400">{label}</label>
      <div className="flex items-center gap-1">
        <button
          onClick={decrement}
          className="p-1 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          <Minus size={14} />
        </button>
        <input
          type="number"
          value={localValue}
          onChange={handleChange}
          onBlur={handleBlur}
          onFocus={handleFocus}
          onKeyDown={handleKeyDown}
          min={min}
          max={max}
          step={step}
          className="w-16 bg-dark-800 border border-white/10 rounded px-2 py-1 text-center text-sm focus:border-primary-500"
        />
        <button
          onClick={increment}
          className="p-1 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          <Plus size={14} />
        </button>
      </div>
    </div>
  );
}

export function Sidebar() {
  const { settings, setSettings, sidebarOpen, toggleSidebar, setSelectedSymbol } = useAppStore();
  const { saveToBackend } = useSaveSettings();
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  
  // Local state for textarea - allows free typing without constant reformatting
  const [symbolsText, setSymbolsText] = useState(settings.symbols.join(', '));

  // Parse symbols from text and update global state
  const parseAndUpdateSymbols = (text: string) => {
    const newSymbols = text
      .split(',')
      .map((s) => s.trim().toUpperCase())
      .filter((s) => s.length > 0);
    
    // Only update if we have valid symbols
    if (newSymbols.length > 0) {
      setSettings({ symbols: newSymbols });
      
      // Update selected symbol if current one is no longer in list
      const currentSelected = useAppStore.getState().selectedSymbol;
      if (!newSymbols.includes(currentSelected)) {
        setSelectedSymbol(newSymbols[0]);
      }
    }
  };

  // Handle textarea changes - update local state immediately, parse on every change
  const handleSymbolsChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const text = e.target.value;
    setSymbolsText(text);
    parseAndUpdateSymbols(text);
  };

  // Save to backend (for persistence across sessions)
  const handleSave = async () => {
    // Ensure latest symbols are parsed before saving
    parseAndUpdateSymbols(symbolsText);
    
    setSaveStatus('saving');

    // Save current settings to backend
    const success = await saveToBackend();
    
    if (success) {
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    } else {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };

  if (!sidebarOpen) {
    return (
      <button
        onClick={toggleSidebar}
        className="fixed left-0 top-1/2 -translate-y-1/2 z-50 bg-dark-800 p-2.5 rounded-r-lg border border-l-0 border-white/10 hover:bg-dark-700 transition-colors text-gray-400 hover:text-white shadow-lg"
        title="Open sidebar"
      >
        <ChevronRight size={20} />
      </button>
    );
  }

  return (
    <aside className="w-72 bg-dark-900 border-r border-white/5 p-4 flex flex-col gap-4 overflow-y-auto relative">
      {/* Collapse button - always visible */}
      <button
        onClick={toggleSidebar}
        className="absolute top-4 right-2 p-1.5 hover:bg-dark-800 rounded-lg transition-colors text-gray-400 hover:text-white"
        title="Collapse sidebar"
      >
        <ChevronLeft size={18} />
      </button>

      {/* Expiration DTE */}
      <div>
        <p className="text-xs font-semibold text-primary-400 uppercase tracking-wider mb-2">
          Expiration (DTE)
        </p>
        <div className="flex gap-4">
          <NumberInput
            label="Min"
            value={settings.min_dte}
            onChange={(v) => setSettings({ min_dte: v })}
            min={0}
            max={364}
          />
          <NumberInput
            label="Max"
            value={settings.max_dte}
            onChange={(v) => setSettings({ max_dte: v })}
            min={1}
            max={365}
          />
        </div>
      </div>

      {/* Liquidity */}
      <div>
        <p className="text-xs font-semibold text-primary-400 uppercase tracking-wider mb-2">
          Liquidity
        </p>
        <div className="flex gap-4">
          <NumberInput
            label="Min Vol"
            value={settings.min_volume}
            onChange={(v) => setSettings({ min_volume: v })}
            min={0}
            max={10000}
          />
          <NumberInput
            label="Min OI"
            value={settings.min_open_interest}
            onChange={(v) => setSettings({ min_open_interest: v })}
            min={0}
            max={10000}
          />
        </div>
      </div>

      {/* Screening */}
      <div>
        <p className="text-xs font-semibold text-primary-400 uppercase tracking-wider mb-2">
          Screening
        </p>
        <div className="flex gap-4">
          <NumberInput
            label="Min Ann Ret(%)"
            value={settings.min_annualized_return}
            onChange={(v) => setSettings({ min_annualized_return: v })}
            min={0}
            max={500}
            step={5}
          />
          <NumberInput
            label="Max Prob(%)"
            value={settings.max_assignment_probability}
            onChange={(v) => setSettings({ max_assignment_probability: v })}
            min={5}
            max={50}
          />
        </div>
      </div>

      {/* Watchlist */}
      <div className="flex-1">
        <p className="text-xs font-semibold text-primary-400 uppercase tracking-wider mb-2">
          Watchlist
        </p>
        <textarea
          value={symbolsText}
          onChange={handleSymbolsChange}
          placeholder="AAPL, TSLA, MSFT..."
          className="w-full h-40 bg-dark-800 border border-white/10 rounded-lg p-3 text-sm resize-none focus:border-primary-500"
        />
        <p className="text-xs text-gray-500 mt-1">
          Changes apply immediately. Click Save to persist.
        </p>
      </div>

      {/* Save button */}
      <button
        onClick={handleSave}
        disabled={saveStatus === 'saving'}
        className={`w-full flex items-center justify-center gap-2 py-2.5 px-4 rounded-lg font-medium transition-colors
          ${saveStatus === 'error' 
            ? 'bg-red-500/20 text-red-400 border border-red-500/30' 
            : 'btn-primary'
          }
          disabled:opacity-50 disabled:cursor-not-allowed
        `}
      >
        {saveStatus === 'saving' ? (
          <Loader2 size={16} className="animate-spin" />
        ) : (
          <Save size={16} />
        )}
        {saveStatus === 'saved' ? 'Saved!' : saveStatus === 'error' ? 'Error saving' : 'Save'}
      </button>
    </aside>
  );
}
