/**
 * Guide drawer — overlay on the right so results stay full width
 * - Portions generated by AI
 */

import { useEffect, type ReactNode } from 'react';
import { BookOpen } from 'lucide-react';
import { useAppStore } from '@/stores/useAppStore';

function GuideTerm({ term, children }: { term: string; children: ReactNode }) {
  return (
    <div>
      <dt className="text-white font-medium">{term}</dt>
      <dd className="text-gray-400 mt-0.5 leading-relaxed">{children}</dd>
    </div>
  );
}

export function Sidebar() {
  const { sidebarOpen, toggleSidebar } = useAppStore();

  useEffect(() => {
    if (!sidebarOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') toggleSidebar();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [sidebarOpen, toggleSidebar]);

  if (!sidebarOpen) return null;

  return (
    <>
      <div
        className="absolute inset-0 bg-black/60 z-40"
        onClick={toggleSidebar}
        aria-hidden="true"
      />
      <aside
        className="absolute top-0 right-0 bottom-0 w-[min(26rem,92vw)] bg-dark-900 border-l border-white/5 p-5 flex flex-col gap-4 overflow-y-auto z-50 shadow-2xl shadow-black/40"
        role="dialog"
        aria-label="How to use PutYield"
      >
        <div className="bg-dark-800/50 rounded-xl p-4 border border-white/5">
          <div className="flex items-center gap-2 mb-3">
            <BookOpen size={18} className="text-primary-400" />
            <p className="text-sm font-semibold text-primary-400 uppercase tracking-wider">
              Guide
            </p>
          </div>
          <ol className="space-y-2.5 text-sm text-gray-300 list-decimal list-inside">
            <li>
              Pick admin curated <span className="text-white">Trade Ideas</span> or build watchlist of stocks you want to own.
            </li>
            <li>
              Pick <span className="text-white">Assignment risk</span> — DTE and chance of buying the stock.
            </li>
            <li>
              <span className="text-white">Screen</span> for cash-secured puts ranked by income.
            </li>
            <li>
              Sell the put. Keep the premium, or own the stock cheaper.
            </li>
          </ol>
        </div>

        <div className="bg-dark-800/50 rounded-xl p-4 border border-white/5">
          <p className="text-sm font-semibold text-primary-400 uppercase tracking-wider mb-3">
            Cash-secured puts
          </p>
          <div className="space-y-3 text-sm text-gray-300 leading-relaxed">
            <p>
              A cash-secured put (CSP) is a short put with cash set aside to buy 100 shares
              at the strike if you are assigned. One contract controls 100 shares, so cash
              required is roughly <span className="text-white">strike × 100</span>.
            </p>
            <p>
              If the stock stays above the strike through expiry, the put expires and you
              keep the premium. If it finishes below, you buy the shares. Your effective
              cost is <span className="text-white">strike − premium</span> — a discount to
              the strike, which is the point of the strategy.
            </p>
            <p>
              Screen names you actually want to own. Assignment is not a failure; it is
              how you get paid to wait, then buy at a price you already accepted.
            </p>
          </div>
        </div>

        <div className="bg-dark-800/50 rounded-xl p-4 border border-white/5">
          <p className="text-sm font-semibold text-primary-400 uppercase tracking-wider mb-3">
            Results columns
          </p>
          <dl className="space-y-3 text-sm">
            <GuideTerm term="Symbol">
              Ticker. The robot icon opens AI analysis for that name.
            </GuideTerm>
            <GuideTerm term="Price">
              Last stock price and today's change. Use it to see how far the strike sits
              below the market.
            </GuideTerm>
            <GuideTerm term="Strike">
              The price you agree to pay for the shares if assigned. Lower strikes are
              safer but pay less premium.
            </GuideTerm>
            <GuideTerm term="Premium">
              Income collected per share for selling the put. A $6.80 premium is $680 per
              contract before fees.
            </GuideTerm>
            <GuideTerm term="Expiry">
              When the option expires. An amber <span className="text-amber-400 font-semibold">E</span> means
              earnings land first; a blue <span className="text-blue-400 font-semibold">D</span> means an
              ex-dividend. Both can reprice the stock before you are done.
            </GuideTerm>
            <GuideTerm term="Discount">
              How far below today's price your cost basis sits if assigned:
              (price − strike − premium) ÷ price. Higher means a deeper discount to own the stock.
            </GuideTerm>
            <GuideTerm term="Ann. return">
              Premium ÷ strike, annualized over days to expiry. This is how PutYield ranks
              income — not a guaranteed yield.
            </GuideTerm>
            <GuideTerm term="Daily Decay">
              Estimated premium that time-value burns off each day (theta). Higher decay
              pays you faster if the stock stays above the strike.
            </GuideTerm>
            <GuideTerm term="Assign Risk">
              Rough chance of finishing in-the-money, from put delta. Your Assignment risk
              chip caps this. Higher risk usually means more premium.
            </GuideTerm>
            <GuideTerm term="DTE">
              Calendar days left until expiry. Shorter DTE compounds annualized return;
              longer DTE gives the trade more room.
            </GuideTerm>
            <GuideTerm term="SMA 20 / 50 / 200">
              Simple moving averages. Green means price is above that average (uptrend);
              red means below. Puts under a rising trend often have more cushion.
            </GuideTerm>
            <GuideTerm term="EMA 9 / 21">
              Exponential moving averages that react faster than SMAs. Price above both
              favors short-term strength; a cross under can warn of a dip toward your strike.
            </GuideTerm>
            <GuideTerm term="RSI">
              14-day relative strength. Near 70 can be stretched to the upside; near 30 can
              be washed out. Context for whether a dip to your strike is likely.
            </GuideTerm>
            <GuideTerm term="Vol / OI">
              Today's volume and open interest. Thin contracts are harder to enter or exit
              at a fair price.
            </GuideTerm>
            <GuideTerm term="IV">
              Implied volatility. High IV inflates premium — and the chance of a sharp move
              against the strike.
            </GuideTerm>
          </dl>
        </div>
      </aside>
    </>
  );
}
