/**
 * StockChartPanel component - Side panel with a TradingView-style candlestick
 * chart (3M/6M/1Y/5Y ranges, SMA/EMA overlays, volume).
 * - Portions generated by AI
 */

import { useEffect, useState } from 'react';
import { X, RefreshCw, CandlestickChart as CandlestickChartIcon, AlertTriangle } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import apiClient from '@/api/client';
import type { OverlayKey } from '@/types';
import { CandlestickChart, OVERLAY_CONFIG, type ChartRange } from './CandlestickChart';

const RANGES: ChartRange[] = ['1M', '3M', '6M', '1Y', '3Y', '5Y'];
const ALL_OVERLAYS = Object.keys(OVERLAY_CONFIG) as OverlayKey[];
// EMAs start hidden to keep the default view uncluttered; users opt in via the legend
const DEFAULT_OVERLAYS: OverlayKey[] = ['sma_20', 'sma_50', 'sma_200'];

interface StockChartPanelProps {
  symbol: string;
  isOpen: boolean;
  onClose: () => void;
}

export default function StockChartPanel({ symbol, isOpen, onClose }: StockChartPanelProps) {
  const [range, setRange] = useState<ChartRange>('6M');
  const [visibleOverlays, setVisibleOverlays] = useState<Set<OverlayKey>>(new Set(DEFAULT_OVERLAYS));
  const [showVolume, setShowVolume] = useState(true);
  const [showVolumeProfile, setShowVolumeProfile] = useState(true);
  const [showSupportResistance, setShowSupportResistance] = useState(false);

  // Close on Escape (full-screen panel has no backdrop to click)
  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [isOpen, onClose]);

  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ['candles', symbol],
    queryFn: () => apiClient.getCandles(symbol),
    enabled: isOpen && !!symbol,
    staleTime: 30 * 60 * 1000,
  });

  if (!isOpen) return null;

  const lastCandle = data?.candles[data.candles.length - 1];
  const prevCandle = data && data.candles.length > 1 ? data.candles[data.candles.length - 2] : undefined;
  const changePercent =
    lastCandle && prevCandle ? ((lastCandle.close - prevCandle.close) * 100) / prevCandle.close : undefined;

  const toggleOverlay = (key: OverlayKey) => {
    setVisibleOverlays((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  return (
    <>
      {/* Panel (full-screen on every breakpoint) */}
      <div className="fixed inset-0 bg-dark-900 z-50 flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-2.5 border-b border-white/10 bg-dark-800">
          <div className="flex items-baseline gap-3">
            <CandlestickChartIcon size={20} className="text-primary-400 self-center" />
            <h2 className="text-base font-bold text-white">{symbol}</h2>
            {lastCandle && (
              <p className="text-sm text-gray-400">
                ${lastCandle.close.toFixed(2)}{' '}
                {changePercent !== undefined && (
                  <span className={changePercent >= 0 ? 'text-green-400' : 'text-red-400'}>
                    ({changePercent >= 0 ? '+' : ''}
                    {changePercent.toFixed(1)}%)
                  </span>
                )}
              </p>
            )}
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-lg transition-colors">
            <X size={18} className="text-gray-400" />
          </button>
        </div>

        {/* Toolbar: range tabs + overlay toggles in one wrapping row */}
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1.5 px-4 py-2">
          <div className="flex items-center gap-1">
            {RANGES.map((r) => (
              <button
                key={r}
                onClick={() => setRange(r)}
                className={`px-2.5 py-1 rounded-full text-sm font-medium transition-colors ${
                  range === r
                    ? 'bg-primary-500/20 text-primary-400'
                    : 'text-gray-400 hover:bg-white/10'
                }`}
              >
                {r}
              </button>
            ))}
          </div>
          <span className="hidden sm:block w-px h-4 bg-white/10" />
          {ALL_OVERLAYS.map((key) => (
            <button
              key={key}
              onClick={() => toggleOverlay(key)}
              className={`flex items-center gap-1.5 px-2 py-0.5 rounded text-xs text-gray-300 hover:bg-white/10 transition-colors ${
                visibleOverlays.has(key) ? '' : 'opacity-40'
              }`}
              title={`Toggle ${OVERLAY_CONFIG[key].label}`}
            >
              <span
                className="w-2 h-2 rounded-full"
                style={{ backgroundColor: OVERLAY_CONFIG[key].color }}
              />
              {OVERLAY_CONFIG[key].label}
            </button>
          ))}
          <button
            onClick={() => setShowVolume((v) => !v)}
            className={`px-2 py-0.5 rounded text-xs text-gray-300 hover:bg-white/10 transition-colors ${
              showVolume ? '' : 'opacity-40'
            }`}
            title="Toggle volume"
          >
            Vol
          </button>
          <button
            onClick={() => setShowVolumeProfile((v) => !v)}
            className={`px-2 py-0.5 rounded text-xs text-gray-300 hover:bg-white/10 transition-colors ${
              showVolumeProfile ? '' : 'opacity-40'
            }`}
            title="Toggle volume-by-price profile"
          >
            Profile
          </button>
          <button
            onClick={() => setShowSupportResistance((v) => !v)}
            className={`px-2 py-0.5 rounded text-xs text-gray-300 hover:bg-white/10 transition-colors ${
              showSupportResistance ? '' : 'opacity-40'
            }`}
            title="Toggle support/resistance levels"
          >
            S/R
          </button>
          {/* Attribution required by the lightweight-charts license */}
          <a
            href="https://www.tradingview.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="ml-auto text-[10px] text-gray-600 hover:text-gray-400 transition-colors"
          >
            Charts by TradingView
          </a>
        </div>

        {/* Chart / states */}
        {isLoading && (
          <div className="flex-1 flex flex-col items-center justify-center text-gray-400">
            <RefreshCw size={32} className="animate-spin mb-3" />
            <p>Loading {symbol} chart...</p>
          </div>
        )}

        {isError && (
          <div className="p-4">
            <div className="p-4 bg-red-500/10 border border-red-500/30 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="text-red-400 flex-shrink-0" size={20} />
                <div>
                  <p className="text-red-400 font-medium">Chart unavailable</p>
                  <p className="text-sm text-gray-400 mt-1">
                    {(error as any)?.response?.data?.detail || 'Failed to load price history'}
                  </p>
                  <button
                    onClick={() => refetch()}
                    className="mt-3 px-3 py-1 text-sm bg-white/10 hover:bg-white/20 rounded-lg text-gray-200 transition-colors"
                  >
                    Retry
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {data && data.candles.length > 0 && (
          <CandlestickChart
            data={data}
            range={range}
            visibleOverlays={visibleOverlays}
            showVolume={showVolume}
            showVolumeProfile={showVolumeProfile}
            showSupportResistance={showSupportResistance}
          />
        )}
      </div>
    </>
  );
}
