/**
 * TradeIdeaForm component for creating and editing trade ideas
 * - Portions generated by AI
 */

import React, { useState, useEffect } from 'react';
import type { TradeIdea, TradeIdeaCreateRequest } from '@/types';

interface TradeIdeaFormProps {
  idea?: TradeIdea | null;
  onSave: (data: TradeIdeaCreateRequest) => void;
  onCancel: () => void;
  loading?: boolean;
}

export function TradeIdeaForm({ idea, onSave, onCancel, loading }: TradeIdeaFormProps) {
  const [name, setName] = useState(idea?.name || '');
  const [description, setDescription] = useState(idea?.description || '');
  const [symbolsText, setSymbolsText] = useState(idea?.symbols.join(', ') || '');

  // Reset form when idea prop changes
  useEffect(() => {
    setName(idea?.name || '');
    setDescription(idea?.description || '');
    setSymbolsText(idea?.symbols.join(', ') || '');
  }, [idea]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Parse symbols from text
    const symbols = symbolsText
      .split(/[,\s\n]+/)
      .map((s) => s.trim().toUpperCase())
      .filter((s) => s.length > 0);

    if (symbols.length === 0) {
      alert('Please enter at least one symbol');
      return;
    }

    if (!name.trim()) {
      alert('Please enter a name');
      return;
    }

    onSave({
      name: name.trim(),
      description: description.trim() || undefined,
      symbols,
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
        {idea ? 'Edit Trade Idea' : 'Create New Trade Idea'}
      </h3>

      {/* Name */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Name *
        </label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="e.g., My Tech Picks"
          required
          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg
                     bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                     focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Description (optional)
        </label>
        <input
          type="text"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="e.g., Tech stocks I'm watching"
          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg
                     bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                     focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      {/* Symbols */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Symbols *
        </label>
        <textarea
          value={symbolsText}
          onChange={(e) => setSymbolsText(e.target.value)}
          placeholder="AAPL, MSFT, GOOGL, TSLA"
          rows={4}
          required
          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg
                     bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                     focus:ring-2 focus:ring-blue-500 focus:border-transparent
                     font-mono text-sm"
        />
        <p className="text-xs text-gray-500 mt-1">
          Enter symbols separated by commas, spaces, or new lines
        </p>
      </div>

      {/* Preview */}
      {symbolsText && (
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-3">
          <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-2">
            Preview ({symbolsText.split(/[,\s\n]+/).filter(s => s.trim()).length} symbols)
          </p>
          <div className="flex flex-wrap gap-1">
            {symbolsText
              .split(/[,\s\n]+/)
              .map((s) => s.trim().toUpperCase())
              .filter((s) => s.length > 0)
              .map((symbol, i) => (
                <span
                  key={i}
                  className="px-2 py-0.5 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200
                             rounded text-xs font-medium"
                >
                  {symbol}
                </span>
              ))}
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex justify-end gap-3 pt-4">
        <button
          type="button"
          onClick={onCancel}
          disabled={loading}
          className="px-4 py-2 text-gray-700 dark:text-gray-300 bg-gray-200 dark:bg-gray-700
                     rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={loading}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700
                     transition-colors disabled:opacity-50 disabled:cursor-not-allowed
                     flex items-center gap-2"
        >
          {loading && (
            <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
          )}
          {idea ? 'Update' : 'Create'}
        </button>
      </div>
    </form>
  );
}

export default TradeIdeaForm;
