/**
 * User menu component with auth state
 * - Portions generated by AI
 */

import { useEffect, useState } from 'react';
import { UserButton, useAuth } from '@clerk/clerk-react';
import { User, LogIn, Shield } from 'lucide-react';
import { Link } from 'react-router-dom';
import apiClient from '@/api/client';

const CLERK_ENABLED = !!import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;

export function UserMenu() {
  if (!CLERK_ENABLED) {
    return (
      <div className="flex items-center gap-2 px-3 py-2 bg-dark-800 rounded-lg border border-white/10">
        <User size={18} className="text-primary-400" />
        <span className="text-sm text-gray-300">Dev Mode</span>
      </div>
    );
  }

  return <AuthenticatedUserMenu />;
}

function AuthenticatedUserMenu() {
  const { isLoaded, isSignedIn } = useAuth();
  const [isAdmin, setIsAdmin] = useState(false);

  useEffect(() => {
    if (isSignedIn) {
      apiClient.checkIsAdmin()
        .then((res) => setIsAdmin(res.is_admin))
        .catch(() => setIsAdmin(false));
    } else {
      setIsAdmin(false);
    }
  }, [isSignedIn]);

  if (!isLoaded) {
    return (
      <div className="w-8 h-8 bg-dark-700 rounded-full animate-pulse" />
    );
  }

  if (!isSignedIn) {
    return (
      <Link
        to="/sign-in"
        className="flex items-center gap-2 px-4 py-2 bg-primary-500 hover:bg-primary-600 rounded-lg transition-colors text-sm font-medium"
      >
        <LogIn size={16} />
        Sign In
      </Link>
    );
  }

  return (
    <UserButton
      afterSignOutUrl="/sign-in"
      appearance={{
        elements: {
          avatarBox: 'w-9 h-9',
          userButtonPopoverCard: 'bg-dark-800 border border-white/10',
          userButtonPopoverActionButton: 'text-gray-200 hover:text-white hover:bg-dark-700',
          userButtonPopoverActionButtonText: '!text-gray-200',
          userButtonPopoverActionButtonIcon: '!text-gray-200',
          userButtonPopoverCustomItemButton: '!text-gray-200 hover:!text-white hover:bg-dark-700',
          userButtonPopoverCustomItemButtonText: '!text-gray-200',
          userButtonPopoverFooter: 'hidden',
        },
      }}
    >
      {isAdmin && (
        <UserButton.MenuItems>
          <UserButton.Link
            label="Admin"
            href="/admin"
            labelIcon={<Shield size={16} className="text-gray-200" />}
          />
        </UserButton.MenuItems>
      )}
    </UserButton>
  );
}
