/**
 * User menu component with auth state
 * - Portions generated by AI
 */

import { useEffect, useState } from 'react';
import { UserButton, useUser, useAuth } from '@clerk/clerk-react';
import { User, LogIn, Shield } from 'lucide-react';
import { Link } from 'react-router-dom';
import apiClient from '@/api/client';

// Check if Clerk is configured
const CLERK_ENABLED = !!import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;

export function UserMenu() {
  // If Clerk is not enabled, show dev mode indicator
  if (!CLERK_ENABLED) {
    return (
      <div className="flex items-center gap-2 px-3 py-2 bg-dark-800 rounded-lg border border-white/10">
        <User size={18} className="text-primary-400" />
        <span className="text-sm text-gray-300">Dev Mode</span>
      </div>
    );
  }

  return <AuthenticatedUserMenu />;
}

function AuthenticatedUserMenu() {
  const { isLoaded, isSignedIn } = useAuth();
  const { user } = useUser();
  const [isAdmin, setIsAdmin] = useState(false);

  // Check admin status when user is signed in
  useEffect(() => {
    if (isSignedIn) {
      apiClient.checkIsAdmin()
        .then((res) => setIsAdmin(res.is_admin))
        .catch(() => setIsAdmin(false));
    } else {
      setIsAdmin(false);
    }
  }, [isSignedIn]);

  if (!isLoaded) {
    return (
      <div className="w-8 h-8 bg-dark-700 rounded-full animate-pulse" />
    );
  }

  if (!isSignedIn) {
    return (
      <Link
        to="/sign-in"
        className="flex items-center gap-2 px-4 py-2 bg-primary-500 hover:bg-primary-600 rounded-lg transition-colors text-sm font-medium"
      >
        <LogIn size={16} />
        Sign In
      </Link>
    );
  }

  const emailDisplay = user?.primaryEmailAddress?.emailAddress || user?.firstName || 'User';

  return (
    <div className="flex items-center gap-3">
      {isAdmin ? (
        <Link
          to="/admin"
          className="hidden sm:flex items-center gap-1.5 text-sm text-primary-400 hover:text-primary-300 transition-colors"
          title="Admin Dashboard"
        >
          <Shield size={14} />
          <span>{emailDisplay}</span>
        </Link>
      ) : (
        <span className="text-sm text-gray-300 hidden sm:inline">
          {emailDisplay}
        </span>
      )}
      <UserButton
        afterSignOutUrl="/sign-in"
        appearance={{
          elements: {
            avatarBox: 'w-9 h-9',
            userButtonPopoverCard: 'bg-dark-800 border border-white/10',
            userButtonPopoverActionButton: 'text-gray-300 hover:text-white hover:bg-dark-700',
            userButtonPopoverActionButtonText: 'text-gray-300',
            userButtonPopoverFooter: 'hidden',
          },
        }}
      />
    </div>
  );
}
