"""
Seed system filters and trade ideas
- Portions generated by AI

Run this script to populate initial system data:
    cd backend
    python -m scripts.seed_system_data
"""

import sys
import os

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database import SessionLocal, init_db
from app.models import Filter, TradeIdea


# System Filters to seed
SYSTEM_FILTERS = [
    {
        "name": "Conservative",
        "is_default": True,  # First one is default
        "min_dte": 15,
        "max_dte": 45,
        "min_volume": 10,
        "min_open_interest": 10,
        "min_annualized_return": 20.0,
        "max_assignment_probability": 20,
    },
    {
        "name": "Moderate",
        "is_default": False,
        "min_dte": 7,
        "max_dte": 21,
        "min_volume": 50,
        "min_open_interest": 50,
        "min_annualized_return": 30.0,
        "max_assignment_probability": 15,
    },
    {
        "name": "Aggressive",
        "is_default": False,
        "min_dte": 3,
        "max_dte": 14,
        "min_volume": 100,
        "min_open_interest": 100,
        "min_annualized_return": 50.0,
        "max_assignment_probability": 10,
    },
]

# System Trade Ideas to seed
SYSTEM_TRADE_IDEAS = [
    {
        "name": "Mag 7",
        "description": "The Magnificent Seven - largest tech companies",
        "is_default": True,  # First one is default
        "symbols": "AAPL,MSFT,GOOGL,AMZN,META,NVDA,TSLA",
    },
    {
        "name": "Crypto Plays",
        "description": "Crypto-related stocks and ETFs",
        "is_default": False,
        "symbols": "COIN,MSTR,IBIT,ETHA",
    },
    {
        "name": "AI and Chips",
        "description": "AI and semiconductor companies",
        "is_default": False,
        "symbols": "NVDA,AMD,AVGO,PLTR,CRWV",
    },
]


def seed_system_filters(db) -> int:
    """Seed system filters, skip if already exist"""
    existing = db.query(Filter).filter(Filter.is_system == True).count()
    if existing > 0:
        print(f"System filters already exist ({existing} found), skipping...")
        return 0
    
    created = 0
    for filter_data in SYSTEM_FILTERS:
        new_filter = Filter(
            name=filter_data["name"],
            is_system=True,
            is_default=filter_data["is_default"],
            user_id=None,
            min_dte=filter_data["min_dte"],
            max_dte=filter_data["max_dte"],
            min_volume=filter_data["min_volume"],
            min_open_interest=filter_data["min_open_interest"],
            min_annualized_return=filter_data["min_annualized_return"],
            max_assignment_probability=filter_data["max_assignment_probability"],
        )
        db.add(new_filter)
        created += 1
        print(f"  Created filter: {filter_data['name']}")
    
    return created


def seed_system_trade_ideas(db) -> int:
    """Seed system trade ideas, skip if already exist"""
    existing = db.query(TradeIdea).filter(TradeIdea.is_system == True).count()
    if existing > 0:
        print(f"System trade ideas already exist ({existing} found), skipping...")
        return 0
    
    created = 0
    for idea_data in SYSTEM_TRADE_IDEAS:
        new_idea = TradeIdea(
            name=idea_data["name"],
            description=idea_data.get("description"),
            is_system=True,
            is_default=idea_data["is_default"],
            user_id=None,
            symbols=idea_data["symbols"],
        )
        db.add(new_idea)
        created += 1
        print(f"  Created trade idea: {idea_data['name']}")
    
    return created


def main():
    """Main function to seed all system data"""
    print("Initializing database...")
    init_db()
    
    print("\nSeeding system data...")
    db = SessionLocal()
    
    try:
        print("\n1. Seeding system filters...")
        filters_created = seed_system_filters(db)
        
        print("\n2. Seeding system trade ideas...")
        ideas_created = seed_system_trade_ideas(db)
        
        db.commit()
        
        print("\n" + "=" * 50)
        print(f"Seeding complete!")
        print(f"  Filters created: {filters_created}")
        print(f"  Trade ideas created: {ideas_created}")
        print("=" * 50)
        
    except Exception as e:
        print(f"\nError during seeding: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
