"""
Admin API endpoints for managing system filters and trade ideas
- Portions generated by AI
"""

from typing import List, Literal
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ...core.database import get_db
from ...core.deps import get_current_admin
from ...core.config import get_settings
from ...core.market_clock import to_market_iso
from ...models import User, Filter, TradeIdea, CacheSettings, ApiProviderSettings, MarketSettings
from ...schemas.filter import FilterCreate, FilterUpdate, FilterResponse
from ...schemas.trade_idea import TradeIdeaCreate, TradeIdeaUpdate, TradeIdeaResponse

router = APIRouter()


class ReorderRequest(BaseModel):
    """Request schema for reordering items"""
    ids: List[str]  # Ordered list of IDs


# ============== System Filters ==============

def _filter_to_response(filter_obj: Filter) -> FilterResponse:
    """Convert Filter model to response schema"""
    return FilterResponse(
        id=filter_obj.id,
        name=filter_obj.name,
        is_system=filter_obj.is_system,
        is_default=filter_obj.is_default,
        display_order=filter_obj.display_order,
        user_id=filter_obj.user_id,
        min_dte=filter_obj.min_dte,
        max_dte=filter_obj.max_dte,
        min_volume=filter_obj.min_volume,
        min_open_interest=filter_obj.min_open_interest,
        min_annualized_return=filter_obj.min_annualized_return,
        max_assignment_probability=filter_obj.max_assignment_probability,
        created_at=filter_obj.created_at,
        updated_at=filter_obj.updated_at,
    )


@router.get("/filters", response_model=List[FilterResponse])
async def list_system_filters(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """List all system filters (admin only)."""
    filters = db.query(Filter).filter(Filter.is_system == True).order_by(Filter.display_order).all()
    return [_filter_to_response(f) for f in filters]


@router.put("/filters/reorder", response_model=List[FilterResponse])
async def reorder_system_filters(
    request: ReorderRequest,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Reorder system filters (admin only)."""
    # Verify all IDs are valid system filters
    filters = db.query(Filter).filter(
        Filter.id.in_(request.ids),
        Filter.is_system == True
    ).all()
    
    if len(filters) != len(request.ids):
        raise HTTPException(status_code=400, detail="Invalid filter IDs provided")
    
    # Create a map for quick lookup
    filter_map = {f.id: f for f in filters}
    
    # Update display_order based on position in the list
    for index, filter_id in enumerate(request.ids):
        filter_map[filter_id].display_order = index
    
    db.commit()
    
    # Return updated filters in new order
    ordered_filters = [filter_map[fid] for fid in request.ids]
    return [_filter_to_response(f) for f in ordered_filters]


@router.post("/filters", response_model=FilterResponse)
async def create_system_filter(
    filter_data: FilterCreate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Create a new system filter (admin only)."""
    # Generate name if not provided
    name = filter_data.name
    if not name:
        name = Filter.generate_name(
            filter_data.min_dte,
            filter_data.max_dte,
            filter_data.min_volume,
            filter_data.min_open_interest,
            filter_data.max_assignment_probability,
        )
    
    # Check if this is the first system filter (make it default)
    existing_system_filters = db.query(Filter).filter(Filter.is_system == True).count()
    is_default = existing_system_filters == 0
    
    new_filter = Filter(
        name=name,
        is_system=True,
        is_default=is_default,
        user_id=None,
        min_dte=filter_data.min_dte,
        max_dte=filter_data.max_dte,
        min_volume=filter_data.min_volume,
        min_open_interest=filter_data.min_open_interest,
        min_annualized_return=filter_data.min_annualized_return,
        max_assignment_probability=filter_data.max_assignment_probability,
    )
    
    db.add(new_filter)
    db.commit()
    db.refresh(new_filter)
    
    return _filter_to_response(new_filter)


@router.put("/filters/{filter_id}", response_model=FilterResponse)
async def update_system_filter(
    filter_id: str,
    filter_data: FilterUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Update a system filter (admin only)."""
    filter_obj = db.query(Filter).filter(
        Filter.id == filter_id,
        Filter.is_system == True
    ).first()
    
    if not filter_obj:
        raise HTTPException(status_code=404, detail="System filter not found")
    
    # Update fields
    update_data = filter_data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(filter_obj, field, value)
    
    db.commit()
    db.refresh(filter_obj)
    
    return _filter_to_response(filter_obj)


@router.put("/filters/{filter_id}/set-default", response_model=FilterResponse)
async def set_default_system_filter(
    filter_id: str,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Set a system filter as the default (admin only)."""
    filter_obj = db.query(Filter).filter(
        Filter.id == filter_id,
        Filter.is_system == True
    ).first()
    
    if not filter_obj:
        raise HTTPException(status_code=404, detail="System filter not found")
    
    # Unset current default
    db.query(Filter).filter(
        Filter.is_system == True,
        Filter.is_default == True
    ).update({"is_default": False})
    
    # Set new default
    filter_obj.is_default = True
    db.commit()
    db.refresh(filter_obj)
    
    return _filter_to_response(filter_obj)


@router.delete("/filters/{filter_id}")
async def delete_system_filter(
    filter_id: str,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Delete a system filter (admin only). Cannot delete the default filter."""
    filter_obj = db.query(Filter).filter(
        Filter.id == filter_id,
        Filter.is_system == True
    ).first()
    
    if not filter_obj:
        raise HTTPException(status_code=404, detail="System filter not found")
    
    if filter_obj.is_default:
        raise HTTPException(
            status_code=400,
            detail="Cannot delete the default filter. Set another filter as default first."
        )
    
    db.delete(filter_obj)
    db.commit()
    
    return {"message": "System filter deleted successfully"}


# ============== System Trade Ideas ==============

def _trade_idea_to_response(idea: TradeIdea) -> TradeIdeaResponse:
    """Convert TradeIdea model to response schema"""
    return TradeIdeaResponse(
        id=idea.id,
        name=idea.name,
        description=idea.description,
        is_system=idea.is_system,
        is_default=idea.is_default,
        display_order=idea.display_order,
        user_id=idea.user_id,
        symbols=idea.get_symbols_list(),
        created_at=idea.created_at,
        updated_at=idea.updated_at,
    )


@router.get("/trade-ideas", response_model=List[TradeIdeaResponse])
async def list_system_trade_ideas(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """List all system trade ideas (admin only)."""
    ideas = db.query(TradeIdea).filter(TradeIdea.is_system == True).order_by(TradeIdea.display_order).all()
    return [_trade_idea_to_response(i) for i in ideas]


@router.put("/trade-ideas/reorder", response_model=List[TradeIdeaResponse])
async def reorder_system_trade_ideas(
    request: ReorderRequest,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Reorder system trade ideas (admin only)."""
    # Verify all IDs are valid system trade ideas
    ideas = db.query(TradeIdea).filter(
        TradeIdea.id.in_(request.ids),
        TradeIdea.is_system == True
    ).all()
    
    if len(ideas) != len(request.ids):
        raise HTTPException(status_code=400, detail="Invalid trade idea IDs provided")
    
    # Create a map for quick lookup
    idea_map = {i.id: i for i in ideas}
    
    # Update display_order based on position in the list
    for index, idea_id in enumerate(request.ids):
        idea_map[idea_id].display_order = index
    
    db.commit()
    
    # Return updated trade ideas in new order
    ordered_ideas = [idea_map[iid] for iid in request.ids]
    return [_trade_idea_to_response(i) for i in ordered_ideas]


@router.post("/trade-ideas", response_model=TradeIdeaResponse)
async def create_system_trade_idea(
    idea_data: TradeIdeaCreate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Create a new system trade idea (admin only)."""
    # Check if this is the first system trade idea (make it default)
    existing_system_ideas = db.query(TradeIdea).filter(TradeIdea.is_system == True).count()
    is_default = existing_system_ideas == 0
    
    new_idea = TradeIdea(
        name=idea_data.name,
        description=idea_data.description,
        is_system=True,
        is_default=is_default,
        user_id=None,
        symbols=",".join(idea_data.symbols),
    )
    
    db.add(new_idea)
    db.commit()
    db.refresh(new_idea)
    
    return _trade_idea_to_response(new_idea)


@router.put("/trade-ideas/{idea_id}", response_model=TradeIdeaResponse)
async def update_system_trade_idea(
    idea_id: str,
    idea_data: TradeIdeaUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Update a system trade idea (admin only)."""
    idea = db.query(TradeIdea).filter(
        TradeIdea.id == idea_id,
        TradeIdea.is_system == True
    ).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="System trade idea not found")
    
    # Update fields
    update_data = idea_data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        if field == "symbols" and value is not None:
            idea.symbols = ",".join(value)
        else:
            setattr(idea, field, value)
    
    db.commit()
    db.refresh(idea)
    
    return _trade_idea_to_response(idea)


@router.put("/trade-ideas/{idea_id}/set-default", response_model=TradeIdeaResponse)
async def set_default_system_trade_idea(
    idea_id: str,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Set a system trade idea as the default (admin only)."""
    idea = db.query(TradeIdea).filter(
        TradeIdea.id == idea_id,
        TradeIdea.is_system == True
    ).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="System trade idea not found")
    
    # Unset current default
    db.query(TradeIdea).filter(
        TradeIdea.is_system == True,
        TradeIdea.is_default == True
    ).update({"is_default": False})
    
    # Set new default
    idea.is_default = True
    db.commit()
    db.refresh(idea)
    
    return _trade_idea_to_response(idea)


@router.delete("/trade-ideas/{idea_id}")
async def delete_system_trade_idea(
    idea_id: str,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Delete a system trade idea (admin only). Cannot delete the default idea."""
    idea = db.query(TradeIdea).filter(
        TradeIdea.id == idea_id,
        TradeIdea.is_system == True
    ).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="System trade idea not found")
    
    if idea.is_default:
        raise HTTPException(
            status_code=400,
            detail="Cannot delete the default trade idea. Set another as default first."
        )
    
    db.delete(idea)
    db.commit()
    
    return {"message": "System trade idea deleted successfully"}


# ============== API Provider Settings ==============

class ApiProviderSettingsResponse(BaseModel):
    """Response schema for API provider settings"""
    active_provider: str  # "massive" or "alpaca"
    use_midpoint_pricing: bool
    massive_api_configured: bool
    alpaca_api_configured: bool
    updated_at: str | None = None


class ApiProviderSettingsUpdate(BaseModel):
    """Request schema for updating API provider settings"""
    active_provider: Literal["massive", "alpaca"] | None = None
    use_midpoint_pricing: bool | None = None


def _get_or_create_api_provider_settings(db: Session) -> ApiProviderSettings:
    """Get the API provider settings row, creating it with defaults if it doesn't exist."""
    settings = db.query(ApiProviderSettings).filter(ApiProviderSettings.id == 1).first()
    if not settings:
        settings = ApiProviderSettings(
            id=1,
            active_provider="massive",
            use_midpoint_pricing=True,
        )
        db.add(settings)
        db.commit()
        db.refresh(settings)
    return settings


def _check_api_keys_configured() -> tuple[bool, bool]:
    """Check if API keys are configured for each provider."""
    settings = get_settings()
    massive_configured = bool(settings.MASSIVE_API_KEY)
    alpaca_configured = bool(settings.ALPACA_API_KEY and settings.ALPACA_SECRET_KEY)
    return massive_configured, alpaca_configured


@router.get("/api-provider", response_model=ApiProviderSettingsResponse)
async def get_api_provider_settings(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Get current API provider settings (admin only)."""
    settings = _get_or_create_api_provider_settings(db)
    massive_configured, alpaca_configured = _check_api_keys_configured()
    
    return ApiProviderSettingsResponse(
        active_provider=settings.active_provider,
        use_midpoint_pricing=settings.use_midpoint_pricing,
        massive_api_configured=massive_configured,
        alpaca_api_configured=alpaca_configured,
        updated_at=to_market_iso(settings.updated_at),
    )


@router.put("/api-provider", response_model=ApiProviderSettingsResponse)
async def update_api_provider_settings(
    data: ApiProviderSettingsUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Update API provider settings (admin only)."""
    from ...core.api_provider import update_api_provider_settings_in_memory
    
    settings = _get_or_create_api_provider_settings(db)
    massive_configured, alpaca_configured = _check_api_keys_configured()
    
    # Validate provider switch
    if data.active_provider:
        if data.active_provider == "alpaca" and not alpaca_configured:
            raise HTTPException(
                status_code=400,
                detail="Cannot switch to Alpaca: ALPACA_API_KEY and ALPACA_SECRET_KEY are not configured"
            )
        if data.active_provider == "massive" and not massive_configured:
            raise HTTPException(
                status_code=400,
                detail="Cannot switch to Massive: MASSIVE_API_KEY is not configured"
            )
    
    # Update fields that were provided
    update_data = data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(settings, field, value)
    
    db.commit()
    db.refresh(settings)
    
    # Update in-memory API provider settings
    update_api_provider_settings_in_memory(settings.to_dict())
    
    return ApiProviderSettingsResponse(
        active_provider=settings.active_provider,
        use_midpoint_pricing=settings.use_midpoint_pricing,
        massive_api_configured=massive_configured,
        alpaca_api_configured=alpaca_configured,
        updated_at=to_market_iso(settings.updated_at),
    )


# ============== Cache Settings ==============

class CacheSettingsResponse(BaseModel):
    """Response schema for cache settings"""
    cache_enabled: bool
    ttl_stock_price: int
    ttl_options_chain: int
    ttl_news: int
    ttl_event_dates: int
    updated_at: str | None = None


class CacheSettingsUpdate(BaseModel):
    """Request schema for updating cache settings"""
    cache_enabled: bool | None = None
    ttl_stock_price: int | None = None
    ttl_options_chain: int | None = None
    ttl_news: int | None = None
    ttl_event_dates: int | None = None


def _get_or_create_cache_settings(db: Session) -> CacheSettings:
    """Get the cache settings row, creating it with defaults if it doesn't exist."""
    settings = db.query(CacheSettings).filter(CacheSettings.id == 1).first()
    if not settings:
        settings = CacheSettings(
            id=1,
            cache_enabled=True,
            ttl_stock_price=180,
            ttl_options_chain=300,
            ttl_news=900,
            ttl_event_dates=604800,  # 1 week default
        )
        db.add(settings)
        db.commit()
        db.refresh(settings)
    return settings


@router.get("/cache-settings", response_model=CacheSettingsResponse)
async def get_cache_settings(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Get current cache settings (admin only)."""
    settings = _get_or_create_cache_settings(db)
    return CacheSettingsResponse(
        cache_enabled=settings.cache_enabled,
        ttl_stock_price=settings.ttl_stock_price,
        ttl_options_chain=settings.ttl_options_chain,
        ttl_news=settings.ttl_news,
        ttl_event_dates=settings.ttl_event_dates if hasattr(settings, 'ttl_event_dates') else 604800,
        updated_at=to_market_iso(settings.updated_at),
    )


@router.put("/cache-settings", response_model=CacheSettingsResponse)
async def update_cache_settings(
    data: CacheSettingsUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """Update cache settings (admin only)."""
    from ...core.cache import update_cache_settings_in_memory, clear_app_cache
    
    settings = _get_or_create_cache_settings(db)
    was_enabled = settings.cache_enabled
    
    # Update fields that were provided
    update_data = data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(settings, field, value)
    
    db.commit()
    db.refresh(settings)

    # Drop stale entries when caching is turned off so a later re-enable
    # cannot serve data from before the disable.
    if was_enabled and not settings.cache_enabled:
        clear_app_cache()
    
    # Update in-memory cache settings
    update_cache_settings_in_memory(settings.to_dict())
    
    return CacheSettingsResponse(
        cache_enabled=settings.cache_enabled,
        ttl_stock_price=settings.ttl_stock_price,
        ttl_options_chain=settings.ttl_options_chain,
        ttl_news=settings.ttl_news,
        ttl_event_dates=settings.ttl_event_dates if hasattr(settings, 'ttl_event_dates') else 604800,
        updated_at=to_market_iso(settings.updated_at),
    )


# ============== Market Settings ==============

class MarketSettingsResponse(BaseModel):
    """Response schema for market settings"""
    risk_free_rate: float
    risk_free_rate_percent: float  # Convenience field: risk_free_rate * 100
    updated_at: str | None = None


class MarketSettingsUpdate(BaseModel):
    """Request schema for updating market settings"""
    risk_free_rate: float | None = None  # As decimal (e.g., 0.0367 for 3.67%)


def _get_or_create_market_settings(db: Session) -> MarketSettings:
    """Get the market settings row, creating it with defaults if it doesn't exist."""
    settings = db.query(MarketSettings).filter(MarketSettings.id == 1).first()
    if not settings:
        settings = MarketSettings(
            id=1,
            risk_free_rate=0.0367,  # Current 3-month Treasury rate from FRED
        )
        db.add(settings)
        db.commit()
        db.refresh(settings)
    return settings


@router.get("/market-settings", response_model=MarketSettingsResponse)
async def get_market_settings(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """
    Get current market settings (admin only).
    
    The risk-free rate is used for Greeks calculations (Black-Scholes model).
    Reference: https://fred.stlouisfed.org/series/DGS3MO
    """
    settings = _get_or_create_market_settings(db)
    return MarketSettingsResponse(
        risk_free_rate=settings.risk_free_rate,
        risk_free_rate_percent=settings.risk_free_rate * 100,
        updated_at=to_market_iso(settings.updated_at),
    )


@router.put("/market-settings", response_model=MarketSettingsResponse)
async def update_market_settings(
    data: MarketSettingsUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """
    Update market settings (admin only).
    
    The risk-free rate should be provided as a decimal (e.g., 0.0367 for 3.67%).
    Get the current rate from: https://fred.stlouisfed.org/series/DGS3MO
    """
    from ...core.market_settings import update_market_settings_in_memory
    
    settings = _get_or_create_market_settings(db)
    
    # Validate risk-free rate if provided
    if data.risk_free_rate is not None:
        if data.risk_free_rate < 0 or data.risk_free_rate > 1:
            raise HTTPException(
                status_code=400,
                detail="Risk-free rate must be between 0 and 1 (e.g., 0.0367 for 3.67%)"
            )
        settings.risk_free_rate = data.risk_free_rate
    
    db.commit()
    db.refresh(settings)
    
    # Update in-memory market settings
    update_market_settings_in_memory(settings.to_dict())
    
    return MarketSettingsResponse(
        risk_free_rate=settings.risk_free_rate,
        risk_free_rate_percent=settings.risk_free_rate * 100,
        updated_at=to_market_iso(settings.updated_at),
    )


# ============== Seed System Data ==============

# System Filters to seed
SYSTEM_FILTERS = [
    {
        "name": "Conservative",
        "is_default": True,
        "min_dte": 15,
        "max_dte": 45,
        "min_volume": 10,
        "min_open_interest": 10,
        "min_annualized_return": 20.0,
        "max_assignment_probability": 20,
    },
    {
        "name": "Moderate",
        "is_default": False,
        "min_dte": 7,
        "max_dte": 21,
        "min_volume": 50,
        "min_open_interest": 50,
        "min_annualized_return": 30.0,
        "max_assignment_probability": 15,
    },
    {
        "name": "Aggressive",
        "is_default": False,
        "min_dte": 3,
        "max_dte": 14,
        "min_volume": 100,
        "min_open_interest": 100,
        "min_annualized_return": 50.0,
        "max_assignment_probability": 10,
    },
]

# System Trade Ideas to seed
SYSTEM_TRADE_IDEAS = [
    {
        "name": "Mag 7",
        "description": "The Magnificent Seven - largest tech companies",
        "is_default": True,
        "symbols": "AAPL,MSFT,GOOGL,AMZN,META,NVDA,TSLA",
    },
    {
        "name": "Crypto Plays",
        "description": "Crypto-related stocks and ETFs",
        "is_default": False,
        "symbols": "COIN,MSTR,IBIT,ETHA",
    },
    {
        "name": "AI and Chips",
        "description": "AI and semiconductor companies",
        "is_default": False,
        "symbols": "NVDA,AMD,AVGO,PLTR,CRWV",
    },
]


@router.post("/seed")
async def seed_system_data(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db)
):
    """
    Seed system filters and trade ideas (admin only).
    This is idempotent - will skip if data already exists.
    """
    results = {
        "filters_created": 0,
        "filters_skipped": False,
        "trade_ideas_created": 0,
        "trade_ideas_skipped": False,
    }
    
    # Seed filters
    existing_filters = db.query(Filter).filter(Filter.is_system == True).count()
    if existing_filters > 0:
        results["filters_skipped"] = True
        results["filters_existing"] = existing_filters
    else:
        for filter_data in SYSTEM_FILTERS:
            new_filter = Filter(
                name=filter_data["name"],
                is_system=True,
                is_default=filter_data["is_default"],
                user_id=None,
                min_dte=filter_data["min_dte"],
                max_dte=filter_data["max_dte"],
                min_volume=filter_data["min_volume"],
                min_open_interest=filter_data["min_open_interest"],
                min_annualized_return=filter_data["min_annualized_return"],
                max_assignment_probability=filter_data["max_assignment_probability"],
            )
            db.add(new_filter)
            results["filters_created"] += 1
    
    # Seed trade ideas
    existing_ideas = db.query(TradeIdea).filter(TradeIdea.is_system == True).count()
    if existing_ideas > 0:
        results["trade_ideas_skipped"] = True
        results["trade_ideas_existing"] = existing_ideas
    else:
        for idea_data in SYSTEM_TRADE_IDEAS:
            new_idea = TradeIdea(
                name=idea_data["name"],
                description=idea_data.get("description"),
                is_system=True,
                is_default=idea_data["is_default"],
                user_id=None,
                symbols=idea_data["symbols"],
            )
            db.add(new_idea)
            results["trade_ideas_created"] += 1
    
    db.commit()
    
    return {
        "message": "Seed operation complete",
        "results": results
    }
