"""
Stock Analysis API endpoints
- Portions generated by AI
"""

import json
from typing import Union
from datetime import datetime, timezone, timedelta
from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session

from ...core.database import get_db
from ...core.market_clock import to_market_iso
from ...models import AISettings, AnalysisCache
from ...schemas.analysis import (
    StockAnalysis,
    AnalysisErrorResponse,
    AISettingsResponse,
    AISettingsUpdate,
)
from ...services.stock_analyzer import analyze_stock, analyze_stock_safe
from ...services.llm import get_available_providers

router = APIRouter()


def get_ai_settings(db: Session) -> AISettings:
    """Get or create AI settings singleton."""
    settings = db.query(AISettings).filter(AISettings.id == 1).first()
    if not settings:
        settings = AISettings(id=1)
        db.add(settings)
        db.commit()
        db.refresh(settings)
    return settings


def get_cached_analysis(db: Session, symbol: str) -> dict | None:
    """Get cached analysis from database if available and not expired."""
    symbol = symbol.upper()
    now = datetime.utcnow()
    
    cached = db.query(AnalysisCache).filter(
        AnalysisCache.symbol == symbol,
        AnalysisCache.expires_at > now
    ).first()
    
    if cached:
        try:
            result = json.loads(cached.analysis_json)
            result['cached_at'] = to_market_iso(cached.created_at)
            result['expires_at'] = to_market_iso(cached.expires_at)
            print(f"[Analysis Cache HIT] {symbol}")
            return result
        except json.JSONDecodeError:
            # Invalid cache entry, delete it
            db.delete(cached)
            db.commit()
    
    return None


def cache_analysis(db: Session, symbol: str, analysis: dict, ttl_seconds: int):
    """Cache analysis result to database."""
    symbol = symbol.upper()
    now = datetime.utcnow()
    expires_at = now + timedelta(seconds=ttl_seconds)
    
    # Remove cache metadata before storing (we'll add it on retrieval)
    analysis_to_store = {k: v for k, v in analysis.items() if k not in ['cached_at', 'expires_at']}
    analysis_json = json.dumps(analysis_to_store)
    
    # Upsert - update if exists, insert if not
    existing = db.query(AnalysisCache).filter(AnalysisCache.symbol == symbol).first()
    
    if existing:
        existing.analysis_json = analysis_json
        existing.created_at = now
        existing.expires_at = expires_at
    else:
        new_cache = AnalysisCache(
            symbol=symbol,
            analysis_json=analysis_json,
            created_at=now,
            expires_at=expires_at
        )
        db.add(new_cache)
    
    db.commit()
    print(f"[Analysis Cache SET] {symbol} (expires in {ttl_seconds}s)")


def cleanup_expired_cache(db: Session) -> int:
    """Remove expired cache entries. Returns count of deleted entries."""
    now = datetime.utcnow()
    expired = db.query(AnalysisCache).filter(AnalysisCache.expires_at <= now).all()
    count = len(expired)
    
    if count > 0:
        for entry in expired:
            db.delete(entry)
        db.commit()
        print(f"[Analysis Cache CLEANUP] Removed {count} expired entries")
    
    return count


@router.post("/{symbol}", response_model=Union[StockAnalysis, AnalysisErrorResponse])
async def analyze_stock_endpoint(
    symbol: str,
    force_refresh: bool = False,
    db: Session = Depends(get_db)
):
    """
    Generate AI-powered stock analysis.
    
    - Results are cached for the configured TTL (default 1 day)
    - Use force_refresh=true to bypass cache
    - Returns detailed analysis with scenarios, recommendations, and data sources
    """
    symbol = symbol.upper().strip()
    
    if not symbol or len(symbol) > 10:
        raise HTTPException(status_code=400, detail="Invalid symbol")
    
    # Get AI settings
    ai_settings = get_ai_settings(db)
    
    if not ai_settings.ai_enabled:
        return AnalysisErrorResponse(
            error="AI analysis is currently disabled. Enable it in Admin settings.",
            error_type="configuration",
            symbol=symbol
        )
    
    # Check cache first (unless force refresh)
    if not force_refresh and ai_settings.cache_enabled:
        cached = get_cached_analysis(db, symbol)
        if cached:
            return cached
    
    # Generate new analysis
    result = await analyze_stock_safe(symbol, ai_settings.active_provider)
    
    # Check if it's an error
    if 'error' in result:
        return AnalysisErrorResponse(**result)
    
    # Cache successful result to database
    if ai_settings.cache_enabled:
        cache_analysis(db, symbol, result, ai_settings.cache_ttl_seconds)
    
    return result


@router.get("/settings", response_model=AISettingsResponse)
async def get_ai_settings_endpoint(db: Session = Depends(get_db)):
    """Get current AI analysis settings."""
    settings = get_ai_settings(db)
    providers = get_available_providers()
    
    return AISettingsResponse(
        ai_enabled=settings.ai_enabled,
        active_provider=settings.active_provider,
        cache_enabled=settings.cache_enabled,
        cache_ttl_seconds=settings.cache_ttl_seconds,
        available_providers=providers,
        updated_at=to_market_iso(settings.updated_at)
    )


@router.put("/settings", response_model=AISettingsResponse)
async def update_ai_settings_endpoint(
    update: AISettingsUpdate,
    db: Session = Depends(get_db)
):
    """Update AI analysis settings (admin only in production)."""
    settings = get_ai_settings(db)
    
    if update.ai_enabled is not None:
        settings.ai_enabled = update.ai_enabled
    if update.active_provider is not None:
        if update.active_provider not in ['gemini', 'groq', 'openai']:
            raise HTTPException(status_code=400, detail="Invalid provider. Must be: gemini, groq, or openai")
        settings.active_provider = update.active_provider
    if update.cache_enabled is not None:
        settings.cache_enabled = update.cache_enabled
    if update.cache_ttl_seconds is not None:
        if update.cache_ttl_seconds < 0:
            raise HTTPException(status_code=400, detail="Cache TTL must be non-negative")
        settings.cache_ttl_seconds = update.cache_ttl_seconds
    
    db.commit()
    db.refresh(settings)
    
    providers = get_available_providers()
    
    return AISettingsResponse(
        ai_enabled=settings.ai_enabled,
        active_provider=settings.active_provider,
        cache_enabled=settings.cache_enabled,
        cache_ttl_seconds=settings.cache_ttl_seconds,
        available_providers=providers,
        updated_at=to_market_iso(settings.updated_at)
    )
