"""
Breakout Scanner admin API endpoints.
- Portions generated by AI

Admin-only endpoints to manage the scan universe + config, trigger a scan
(background job), and read the latest ranked results.
"""

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, BackgroundTasks, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ...core.config import get_settings
from ...core.database import get_db
from ...core.deps import get_current_admin
from ...models import BreakoutScannerSettings, BreakoutScanResult, User
from ...modules.breakout_scanner.integration import (
    ensure_schema,
    get_or_create_settings,
    reset_if_stale,
    reset_status,
    run_and_publish,
)

router = APIRouter()


# ----------------------------- Schemas ----------------------------- #
class BreakoutSettingsResponse(BaseModel):
    enabled: bool
    universe: List[str]
    top_n: int
    deep_dive_n: int
    use_unusual_whales: bool
    weights: Dict[str, float]
    min_price: float
    max_price: float
    min_avg_volume: int
    require_above_sma200: bool
    typical_csp_dte: int
    last_run_at: Optional[str] = None
    last_run_status: str
    last_run_message: Optional[str] = None
    market_context: Dict[str, Any] = {}
    updated_at: Optional[str] = None
    unusual_whales_configured: bool


class BreakoutSettingsUpdate(BaseModel):
    enabled: Optional[bool] = None
    universe: Optional[List[str]] = None
    top_n: Optional[int] = None
    deep_dive_n: Optional[int] = None
    use_unusual_whales: Optional[bool] = None
    weights: Optional[Dict[str, float]] = None
    min_price: Optional[float] = None
    max_price: Optional[float] = None
    min_avg_volume: Optional[int] = None
    require_above_sma200: Optional[bool] = None
    typical_csp_dte: Optional[int] = None


class BreakoutRunResponse(BaseModel):
    status: str
    message: str


# ----------------------------- Helpers ----------------------------- #
def _settings_response(settings: BreakoutScannerSettings) -> BreakoutSettingsResponse:
    data = settings.to_dict()
    return BreakoutSettingsResponse(
        **data,
        unusual_whales_configured=bool(get_settings().UNUSUAL_WHALES_API_KEY),
    )


# ----------------------------- Endpoints ----------------------------- #
@router.get("", response_model=BreakoutSettingsResponse)
@router.get("/", response_model=BreakoutSettingsResponse)
async def get_breakout_settings(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db),
):
    """Get breakout scanner settings + last-run status (admin only)."""
    settings = get_or_create_settings(db)
    reset_if_stale(db, settings)
    return _settings_response(settings)


@router.put("", response_model=BreakoutSettingsResponse)
@router.put("/", response_model=BreakoutSettingsResponse)
async def update_breakout_settings(
    data: BreakoutSettingsUpdate,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db),
):
    """Update scan universe and config (admin only)."""
    import json

    settings = get_or_create_settings(db)
    update = data.model_dump(exclude_unset=True)

    for field, value in update.items():
        if field == "universe" and value is not None:
            cleaned = ",".join(s.strip().upper() for s in value if s and s.strip())
            settings.universe = cleaned
        elif field == "weights" and value is not None:
            settings.weights = json.dumps(value)
        else:
            setattr(settings, field, value)

    db.commit()
    db.refresh(settings)
    return _settings_response(settings)


@router.post("/run", response_model=BreakoutRunResponse)
async def run_breakout_scan(
    background_tasks: BackgroundTasks,
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db),
):
    """Trigger a scan as a background job (admin only)."""
    settings = get_or_create_settings(db)
    reset_if_stale(db, settings)

    if settings.last_run_status == "running":
        return BreakoutRunResponse(status="running", message="A scan is already in progress")

    if not settings.get_universe_list():
        return BreakoutRunResponse(status="error", message="Scan universe is empty. Add tickers first.")

    # Mark running immediately so the UI reflects state before the job starts
    settings.last_run_status = "running"
    settings.last_run_message = "Scan queued..."
    db.commit()

    background_tasks.add_task(run_and_publish)
    return BreakoutRunResponse(status="running", message="Scan started")


@router.post("/reset", response_model=BreakoutSettingsResponse)
async def reset_breakout_status(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db),
):
    """Force the scan status back to idle (clears a stuck 'running' state)."""
    settings = reset_status(db, message="Status reset by admin")
    return _settings_response(settings)


@router.get("/results")
async def get_breakout_results(
    admin: User = Depends(get_current_admin),
    db: Session = Depends(get_db),
):
    """Get the latest ranked scan results (admin only)."""
    ensure_schema()
    rows = (
        db.query(BreakoutScanResult)
        .order_by(BreakoutScanResult.run_at.desc(), BreakoutScanResult.rank.asc())
        .limit(100)
        .all()
    )
    return {"results": [r.to_dict() for r in rows]}
