"""
Daily candle chart endpoint
- Portions generated by AI
"""

import asyncio

from fastapi import APIRouter, Depends, HTTPException

from ...core.cache import get_cached_candles, set_cached_candles
from ...core.deps import get_current_user_optional
from ...models import User
from ...schemas.candles import CandlesResponse
from ...services.data_fetcher import fetch_candles_with_indicators

router = APIRouter()


@router.get("/candles/{symbol}", response_model=CandlesResponse)
async def get_candles(
    symbol: str,
    user: User = Depends(get_current_user_optional),
):
    """Daily OHLCV candles (~5y + SMA-200 warm-up) with SMA/EMA overlays."""
    normalized = (symbol or "").upper().strip()
    if not normalized or len(normalized) > 10:
        raise HTTPException(status_code=422, detail="Invalid symbol")

    cached = get_cached_candles(normalized)
    if cached is not None:
        return cached

    data = await asyncio.to_thread(fetch_candles_with_indicators, normalized)
    if not data.get("candles"):
        raise HTTPException(status_code=404, detail=f"No price history for {normalized}")

    set_cached_candles(normalized, data)
    return data
