"""
Flow & Positioning direction endpoint
- Portions generated by AI
"""

import asyncio
import logging
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException

from ...core.cache import (
    DIRECTION_TTL_SECONDS,
    get_cached_direction_bundle,
    set_cached_direction_bundle,
)
from ...core.deps import get_current_user_optional
from ...core.market_clock import to_market_iso
from ...models import User
from ...schemas.direction import DirectionResponse
from ...services.direction import (
    DirectionUnavailable,
    fetch_direction_bundle,
    score_direction,
)
from ...modules.breakout_scanner.uw_signals import _f

logger = logging.getLogger(__name__)

router = APIRouter()


def _spot_from_bundle(bundle: dict) -> Optional[float]:
    """Fall back to the close price UW already returns with max-pain data."""
    payload: Any = bundle.get("max_pain")
    rows = payload.get("data") if isinstance(payload, dict) else payload
    if isinstance(rows, list):
        for row in rows:
            if isinstance(row, dict):
                close = _f(row.get("close"))
                if close and close > 0:
                    return close
    return None


@router.get("/prediction/{symbol}", response_model=DirectionResponse)
async def get_direction(
    symbol: str,
    expiry: Optional[str] = None,
    strike: Optional[float] = None,
    spot: Optional[float] = None,
    force_refresh: bool = False,
    user: User = Depends(get_current_user_optional),
):
    """Directional bias for a ticker from Unusual Whales positioning data.

    The raw provider bundle is cached per symbol; scoring is recomputed per
    request so each option contract gets an expiry- and strike-aware read
    without refetching.
    """
    normalized = (symbol or "").upper().strip()
    if not normalized or len(normalized) > 10:
        raise HTTPException(status_code=422, detail="Invalid symbol")

    bundle = None if force_refresh else get_cached_direction_bundle(normalized)
    cached = bundle is not None

    if bundle is None:
        try:
            bundle = await asyncio.to_thread(fetch_direction_bundle, normalized)
        except DirectionUnavailable as e:
            raise HTTPException(status_code=503, detail=str(e))
        except Exception as e:
            logger.warning(f"Direction fetch failed for {normalized}: {e}")
            raise HTTPException(status_code=502, detail="Unusual Whales data unavailable")

        set_cached_direction_bundle(normalized, bundle)

    result = score_direction(
        bundle,
        spot=spot or _spot_from_bundle(bundle),
        expiry=expiry,
        strike=strike,
    )

    # Empty envelopes still parse, so the real test for an unknown or uncovered
    # ticker is whether any signal produced a usable value.
    if result["coverage"] <= 0:
        raise HTTPException(status_code=404, detail=f"No positioning data for {normalized}")

    fetched_at = bundle.get("fetched_at")
    if fetched_at:
        try:
            stamp = datetime.fromisoformat(fetched_at)
            result["cached_at"] = to_market_iso(stamp) if cached else None
            result["expires_at"] = to_market_iso(stamp + timedelta(seconds=DIRECTION_TTL_SECONDS))
        except ValueError:
            pass

    return result
