"""
Health check endpoint
- Portions generated by AI
"""

from fastapi import APIRouter
from sqlalchemy import text

from ...core.config import get_settings
from ...core.database import engine
from ...core.market_clock import to_market_iso, market_now

router = APIRouter()
settings = get_settings()


@router.get("/health")
async def health_check():
    """
    Health check endpoint.
    Returns status of the application and its dependencies.
    """
    # Check database connection
    db_status = "not configured"
    try:
        if engine:
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            db_status = "connected"
    except Exception as e:
        db_status = f"error: {str(e)}"
    
    return {
        "status": "ok",
        "timestamp": to_market_iso(market_now()),
        "version": settings.APP_VERSION,
        "database": db_status,
        "massive_api": "configured" if settings.MASSIVE_API_KEY else "not configured",
        "alpaca_api": "configured" if settings.ALPACA_API_KEY and settings.ALPACA_SECRET_KEY else "not configured",
        "auth": "clerk" if settings.CLERK_SECRET_KEY else "dev_mode"
    }
