"""
Trade Idea API endpoints
- Portions generated by AI
"""

from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from ...core.database import get_db
from ...core.deps import get_current_user, get_current_user_optional, is_admin
from ...models import User, TradeIdea
from ...schemas.trade_idea import (
    TradeIdeaCreate,
    TradeIdeaUpdate,
    TradeIdeaResponse,
    TradeIdeaListResponse,
)

router = APIRouter()

# Maximum user trade ideas allowed
MAX_USER_TRADE_IDEAS = 10


def _trade_idea_to_response(idea: TradeIdea) -> TradeIdeaResponse:
    """Convert TradeIdea model to response schema"""
    return TradeIdeaResponse(
        id=idea.id,
        name=idea.name,
        description=idea.description,
        is_system=idea.is_system,
        is_default=idea.is_default,
        user_id=idea.user_id,
        symbols=idea.get_symbols_list(),
        created_at=idea.created_at,
        updated_at=idea.updated_at,
    )


@router.get("/trade-ideas", response_model=TradeIdeaListResponse)
async def list_trade_ideas(
    user: User = Depends(get_current_user_optional),
    db: Session = Depends(get_db)
):
    """
    List all trade ideas available to the user.
    Returns system trade ideas + user's own trade ideas.
    """
    # Get all system trade ideas
    system_ideas = db.query(TradeIdea).filter(TradeIdea.is_system == True).all()
    
    # Get user's trade ideas if authenticated
    user_ideas = []
    if user:
        user_ideas = db.query(TradeIdea).filter(
            TradeIdea.is_system == False,
            TradeIdea.user_id == user.id
        ).all()
    
    # Find default trade idea ID
    default_idea = next((i for i in system_ideas if i.is_default), None)
    default_idea_id = default_idea.id if default_idea else None
    
    return TradeIdeaListResponse(
        system_trade_ideas=[_trade_idea_to_response(i) for i in system_ideas],
        user_trade_ideas=[_trade_idea_to_response(i) for i in user_ideas],
        default_trade_idea_id=default_idea_id,
    )


@router.get("/trade-ideas/{idea_id}", response_model=TradeIdeaResponse)
async def get_trade_idea(
    idea_id: str,
    user: User = Depends(get_current_user_optional),
    db: Session = Depends(get_db)
):
    """Get a specific trade idea by ID."""
    idea = db.query(TradeIdea).filter(TradeIdea.id == idea_id).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="Trade idea not found")
    
    # Check access: system ideas are public, user ideas are private
    if not idea.is_system and (not user or idea.user_id != user.id):
        raise HTTPException(status_code=403, detail="Access denied")
    
    return _trade_idea_to_response(idea)


@router.post("/trade-ideas", response_model=TradeIdeaResponse)
async def create_trade_idea(
    idea_data: TradeIdeaCreate,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a new user trade idea.
    Users can create up to 10 trade ideas.
    """
    # Check user trade idea limit
    user_idea_count = db.query(TradeIdea).filter(
        TradeIdea.is_system == False,
        TradeIdea.user_id == user.id
    ).count()
    
    if user_idea_count >= MAX_USER_TRADE_IDEAS:
        raise HTTPException(
            status_code=400,
            detail=f"Maximum of {MAX_USER_TRADE_IDEAS} user trade ideas allowed"
        )
    
    # Create trade idea
    new_idea = TradeIdea(
        name=idea_data.name,
        description=idea_data.description,
        is_system=False,
        is_default=False,
        user_id=user.id,
        symbols=",".join(idea_data.symbols),
    )
    
    db.add(new_idea)
    db.commit()
    db.refresh(new_idea)
    
    return _trade_idea_to_response(new_idea)


@router.put("/trade-ideas/{idea_id}", response_model=TradeIdeaResponse)
async def update_trade_idea(
    idea_id: str,
    idea_data: TradeIdeaUpdate,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Update an existing user trade idea.
    Users can only update their own trade ideas.
    """
    idea = db.query(TradeIdea).filter(TradeIdea.id == idea_id).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="Trade idea not found")
    
    # Only allow updating own trade ideas (not system ideas)
    if idea.is_system:
        raise HTTPException(status_code=403, detail="Cannot modify system trade ideas")
    
    if idea.user_id != user.id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    # Update fields
    update_data = idea_data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        if field == "symbols" and value is not None:
            idea.symbols = ",".join(value)
        else:
            setattr(idea, field, value)
    
    db.commit()
    db.refresh(idea)
    
    return _trade_idea_to_response(idea)


@router.delete("/trade-ideas/{idea_id}")
async def delete_trade_idea(
    idea_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Delete a user trade idea.
    Users can only delete their own trade ideas.
    """
    idea = db.query(TradeIdea).filter(TradeIdea.id == idea_id).first()
    
    if not idea:
        raise HTTPException(status_code=404, detail="Trade idea not found")
    
    # Only allow deleting own trade ideas (not system ideas)
    if idea.is_system:
        raise HTTPException(status_code=403, detail="Cannot delete system trade ideas")
    
    if idea.user_id != user.id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    db.delete(idea)
    db.commit()
    
    return {"message": "Trade idea deleted successfully"}
