/**
 * Hook to sync authentication and settings with backend
 * - Portions generated by AI
 */

import { useEffect, useCallback, useState, useRef } from 'react';
import { useAuth, useUser } from '@clerk/clerk-react';
import { useAppStore } from '@/stores/useAppStore';
import { setAuthTokenGetter } from '@/api/client';
import apiClient from '@/api/client';

// Check if Clerk is configured
const CLERK_ENABLED = !!import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;

export function useAuthSync() {
  // Only use Clerk hooks if enabled
  if (!CLERK_ENABLED) {
    return { isLoading: false, syncSettings: () => {}, isSettingsSynced: true };
  }

  return useAuthSyncWithClerk();
}

function useAuthSyncWithClerk() {
  const { getToken, isLoaded, isSignedIn } = useAuth();
  const { user } = useUser();
  const { replaceSettings } = useAppStore();
  
  // Track if token getter is ready and if settings have been synced
  const [isTokenReady, setIsTokenReady] = useState(false);
  const [isSettingsSynced, setIsSettingsSynced] = useState(false);
  
  // Track if we've already synced for this session to avoid duplicate syncs
  const hasSyncedRef = useRef(false);

  // Set up the token getter for the API client FIRST
  useEffect(() => {
    if (isLoaded && isSignedIn) {
      console.log('[AuthSync] Setting up token getter...');
      setAuthTokenGetter(async () => {
        try {
          const token = await getToken();
          return token;
        } catch (e) {
          console.error('[AuthSync] Error getting token:', e);
          return null;
        }
      });
      // Mark token as ready after setting the getter
      setIsTokenReady(true);
      console.log('[AuthSync] Token getter ready');
    } else if (isLoaded && !isSignedIn) {
      // User logged out - reset state
      setIsTokenReady(false);
      setIsSettingsSynced(false);
      hasSyncedRef.current = false;
      console.log('[AuthSync] User signed out, reset state');
    }
  }, [isLoaded, isSignedIn, getToken]);

  // Sync settings from backend when user signs in
  // This REPLACES local/browser settings with backend settings (or system defaults)
  const syncSettings = useCallback(async () => {
    console.log('[AuthSync] syncSettings called, isSignedIn:', isSignedIn);
    if (!isSignedIn) return;

    try {
      console.log('[AuthSync] Fetching settings from backend...');
      const settings = await apiClient.getSettings();
      console.log('[AuthSync] Settings received from backend:', settings);
      
      // Fully replace browser settings with backend settings
      replaceSettings(settings);
      setIsSettingsSynced(true);
      console.log('[AuthSync] Settings applied to store');
    } catch (error) {
      console.error('[AuthSync] Error syncing settings from backend:', error);
      // Keep local settings if backend fetch fails
      setIsSettingsSynced(true); // Mark as synced to prevent retry loop
    }
  }, [isSignedIn, replaceSettings]);

  // Auto-sync settings AFTER token is ready
  // This effect only runs when isTokenReady becomes true
  useEffect(() => {
    if (isLoaded && isSignedIn && isTokenReady && !hasSyncedRef.current) {
      console.log('[AuthSync] Token ready, triggering settings sync...');
      hasSyncedRef.current = true;
      syncSettings();
    }
  }, [isLoaded, isSignedIn, isTokenReady, syncSettings]);

  return {
    isLoading: !isLoaded,
    syncSettings,
    user,
    isSignedIn,
    isSettingsSynced,
  };
}

/**
 * Hook to save settings to backend
 */
export function useSaveSettings() {
  const { isSignedIn } = CLERK_ENABLED ? useAuth() : { isSignedIn: false };
  const { settings } = useAppStore();

  const saveToBackend = useCallback(async () => {
    console.log('[SaveSettings] saveToBackend called, isSignedIn:', isSignedIn);
    console.log('[SaveSettings] Settings to save:', settings);
    
    if (!CLERK_ENABLED || !isSignedIn) {
      // In dev mode, just save locally (already done by store)
      console.log('[SaveSettings] Clerk not enabled or not signed in, skipping backend save');
      return true;
    }

    try {
      const result = await apiClient.updateSettings(settings);
      console.log('[SaveSettings] Settings saved successfully:', result);
      return true;
    } catch (error) {
      console.error('[SaveSettings] Error saving settings to backend:', error);
      return false;
    }
  }, [isSignedIn, settings]);

  return { saveToBackend };
}
