/**
 * Hook for loading and managing filters and trade ideas
 * - Portions generated by AI
 */

import { useCallback } from 'react';
import { useAppStore } from '@/stores/useAppStore';
import { apiClient } from '@/api/client';
import type { Filter, TradeIdea, FilterCreateRequest, TradeIdeaCreateRequest } from '@/types';

export function useFiltersAndIdeas() {
  const {
    // Filters state
    systemFilters,
    userFilters,
    selectedFilter,
    defaultFilterId,
    setFilters,
    selectFilter,
    addUserFilter,
    updateUserFilter,
    removeUserFilter,
    filtersLoading,
    setFiltersLoading,

    // Trade Ideas state
    systemTradeIdeas,
    userTradeIdeas,
    selectedTradeIdea,
    defaultTradeIdeaId,
    setTradeIdeas,
    selectTradeIdea,
    addUserTradeIdea,
    updateUserTradeIdea,
    removeUserTradeIdea,
    tradeIdeasLoading,
    setTradeIdeasLoading,
  } = useAppStore();

  // Load filters from API
  const loadFilters = useCallback(async () => {
    setFiltersLoading(true);
    try {
      const response = await apiClient.getFilters();
      setFilters(
        response.system_filters,
        response.user_filters,
        response.default_filter_id || null
      );

      // Auto-select default filter if none selected
      if (!selectedFilter) {
        const defaultFilter =
          response.system_filters.find((f) => f.is_default) ||
          response.system_filters[0];
        if (defaultFilter) {
          selectFilter(defaultFilter);
        }
      }
    } catch (error) {
      console.error('Failed to load filters:', error);
    } finally {
      setFiltersLoading(false);
    }
  }, [setFilters, setFiltersLoading, selectedFilter, selectFilter]);

  // Load trade ideas from API
  const loadTradeIdeas = useCallback(async () => {
    setTradeIdeasLoading(true);
    try {
      const response = await apiClient.getTradeIdeas();
      setTradeIdeas(
        response.system_trade_ideas,
        response.user_trade_ideas,
        response.default_trade_idea_id || null
      );

      // Auto-select default trade idea if none selected
      if (!selectedTradeIdea) {
        const defaultIdea =
          response.system_trade_ideas.find((i) => i.is_default) ||
          response.system_trade_ideas[0];
        if (defaultIdea) {
          selectTradeIdea(defaultIdea);
        }
      }
    } catch (error) {
      console.error('Failed to load trade ideas:', error);
    } finally {
      setTradeIdeasLoading(false);
    }
  }, [setTradeIdeas, setTradeIdeasLoading, selectedTradeIdea, selectTradeIdea]);

  // Create a new user filter
  const createFilter = useCallback(
    async (data: FilterCreateRequest): Promise<Filter | null> => {
      try {
        const newFilter = await apiClient.createFilter(data);
        addUserFilter(newFilter);
        selectFilter(newFilter);
        // Persist selection to backend
        await apiClient.updateSettings({ selected_filter_id: newFilter.id });
        return newFilter;
      } catch (error) {
        console.error('Failed to create filter:', error);
        throw error;
      }
    },
    [addUserFilter, selectFilter]
  );

  // Update a user filter
  const editFilter = useCallback(
    async (filterId: string, data: Partial<FilterCreateRequest>): Promise<Filter | null> => {
      try {
        const updatedFilter = await apiClient.updateFilter(filterId, data);
        updateUserFilter(updatedFilter);
        return updatedFilter;
      } catch (error) {
        console.error('Failed to update filter:', error);
        throw error;
      }
    },
    [updateUserFilter]
  );

  // Delete a user filter
  const deleteFilter = useCallback(
    async (filterId: string): Promise<void> => {
      try {
        await apiClient.deleteFilter(filterId);
        removeUserFilter(filterId);

        // If deleted filter was selected, select default
        if (selectedFilter?.id === filterId) {
          const defaultFilter =
            systemFilters.find((f) => f.is_default) || systemFilters[0];
          if (defaultFilter) {
            selectFilter(defaultFilter);
            await apiClient.updateSettings({ selected_filter_id: defaultFilter.id });
          }
        }
      } catch (error) {
        console.error('Failed to delete filter:', error);
        throw error;
      }
    },
    [removeUserFilter, selectedFilter, systemFilters, selectFilter]
  );

  // Create a new user trade idea
  const createTradeIdea = useCallback(
    async (data: TradeIdeaCreateRequest): Promise<TradeIdea | null> => {
      try {
        const newIdea = await apiClient.createTradeIdea(data);
        addUserTradeIdea(newIdea);
        selectTradeIdea(newIdea);
        // Persist selection to backend
        await apiClient.updateSettings({ selected_trade_idea_id: newIdea.id });
        return newIdea;
      } catch (error) {
        console.error('Failed to create trade idea:', error);
        throw error;
      }
    },
    [addUserTradeIdea, selectTradeIdea]
  );

  // Update a user trade idea
  const editTradeIdea = useCallback(
    async (ideaId: string, data: Partial<TradeIdeaCreateRequest>): Promise<TradeIdea | null> => {
      try {
        const updatedIdea = await apiClient.updateTradeIdea(ideaId, data);
        updateUserTradeIdea(updatedIdea);
        return updatedIdea;
      } catch (error) {
        console.error('Failed to update trade idea:', error);
        throw error;
      }
    },
    [updateUserTradeIdea]
  );

  // Delete a user trade idea
  const deleteTradeIdea = useCallback(
    async (ideaId: string): Promise<void> => {
      try {
        await apiClient.deleteTradeIdea(ideaId);
        removeUserTradeIdea(ideaId);

        // If deleted idea was selected, select default
        if (selectedTradeIdea?.id === ideaId) {
          const defaultIdea =
            systemTradeIdeas.find((i) => i.is_default) || systemTradeIdeas[0];
          if (defaultIdea) {
            selectTradeIdea(defaultIdea);
            await apiClient.updateSettings({ selected_trade_idea_id: defaultIdea.id });
          }
        }
      } catch (error) {
        console.error('Failed to delete trade idea:', error);
        throw error;
      }
    },
    [removeUserTradeIdea, selectedTradeIdea, systemTradeIdeas, selectTradeIdea]
  );

  // Handle filter selection with backend sync
  const handleSelectFilter = useCallback(
    async (filter: Filter) => {
      selectFilter(filter);
      try {
        await apiClient.updateSettings({ selected_filter_id: filter.id });
      } catch (error) {
        console.error('Failed to persist filter selection:', error);
      }
    },
    [selectFilter]
  );

  // Handle trade idea selection with backend sync
  const handleSelectTradeIdea = useCallback(
    async (idea: TradeIdea) => {
      selectTradeIdea(idea);
      try {
        await apiClient.updateSettings({ selected_trade_idea_id: idea.id });
      } catch (error) {
        console.error('Failed to persist trade idea selection:', error);
      }
    },
    [selectTradeIdea]
  );

  return {
    // Filters
    systemFilters,
    userFilters,
    allFilters: [...systemFilters, ...userFilters],
    selectedFilter,
    defaultFilterId,
    filtersLoading,
    loadFilters,
    createFilter,
    editFilter,
    deleteFilter,
    handleSelectFilter,

    // Trade Ideas
    systemTradeIdeas,
    userTradeIdeas,
    allTradeIdeas: [...systemTradeIdeas, ...userTradeIdeas],
    selectedTradeIdea,
    defaultTradeIdeaId,
    tradeIdeasLoading,
    loadTradeIdeas,
    createTradeIdea,
    editTradeIdea,
    deleteTradeIdea,
    handleSelectTradeIdea,
  };
}

export default useFiltersAndIdeas;
