"""
Tests for market-data caching
- Portions generated by AI
"""

from datetime import datetime, timedelta

from app.core import cache as cache_mod
from app.core.cache import (
    InMemoryCache,
    _options_key,
    _price_key,
    _news_key,
    get_cached_options_chain,
    set_cached_options_chain,
    get_cached_stock_price,
    set_cached_stock_price,
    get_cached_news,
    set_cached_news,
    get_cached_indicators,
    set_cached_indicators,
    clear_app_cache,
)


def setup_function():
    cache_mod._cache_instance = InMemoryCache()
    cache_mod._cache_settings = {
        "cache_enabled": True,
        "ttl_stock_price": 180,
        "ttl_options_chain": 300,
        "ttl_news": 900,
        "ttl_event_dates": 604800,
    }


def teardown_function():
    cache_mod._cache_instance = None


def test_options_key_shared_across_screening_filters():
    """Volume/OI/probability must not split the raw chain cache."""
    conservative = _options_key("AAPL", "alpaca", 15, 45, True)
    aggressive_same_dte = _options_key("AAPL", "alpaca", 15, 45, True)
    different_dte = _options_key("AAPL", "alpaca", 3, 14, True)
    different_provider = _options_key("AAPL", "massive", 15, 45, True)
    different_midpoint = _options_key("AAPL", "alpaca", 15, 45, False)

    assert conservative == aggressive_same_dte
    assert conservative != different_dte
    assert conservative != different_provider
    assert conservative != different_midpoint


def test_price_and_news_keys_are_provider_specific():
    assert _price_key("aapl", "alpaca", True) != _price_key("AAPL", "massive", True)
    assert _price_key("AAPL", "alpaca", True) != _price_key("AAPL", "alpaca", False)
    assert _price_key("aapl", "alpaca", True) == _price_key("AAPL", "alpaca", True)
    assert _news_key("MSFT", "alpaca", 7, 10) != _news_key("MSFT", "massive", 7, 10)
    assert _news_key("MSFT", "alpaca", 7, 10) != _news_key("MSFT", "alpaca", 7, 20)


def test_options_chain_round_trip_ignores_symbol_case():
    chain = [{"strike": 100, "lastPrice": 1.5}]
    set_cached_options_chain("aapl", chain, "massive", 15, 45, False)
    hit = get_cached_options_chain("AAPL", "massive", 15, 45, False)
    miss = get_cached_options_chain("AAPL", "massive", 7, 21, False)
    assert hit == chain
    assert miss is None


def test_price_and_news_round_trip():
    set_cached_stock_price("MSFT", {"price": 400.0}, "alpaca", True)
    assert get_cached_stock_price("MSFT", "alpaca", True)["price"] == 400.0
    assert get_cached_stock_price("MSFT", "massive", True) is None

    set_cached_news("NVDA", [{"title": "hi"}], "massive", 7, 10)
    assert get_cached_news("NVDA", "massive", 7, 10) == [{"title": "hi"}]
    assert get_cached_news("NVDA", "alpaca", 7, 10) is None


def test_in_memory_cache_evicts_expired_on_set():
    mem = InMemoryCache()
    mem._cache["stale"] = ("old", datetime.now() - timedelta(seconds=1))
    mem.set("fresh", "new", ex=60)
    assert "stale" not in mem._cache
    assert mem.get("fresh") == "new"


def test_indicators_are_keyed_by_market_session():
    payload = {"sma_20": 1.0, "sma_50": 2.0, "sma_200": 3.0, "rsi_14": 40.0}
    set_cached_indicators("aapl", payload, "2026-08-15")
    assert get_cached_indicators("AAPL", "2026-08-15") == payload
    assert get_cached_indicators("AAPL", "2026-08-16") is None


def test_clear_app_cache_only_drops_app_prefixes():
    cache = cache_mod.get_cache()
    cache.set("price:AAPL:massive:0", "1", ex=60)
    cache.set("unrelated:keep", "2", ex=60)
    deleted = clear_app_cache()
    assert deleted >= 1
    assert cache.get("price:AAPL:massive:0") is None
    assert cache.get("unrelated:keep") == "2"


def test_analysis_cache_rejects_other_llm_provider(db):
    from app.api.v1.analyze import cache_analysis, get_cached_analysis

    cache_analysis(db, "AAPL", {"summary": "gemini take", "llm_provider": "gemini"}, 86400)
    hit = get_cached_analysis(db, "AAPL", "gemini")
    miss = get_cached_analysis(db, "AAPL", "groq")
    assert hit is not None
    assert hit["summary"] == "gemini take"
    assert miss is None
