"""
Tests for Trade Ideas API endpoints
- Portions generated by AI
"""

import pytest
from fastapi.testclient import TestClient


class TestTradeIdeasAPI:
    """Tests for the trade ideas API"""

    def test_list_trade_ideas_empty(self, client: TestClient):
        """Test listing trade ideas when none exist"""
        response = client.get("/api/v1/trade-ideas")
        assert response.status_code == 200
        data = response.json()
        assert "system_trade_ideas" in data
        assert "user_trade_ideas" in data
        assert data["system_trade_ideas"] == []
        assert data["user_trade_ideas"] == []

    def test_create_user_trade_idea(self, client: TestClient, auth_headers):
        """Test creating a user trade idea"""
        idea_data = {
            "name": "My Watchlist",
            "description": "My favorite stocks",
            "symbols": ["AAPL", "MSFT", "GOOGL"],
        }
        response = client.post(
            "/api/v1/trade-ideas",
            json=idea_data,
            headers=auth_headers,
        )
        assert response.status_code == 200
        data = response.json()
        assert data["name"] == "My Watchlist"
        assert data["description"] == "My favorite stocks"
        assert data["is_system"] == False
        assert data["symbols"] == ["AAPL", "MSFT", "GOOGL"]

    def test_create_trade_idea_no_name(self, client: TestClient, auth_headers):
        """Test creating a trade idea without a name fails"""
        idea_data = {
            "symbols": ["AAPL", "MSFT"],
        }
        response = client.post(
            "/api/v1/trade-ideas",
            json=idea_data,
            headers=auth_headers,
        )
        assert response.status_code == 422  # Validation error

    def test_create_trade_idea_limit(self, client: TestClient, auth_headers):
        """Test that user cannot create more than 10 trade ideas"""
        # Create 10 trade ideas
        for i in range(10):
            idea_data = {
                "name": f"Idea {i}",
                "symbols": ["AAPL"],
            }
            response = client.post(
                "/api/v1/trade-ideas",
                json=idea_data,
                headers=auth_headers,
            )
            assert response.status_code == 200

        # 11th trade idea should fail
        idea_data = {
            "name": "Idea 10",
            "symbols": ["AAPL"],
        }
        response = client.post(
            "/api/v1/trade-ideas",
            json=idea_data,
            headers=auth_headers,
        )
        assert response.status_code == 400
        assert "Maximum of 10" in response.json()["detail"]

    def test_update_user_trade_idea(self, client: TestClient, auth_headers):
        """Test updating a user trade idea"""
        # Create trade idea
        idea_data = {
            "name": "Original",
            "symbols": ["AAPL"],
        }
        create_response = client.post(
            "/api/v1/trade-ideas",
            json=idea_data,
            headers=auth_headers,
        )
        idea_id = create_response.json()["id"]

        # Update trade idea
        update_data = {
            "name": "Updated",
            "symbols": ["AAPL", "MSFT", "GOOGL"],
        }
        update_response = client.put(
            f"/api/v1/trade-ideas/{idea_id}",
            json=update_data,
            headers=auth_headers,
        )
        assert update_response.status_code == 200
        data = update_response.json()
        assert data["name"] == "Updated"
        assert data["symbols"] == ["AAPL", "MSFT", "GOOGL"]

    def test_delete_user_trade_idea(self, client: TestClient, auth_headers):
        """Test deleting a user trade idea"""
        # Create trade idea
        idea_data = {
            "name": "To Delete",
            "symbols": ["AAPL"],
        }
        create_response = client.post(
            "/api/v1/trade-ideas",
            json=idea_data,
            headers=auth_headers,
        )
        idea_id = create_response.json()["id"]

        # Delete trade idea
        delete_response = client.delete(
            f"/api/v1/trade-ideas/{idea_id}",
            headers=auth_headers,
        )
        assert delete_response.status_code == 200

        # Verify deleted
        get_response = client.get(
            f"/api/v1/trade-ideas/{idea_id}",
            headers=auth_headers,
        )
        assert get_response.status_code == 404

    def test_get_trade_idea_not_found(self, client: TestClient):
        """Test getting a non-existent trade idea"""
        response = client.get("/api/v1/trade-ideas/nonexistent-id")
        assert response.status_code == 404
