"""
Tests for options screening filters
- Portions generated by AI
"""

import pandas as pd

from app.services.options_screener import screen_options
from app.models.filter import Filter


def _config(max_assignment_probability: int = 20, min_volume: int = 10, min_open_interest: int = 10):
    return {
        "options_strategy": {
            "max_dte": 45,
            "min_dte": 15,
            "min_volume": min_volume,
            "min_open_interest": min_open_interest,
        },
        "screening_criteria": {
            "min_annualized_return": 50.0,
            "max_assignment_probability": max_assignment_probability,
        },
        "output": {
            "sort_by": ["annualized_return"],
            "sort_order": "descending",
            "max_results": 50,
        },
    }


def test_screen_options_keeps_low_annualized_returns():
    """Annualized return is ranked, not used as a cutoff."""
    options = pd.DataFrame({
        "open_interest": [100, 100],
        "delta": [-0.10, -0.12],
        "out_of_the_money": [True, True],
        "annualized_return": [5.0, 80.0],
        "volume": [50, 50],
        "strike": [90.0, 85.0],
        "lastPrice": [1.0, 2.0],
    })

    result = screen_options(options, _config(), api_source="yahoo")

    assert len(result) == 2
    assert set(result["annualized_return"]) == {5.0, 80.0}
    assert result.iloc[0]["annualized_return"] == 80.0


def test_screen_options_still_filters_assignment_probability():
    options = pd.DataFrame({
        "open_interest": [100, 100],
        "delta": [-0.10, -0.40],
        "out_of_the_money": [True, True],
        "annualized_return": [25.0, 90.0],
        "volume": [50, 50],
        "strike": [90.0, 85.0],
        "lastPrice": [1.0, 2.0],
    })

    result = screen_options(options, _config(max_assignment_probability=20), api_source="yahoo")

    assert len(result) == 1
    assert result.iloc[0]["annualized_return"] == 25.0


def test_filter_auto_name_omits_return():
    name = Filter.generate_name(15, 45, 10, 10, 20)
    assert name == "DTE_15-45_VOL_10_OI_10_PROB_20"
    assert "RET_" not in name
