/**
 * API client for Put Options Screener
 * - Portions generated by AI
 */

import axios, { AxiosInstance } from 'axios';
import type { 
  UserSettings, 
  UserInfo, 
  ScreenRequest, 
  ScreenResponse, 
  NewsResponse,
  HealthResponse,
  Filter,
  FilterListResponse,
  FilterCreateRequest,
  TradeIdea,
  TradeIdeaListResponse,
  TradeIdeaCreateRequest,
} from '@/types';

// Get API base URL from environment or default to relative path
const API_BASE_URL = import.meta.env.VITE_API_URL || '';

// Create axios instance
const api: AxiosInstance = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Token getter function - will be set by useAuthToken hook
let getAuthToken: (() => Promise<string | null>) | null = null;

export function setAuthTokenGetter(getter: () => Promise<string | null>) {
  getAuthToken = getter;
}

// Add auth token to requests
api.interceptors.request.use(async (config) => {
  const requestUrl = config.url || '';
  
  // Try to get token from Clerk via the getter
  if (getAuthToken) {
    try {
      const token = await getAuthToken();
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
        console.log(`[API] Request to ${requestUrl} with Clerk token`);
        return config;
      } else {
        console.log(`[API] Request to ${requestUrl} - token getter returned null`);
      }
    } catch (e) {
      console.error('[API] Error getting auth token:', e);
    }
  } else {
    console.log(`[API] Request to ${requestUrl} - no token getter set`);
  }
  
  // Fallback to localStorage (for dev mode)
  const localToken = localStorage.getItem('auth_token');
  if (localToken) {
    config.headers.Authorization = `Bearer ${localToken}`;
    console.log(`[API] Request to ${requestUrl} with localStorage token`);
  } else {
    console.log(`[API] Request to ${requestUrl} without auth token`);
  }
  return config;
});

// API functions
export const apiClient = {
  // Health check
  async getHealth(): Promise<HealthResponse> {
    const response = await api.get('/health');
    return response.data;
  },

  // Get current user info (Phase 2)
  async getMe(): Promise<UserInfo> {
    const response = await api.get('/api/v1/me');
    return response.data;
  },

  // Check if current user is admin
  async checkIsAdmin(): Promise<{ is_admin: boolean }> {
    const response = await api.get('/api/v1/me/is-admin');
    return response.data;
  },

  // Get user settings
  async getSettings(): Promise<UserSettings> {
    const response = await api.get('/api/v1/settings');
    return response.data;
  },

  // Update user settings
  async updateSettings(settings: Partial<UserSettings>): Promise<UserSettings> {
    const response = await api.put('/api/v1/settings', settings);
    return response.data;
  },

  // Screen options
  async screenOptions(request: ScreenRequest): Promise<ScreenResponse> {
    const response = await api.post('/api/v1/screen', request);
    return response.data;
  },

  // Get news for symbol
  async getNews(symbol: string, limit = 10, maxAgeDays = 7): Promise<NewsResponse> {
    const response = await api.get(`/api/v1/news/${symbol}`, {
      params: { limit, max_age_days: maxAgeDays },
    });
    return response.data;
  },

  // Test screen (no auth required)
  async testScreen(symbol: string): Promise<unknown> {
    const response = await api.get('/api/v1/test-screen', {
      params: { symbol },
    });
    return response.data;
  },

  // ============== Filters API ==============
  
  // Get all filters (system + user's)
  async getFilters(): Promise<FilterListResponse> {
    const response = await api.get('/api/v1/filters');
    return response.data;
  },

  // Get a specific filter
  async getFilter(filterId: string): Promise<Filter> {
    const response = await api.get(`/api/v1/filters/${filterId}`);
    return response.data;
  },

  // Create a new user filter
  async createFilter(filter: FilterCreateRequest): Promise<Filter> {
    const response = await api.post('/api/v1/filters', filter);
    return response.data;
  },

  // Update a user filter
  async updateFilter(filterId: string, filter: Partial<FilterCreateRequest>): Promise<Filter> {
    const response = await api.put(`/api/v1/filters/${filterId}`, filter);
    return response.data;
  },

  // Delete a user filter
  async deleteFilter(filterId: string): Promise<void> {
    await api.delete(`/api/v1/filters/${filterId}`);
  },

  // ============== Trade Ideas API ==============
  
  // Get all trade ideas (system + user's)
  async getTradeIdeas(): Promise<TradeIdeaListResponse> {
    const response = await api.get('/api/v1/trade-ideas');
    return response.data;
  },

  // Get a specific trade idea
  async getTradeIdea(ideaId: string): Promise<TradeIdea> {
    const response = await api.get(`/api/v1/trade-ideas/${ideaId}`);
    return response.data;
  },

  // Create a new user trade idea
  async createTradeIdea(idea: TradeIdeaCreateRequest): Promise<TradeIdea> {
    const response = await api.post('/api/v1/trade-ideas', idea);
    return response.data;
  },

  // Update a user trade idea
  async updateTradeIdea(ideaId: string, idea: Partial<TradeIdeaCreateRequest>): Promise<TradeIdea> {
    const response = await api.put(`/api/v1/trade-ideas/${ideaId}`, idea);
    return response.data;
  },

  // Delete a user trade idea
  async deleteTradeIdea(ideaId: string): Promise<void> {
    await api.delete(`/api/v1/trade-ideas/${ideaId}`);
  },

  // ============== Admin API ==============
  
  // Create system filter (admin only)
  async createSystemFilter(filter: FilterCreateRequest): Promise<Filter> {
    const response = await api.post('/api/v1/admin/filters', filter);
    return response.data;
  },

  // Update system filter (admin only)
  async updateSystemFilter(filterId: string, filter: Partial<FilterCreateRequest>): Promise<Filter> {
    const response = await api.put(`/api/v1/admin/filters/${filterId}`, filter);
    return response.data;
  },

  // Set default system filter (admin only)
  async setDefaultFilter(filterId: string): Promise<Filter> {
    const response = await api.put(`/api/v1/admin/filters/${filterId}/set-default`);
    return response.data;
  },

  // Delete system filter (admin only)
  async deleteSystemFilter(filterId: string): Promise<void> {
    await api.delete(`/api/v1/admin/filters/${filterId}`);
  },

  // Create system trade idea (admin only)
  async createSystemTradeIdea(idea: TradeIdeaCreateRequest): Promise<TradeIdea> {
    const response = await api.post('/api/v1/admin/trade-ideas', idea);
    return response.data;
  },

  // Update system trade idea (admin only)
  async updateSystemTradeIdea(ideaId: string, idea: Partial<TradeIdeaCreateRequest>): Promise<TradeIdea> {
    const response = await api.put(`/api/v1/admin/trade-ideas/${ideaId}`, idea);
    return response.data;
  },

  // Set default system trade idea (admin only)
  async setDefaultTradeIdea(ideaId: string): Promise<TradeIdea> {
    const response = await api.put(`/api/v1/admin/trade-ideas/${ideaId}/set-default`);
    return response.data;
  },

  // Delete system trade idea (admin only)
  async deleteSystemTradeIdea(ideaId: string): Promise<void> {
    await api.delete(`/api/v1/admin/trade-ideas/${ideaId}`);
  },

  // Reorder system filters (admin only)
  async reorderSystemFilters(ids: string[]): Promise<Filter[]> {
    const response = await api.put('/api/v1/admin/filters/reorder', { ids });
    return response.data;
  },

  // Reorder system trade ideas (admin only)
  async reorderSystemTradeIdeas(ids: string[]): Promise<TradeIdea[]> {
    const response = await api.put('/api/v1/admin/trade-ideas/reorder', { ids });
    return response.data;
  },
};

export default apiClient;
