"""
Flow & Positioning directional bias from Unusual Whales data.

Six independent signals — options premium flow, dealer delta trend, dealer gamma
regime, dark-pool positioning, discretionary insider flow, and max-pain pull —
are each normalized to [-1, +1] and combined into a weighted composite. Signals
that have no usable data are dropped and the remaining weights renormalized, so
one dead endpoint degrades the answer instead of breaking it.

This is positioning-derived context, not a price forecast.
- Portions generated by AI
"""

import logging
import math
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from ..core.config import get_settings
from ..core.market_clock import market_today, to_market_iso
from ..modules.breakout_scanner.providers.unusual_whales import UnusualWhalesProvider
from ..modules.breakout_scanner.uw_signals import _f, _get_any

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "Directional bias derived from options positioning and flow data. "
    "This is context, not a price forecast or investment advice."
)

# Judgment-based, not backtested. Tune here.
DIRECTION_WEIGHTS: Dict[str, float] = {
    "flow_sentiment": 0.30,
    "delta_trend": 0.20,
    "gamma_regime": 0.15,
    "dark_pool": 0.15,
    "insider": 0.10,
    "max_pain": 0.10,
}

SIGNAL_LABELS: Dict[str, str] = {
    "flow_sentiment": "Options flow",
    "delta_trend": "Dealer delta trend",
    "gamma_regime": "Gamma regime",
    "dark_pool": "Dark pool positioning",
    "insider": "Insider flow",
    "max_pain": "Max pain pull",
}

# Below this much total premium the flow read is noise, not signal.
MIN_FLOW_PREMIUM = 250_000.0
# Insider flow below this notional is not worth scoring, and only flow at or
# above the material threshold earns a full-strength score — otherwise a lone
# small sale would read as maximally bearish.
MIN_INSIDER_PREMIUM = 100_000.0
MATERIAL_INSIDER_PREMIUM = 5_000_000.0
INSIDER_LOOKBACK_DAYS = 90
# |score| at or beyond this threshold reads as directional rather than neutral.
DIRECTION_THRESHOLD = 0.20


def _tanh(x: float) -> float:
    return float(math.tanh(x))


def _dte(expiry: Any, today: Optional[date] = None) -> Optional[int]:
    """Calendar days from today to an ISO date string."""
    if not expiry:
        return None
    today = today or market_today()
    try:
        d = datetime.strptime(str(expiry)[:10], "%Y-%m-%d").date()
    except (TypeError, ValueError):
        return None
    return (d - today).days


# --------------------------------------------------------------------------- #
# Fetch (blocking — always call via asyncio.to_thread)
# --------------------------------------------------------------------------- #
def fetch_direction_bundle(symbol: str) -> Dict[str, Any]:
    """Pull every raw UW payload one prediction needs.

    Sequential on a single throttled client: the provider's rate limiting is
    per-instance, so fanning out would defeat it and invite 429s.
    """
    api_key = get_settings().UNUSUAL_WHALES_API_KEY
    if not api_key:
        raise DirectionUnavailable("Unusual Whales API key is not configured")

    provider = UnusualWhalesProvider(api_key=api_key, min_interval=0.15)
    if not provider.is_available():
        raise DirectionUnavailable("Unusual Whales client could not be initialized")

    bundle: Dict[str, Any] = {"symbol": symbol}
    calls = (
        ("flow_per_expiry", lambda: provider.flow_per_expiry(symbol)),
        ("greek_series", lambda: provider.greek_exposure_series(symbol)),
        ("dark_pool_levels", lambda: provider.darkpool_price_levels(symbol)),
        ("insider_flow", lambda: provider.insider_ticker_flow(symbol)),
        ("max_pain", lambda: provider.max_pain(symbol)),
    )
    try:
        for key, call in calls:
            try:
                bundle[key] = call()
            except Exception as e:  # provider already swallows most failures
                logger.warning(f"UW {key} failed for {symbol}: {e}")
                bundle[key] = None
    finally:
        provider.close()

    bundle["fetched_at"] = datetime.now(timezone.utc).isoformat()
    return bundle


class DirectionUnavailable(Exception):
    """Raised when the prediction cannot be produced at all."""


# --------------------------------------------------------------------------- #
# Individual signals — each returns (score in [-1, 1], human detail) or None
# --------------------------------------------------------------------------- #
def _signal_flow(rows: Any, dte_target: Optional[int]) -> Optional[Tuple[float, str]]:
    """Net aggressive premium: buyers lifting the ask reveal direction.

    Ask-side calls and bid-side puts are bullish initiations; bid-side calls and
    ask-side puts are bearish. Expiries are weighted by their premium size and
    by how close they sit to the contract being sold.
    """
    if not isinstance(rows, list) or not rows:
        return None

    target = dte_target if dte_target is not None else 30
    weighted_sum = 0.0
    weight_total = 0.0
    gross_premium = 0.0
    bull_total = 0.0
    bear_total = 0.0

    for row in rows:
        if not isinstance(row, dict):
            continue
        call_ask = _f(row.get("call_premium_ask_side")) or 0.0
        call_bid = _f(row.get("call_premium_bid_side")) or 0.0
        put_ask = _f(row.get("put_premium_ask_side")) or 0.0
        put_bid = _f(row.get("put_premium_bid_side")) or 0.0

        bull = call_ask + put_bid
        bear = put_ask + call_bid
        total = bull + bear
        if total <= 0:
            continue

        dte = _dte(row.get("expiry"))
        if dte is None or dte < 0:
            continue
        relevance = math.exp(-abs(dte - target) / 30.0)
        weight = total * relevance

        weighted_sum += weight * ((bull - bear) / total)
        weight_total += weight
        gross_premium += total
        # Report only the expiries that meaningfully drive the score, so the
        # headline numbers match what was actually weighted.
        if relevance >= 0.3:
            bull_total += bull
            bear_total += bear

    if weight_total <= 0 or gross_premium < MIN_FLOW_PREMIUM:
        return None

    score = max(-1.0, min(1.0, weighted_sum / weight_total))
    detail = (
        f"${bull_total / 1e6:.1f}M bullish vs ${bear_total / 1e6:.1f}M bearish "
        "premium near your expiry"
    )
    return score, detail


def _net_delta_series(rows: Any) -> List[float]:
    out: List[float] = []
    if not isinstance(rows, list):
        return out
    for row in rows:
        if not isinstance(row, dict):
            continue
        call_delta = _f(_get_any(row, "call_delta", "delta_call"))
        put_delta = _f(_get_any(row, "put_delta", "delta_put"))
        if call_delta is None or put_delta is None:
            continue
        # Put delta is reported negative, so the net book is the plain sum.
        out.append(call_delta + put_delta)
    return out


def _signal_delta_trend(rows: Any) -> Optional[Tuple[float, str]]:
    """Direction of change in dealer delta exposure over the last few sessions."""
    series = _net_delta_series(rows)
    if len(series) < 5:
        return None

    recent = series[-3:]
    prior = series[-13:-3] or series[:-3]
    if not prior:
        return None

    recent_avg = sum(recent) / len(recent)
    prior_avg = sum(prior) / len(prior)
    denom = abs(prior_avg) + 1e-9
    score = _tanh((recent_avg - prior_avg) / denom)

    direction = "rising" if recent_avg > prior_avg else "falling"
    pct = (recent_avg - prior_avg) / denom * 100.0
    detail = f"Net dealer delta {direction} {abs(pct):.0f}% vs prior 10 sessions"
    return score, detail


def _signal_gamma(rows: Any) -> Optional[Tuple[float, str, str]]:
    """Dealer gamma regime: long gamma dampens moves, short gamma amplifies them.

    Net gamma is ``call_gamma + put_gamma`` — UW reports put gamma negative, the
    same convention ``gex_profile`` documents for per-strike exposure.
    """
    if not isinstance(rows, list) or not rows:
        return None

    nets: List[float] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        call_gamma = _f(_get_any(row, "call_gamma", "gamma_call"))
        put_gamma = _f(_get_any(row, "put_gamma", "gamma_put"))
        if call_gamma is None or put_gamma is None:
            continue
        nets.append(call_gamma + put_gamma)

    if not nets:
        return None

    latest = nets[-1]
    scale = max(abs(v) for v in nets[-20:]) or abs(latest)
    if scale <= 0:
        return None

    score = _tanh(latest / scale)
    stability = "stabilizing" if latest > 0 else "amplifying"
    regime = "long_gamma" if latest > 0 else "short_gamma"
    detail = (
        "Dealers long gamma — moves tend to get dampened"
        if latest > 0
        else "Dealers short gamma — moves tend to get amplified"
    )
    return score, detail, regime


def _dark_pool_levels(payload: Any) -> List[Tuple[float, float]]:
    """[(price, dark_pool_volume)] from the price-levels payload."""
    out: List[Tuple[float, float]] = []
    rows: Any = None
    if isinstance(payload, dict):
        # REST returns {"data": [...]}; the MCP wrapper reshapes it to
        # {"stock_price_vol": [...]}. Accept either.
        rows = payload.get("data") or payload.get("stock_price_vol")
    elif isinstance(payload, list):
        rows = payload
    if not isinstance(rows, list):
        return out
    for row in rows:
        if not isinstance(row, dict):
            continue
        price = _f(row.get("price"))
        volume = _f(_get_any(row, "dark_pool_volume", "volume"))
        if price is None or volume is None or price <= 0 or volume <= 0:
            continue
        out.append((price, volume))
    return out


def _signal_dark_pool(
    payload: Any, spot: Optional[float]
) -> Optional[Tuple[float, str, float, float]]:
    """Spot versus the volume-weighted price institutions actually traded at.

    Above that average, the size below price acts as support; below it, the same
    size is overhead supply.
    """
    levels = _dark_pool_levels(payload)
    if not levels or not spot or spot <= 0:
        return None

    total_volume = sum(v for _, v in levels)
    if total_volume <= 0:
        return None

    vwap = sum(p * v for p, v in levels) / total_volume
    poc = max(levels, key=lambda pv: pv[1])[0]
    score = _tanh((spot - vwap) / (0.03 * spot))

    side = "above" if spot >= vwap else "below"
    detail = f"Price {side} the ${vwap:,.2f} dark-pool average (heaviest at ${poc:,.2f})"
    return score, detail, vwap, poc


def _signal_insider(rows: Any) -> Optional[Tuple[float, str]]:
    """Discretionary insider flow, excluding pre-scheduled 10b5-1 transactions.

    10b5-1 sales are planned months ahead and say nothing about current
    conviction, so counting them makes routine selling look like a bearish call.
    """
    if not isinstance(rows, list) or not rows:
        return None

    cutoff = market_today()
    net = 0.0
    gross = 0.0
    planned_only = True

    for row in rows:
        if not isinstance(row, dict):
            continue
        dte = _dte(row.get("date"), cutoff)
        if dte is None or dte < -INSIDER_LOOKBACK_DAYS:
            continue
        premium = _f(row.get("premium"))
        if premium is None:
            continue
        planned = _f(row.get("premium_10b5")) or 0.0
        discretionary = premium - planned
        if abs(discretionary) > 0:
            planned_only = False
        net += discretionary
        gross += abs(discretionary)

    if gross < MIN_INSIDER_PREMIUM:
        detail = (
            "No discretionary insider activity (all filings were 10b5-1 plans)"
            if planned_only
            else "No meaningful insider activity in the last 90 days"
        )
        return 0.0, detail

    materiality = min(1.0, gross / MATERIAL_INSIDER_PREMIUM)
    score = max(-1.0, min(1.0, net / gross)) * materiality
    verb = "buying" if net > 0 else "selling"
    detail = f"Net discretionary insider {verb} of ${abs(net) / 1e6:.1f}M over 90 days"
    return score, detail


def _signal_max_pain(
    payload: Any, spot: Optional[float], expiry: Optional[str]
) -> Optional[Tuple[float, str, float]]:
    """Pin pull toward the max-pain strike of the contract's own expiry."""
    if not spot or spot <= 0:
        return None

    rows: List[Dict[str, Any]] = []
    if isinstance(payload, dict):
        data = payload.get("data")
        if isinstance(data, list):
            rows = [r for r in data if isinstance(r, dict)]
    elif isinstance(payload, list):
        rows = [r for r in payload if isinstance(r, dict)]
    if not rows:
        return None

    target_dte = _dte(expiry) if expiry else None
    best: Optional[Tuple[float, float]] = None  # (distance_in_days, max_pain)
    for row in rows:
        mp = _f(_get_any(row, "max_pain", "max_pain_price"))
        dte = _dte(row.get("expiry"))
        if mp is None or mp <= 0 or dte is None or dte < 0:
            continue
        distance = abs(dte - target_dte) if target_dte is not None else dte
        if best is None or distance < best[0]:
            best = (distance, mp)

    if best is None:
        return None

    max_pain = best[1]
    score = _tanh((max_pain - spot) / (0.05 * spot))
    side = "above" if max_pain >= spot else "below"
    detail = f"Max pain ${max_pain:,.2f} sits {side} spot for the nearest expiry"
    return score, detail, max_pain


# --------------------------------------------------------------------------- #
# Composite
# --------------------------------------------------------------------------- #
def _put_seller_note(
    direction: str,
    stability: Optional[str],
    strike: Optional[float],
    levels: Dict[str, Optional[float]],
) -> str:
    """One sentence translating the read into cash-secured-put terms."""
    vwap = levels.get("dark_pool_vwap")
    max_pain = levels.get("max_pain")

    if strike is None:
        base = {
            "BULLISH": "Positioning leans higher, which favors selling puts here.",
            "BEARISH": "Positioning leans lower — assignment risk is elevated.",
        }.get(direction, "Positioning is mixed; no directional edge either way.")
        if stability == "amplifying":
            base += " Dealers are short gamma, so moves can overshoot."
        return base

    parts: List[str] = []
    if vwap:
        side = "below" if strike < vwap else "above"
        parts.append(f"your ${strike:,.2f} strike sits {side} the ${vwap:,.2f} dark-pool average")
    if max_pain:
        parts.append(f"max pain is ${max_pain:,.2f}")

    verdict = {
        "BULLISH": "flow is supportive for selling this put",
        "BEARISH": "flow argues for caution on assignment risk",
    }.get(direction, "flow is neutral for this strike")

    note = f"{' and '.join(parts).capitalize()}, so {verdict}." if parts else f"{verdict.capitalize()}."
    if stability == "amplifying":
        note += " Dealers are short gamma, so expect larger swings."
    return note


def score_direction(
    bundle: Dict[str, Any],
    spot: Optional[float],
    expiry: Optional[str] = None,
    strike: Optional[float] = None,
) -> Dict[str, Any]:
    """Combine the raw UW bundle into a directional read. Pure, no I/O."""
    dte_target = _dte(expiry) if expiry else None

    raw: Dict[str, Tuple[float, str]] = {}
    stability: Optional[str] = None
    gamma_regime: Optional[str] = None
    dp_vwap: Optional[float] = None
    dp_poc: Optional[float] = None
    max_pain_level: Optional[float] = None

    flow = _signal_flow(bundle.get("flow_per_expiry"), dte_target)
    if flow:
        raw["flow_sentiment"] = flow

    delta = _signal_delta_trend(bundle.get("greek_series"))
    if delta:
        raw["delta_trend"] = delta

    gamma = _signal_gamma(bundle.get("greek_series"))
    if gamma:
        raw["gamma_regime"] = (gamma[0], gamma[1])
        gamma_regime = gamma[2]
        stability = "stabilizing" if gamma[0] > 0 else "amplifying"

    dark = _signal_dark_pool(bundle.get("dark_pool_levels"), spot)
    if dark:
        raw["dark_pool"] = (dark[0], dark[1])
        dp_vwap, dp_poc = dark[2], dark[3]

    insider = _signal_insider(bundle.get("insider_flow"))
    if insider:
        raw["insider"] = insider

    pain = _signal_max_pain(bundle.get("max_pain"), spot, expiry)
    if pain:
        raw["max_pain"] = (pain[0], pain[1])
        max_pain_level = pain[2]

    weight_total = sum(DIRECTION_WEIGHTS[k] for k in raw)
    score = (
        sum(DIRECTION_WEIGHTS[k] * s for k, (s, _) in raw.items()) / weight_total
        if weight_total > 0
        else 0.0
    )
    coverage = weight_total / sum(DIRECTION_WEIGHTS.values())

    if score >= DIRECTION_THRESHOLD:
        direction = "BULLISH"
    elif score <= -DIRECTION_THRESHOLD:
        direction = "BEARISH"
    else:
        direction = "NEUTRAL"

    # Confidence falls for missing data, disagreement, or a score near zero —
    # three genuinely different reasons to distrust the read.
    if weight_total > 0:
        agreeing = 0.0
        for key, (s, _) in raw.items():
            w = DIRECTION_WEIGHTS[key]
            if abs(s) < 0.05:
                agreeing += w * 0.5
            elif (s > 0) == (score > 0):
                agreeing += w
        agreement = agreeing / weight_total
    else:
        agreement = 0.0
    magnitude = min(1.0, abs(score) / 0.5)
    confidence = coverage * (0.40 + 0.60 * agreement) * (0.45 + 0.55 * magnitude)

    signals = [
        {
            "key": key,
            "label": SIGNAL_LABELS[key],
            "weight": DIRECTION_WEIGHTS[key],
            "score": round(raw[key][0], 3) if key in raw else None,
            "detail": raw[key][1] if key in raw else "No data available",
            "available": key in raw,
        }
        for key in DIRECTION_WEIGHTS
    ]

    levels: Dict[str, Optional[float]] = {
        "dark_pool_vwap": round(dp_vwap, 2) if dp_vwap else None,
        "point_of_control": round(dp_poc, 2) if dp_poc else None,
        "max_pain": round(max_pain_level, 2) if max_pain_level else None,
    }

    return {
        "symbol": bundle.get("symbol", ""),
        "as_of": to_market_iso(datetime.now(timezone.utc)),
        "direction": direction,
        "score": round(score * 100.0, 1),
        "confidence": round(confidence, 3),
        "coverage": round(coverage, 3),
        "stability": stability,
        "gamma_regime": gamma_regime,
        "signals": signals,
        "levels": levels,
        "put_seller_note": _put_seller_note(direction, stability, strike, levels),
        "disclaimer": DISCLAIMER,
    }
