"""
Screener service - business logic for options screening
- Portions generated by AI

Includes caching layer for:
- Stock prices (1 minute TTL)
- Options chains (5 minutes TTL)
- News (15 minutes TTL)
- Event dates (1 week TTL)

Supports multiple API providers:
- Massive.com API (15-minute delayed options data)
- Alpaca API (real-time options data with bid/ask quotes)
"""

from datetime import date
from typing import Dict, List, Any, Tuple

# Import from local modules
from .options_screener import (
    get_stock_price_massive,
    get_stock_price_yahoo,
    get_stock_price_alpaca,
    get_stock_price_with_change_massive,
    get_stock_price_with_change_yahoo,
    get_stock_price_with_change_alpaca,
    get_options_chain_massive,
    get_options_chain_yahoo,
    get_options_chain_alpaca,
    calculate_metrics,
    screen_options as filter_options,
    get_fallback_options,
    format_output,
    get_earnings_dividend_dates,
)
from .massive_api_client import get_massive_client
from .alpaca_api_client import get_alpaca_client
from ..core.cache import (
    get_cached_stock_price,
    set_cached_stock_price,
    get_cached_options_chain,
    set_cached_options_chain,
    get_cached_news,
    set_cached_news,
    get_cached_event_dates,
    set_cached_event_dates,
    get_config_hash,
    is_cache_disabled,
)
from ..core.api_provider import get_active_provider, get_use_midpoint_pricing

SCREENER_AVAILABLE = True


def screen_symbols(
    symbols: List[str],
    max_dte: int = 45,
    min_dte: int = 15,
    min_volume: int = 10,
    min_open_interest: int = 10,
    min_annualized_return: float = 20.0,
    max_assignment_probability: int = 20,
) -> Tuple[Dict[str, List[Dict[str, Any]]], bool]:
    """
    Screen multiple symbols for put options.
    
    Args:
        symbols: List of stock symbols to screen
        max_dte: Maximum days to expiration
        min_dte: Minimum days to expiration
        min_volume: Minimum option volume
        min_open_interest: Minimum open interest
        min_annualized_return: Minimum annualized return percentage
        max_assignment_probability: Maximum assignment probability percentage
    
    Returns:
        Tuple of (results dict, used_yahoo_fallback bool)
        results dict: symbol -> list of option dicts
    """
    if not SCREENER_AVAILABLE:
        return {}, False
    
    # Build config for screener
    config = {
        'options_strategy': {
            'max_dte': max_dte,
            'min_dte': min_dte,
            'min_volume': min_volume,
            'min_open_interest': min_open_interest
        },
        'screening_criteria': {
            'min_annualized_return': min_annualized_return,
            'max_assignment_probability': max_assignment_probability
        },
        'output': {
            'sort_by': ['annualized_return'],
            'sort_order': 'descending',
            'max_results': 50
        }
    }
    
    results = {}
    used_yahoo = False
    
    for symbol in symbols:
        try:
            symbol_results, symbol_yahoo = _screen_single_symbol(symbol, config)
            if symbol_results:
                results[symbol] = symbol_results
            if symbol_yahoo:
                used_yahoo = True
        except Exception as e:
            print(f"Error processing {symbol}: {e}")
            continue
    
    # Enrich qualified results with earnings/dividend event flags
    # This is done AFTER filtering to minimize API calls
    results = _enrich_with_event_dates(results)
    
    return results, used_yahoo


def _enrich_with_event_dates(results: Dict[str, List[Dict[str, Any]]]) -> Dict[str, List[Dict[str, Any]]]:
    """
    Enrich qualified results with earnings/dividend flags.
    Only fetches data for symbols that have qualifying options (post-filter optimization).
    
    Event flags are set to True only when the event date falls BETWEEN today and expiry date.
    This ensures we only flag upcoming events that are relevant to the option's timeframe.
    
    Args:
        results: Dictionary of symbol -> list of option dicts
        
    Returns:
        Same results dict with has_earnings_before_expiry and has_dividend_before_expiry added
    """
    # Get today's date as string for comparison (YYYY-MM-DD format)
    today_str = date.today().strftime('%Y-%m-%d')
    
    # Check if caching is disabled
    cache_disabled = is_cache_disabled()
    
    for symbol, options in results.items():
        if not options:
            continue
        
        # Check cache first (unless caching is disabled)
        event_dates = None if cache_disabled else get_cached_event_dates(symbol)
        
        if event_dates is None:
            # Fetch from Yahoo Finance (only for qualified symbols)
            event_dates = get_earnings_dividend_dates(symbol)
            # Only cache if caching is enabled and we got valid data
            if event_dates and not cache_disabled:
                set_cached_event_dates(symbol, event_dates)
        
        if not event_dates:
            event_dates = {'earnings_date': None, 'ex_dividend_date': None}
        
        # Add flags to each option row
        for row in options:
            expiry = row.get('expiry', '')
            
            # Check if earnings date is between now and expiry
            # Event must be: today <= event_date < expiry
            earnings_date = event_dates.get('earnings_date')
            row['has_earnings_before_expiry'] = bool(
                earnings_date and expiry and 
                today_str <= earnings_date < expiry
            )
            
            # Check if ex-dividend date is between now and expiry
            # Event must be: today <= event_date < expiry
            ex_div_date = event_dates.get('ex_dividend_date')
            row['has_dividend_before_expiry'] = bool(
                ex_div_date and expiry and 
                today_str <= ex_div_date < expiry
            )
    
    return results


def _screen_single_symbol(symbol: str, config: dict) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Screen a single symbol for put options.
    Uses caching to reduce external API calls.
    Routes requests to the active API provider (Massive or Alpaca).
    
    Returns:
        Tuple of (list of option dicts, used_yahoo bool)
    """
    import pandas as pd
    
    used_yahoo = False
    config_hash = get_config_hash(config)
    active_provider = get_active_provider()
    
    # Check cache for stock price first
    cached_price_data = get_cached_stock_price(symbol)
    current_price = None
    price_change_percent = None
    
    if cached_price_data is not None:
        # Handle both old format (float) and new format (dict)
        if isinstance(cached_price_data, dict):
            current_price = cached_price_data.get('price')
            price_change_percent = cached_price_data.get('change_percent')
            print(f"[CACHE HIT] Price for {symbol}: ${current_price}" + (f" ({'+' if price_change_percent and price_change_percent >= 0 else ''}{price_change_percent:.2f}%)" if price_change_percent is not None else ""))
        else:
            current_price = cached_price_data
            print(f"[CACHE HIT] Price for {symbol}: ${current_price}")
    else:
        # Get price with change from active API provider
        price_data = None
        if active_provider == "alpaca":
            price_data = get_stock_price_with_change_alpaca(symbol)
        else:
            price_data = get_stock_price_with_change_massive(symbol)
        
        # Yahoo fallback if primary provider fails
        if price_data is None:
            price_data = get_stock_price_with_change_yahoo(symbol)
            if price_data:
                used_yahoo = True
        
        if price_data is not None:
            current_price = price_data.get('price')
            price_change_percent = price_data.get('change_percent')
            # Cache the full price data
            set_cached_stock_price(symbol, price_data)
            print(f"[CACHE SET] Price for {symbol}: ${current_price}" + (f" ({'+' if price_change_percent and price_change_percent >= 0 else ''}{price_change_percent:.2f}%)" if price_change_percent is not None else ""))
    
    if current_price is None:
        return [], used_yahoo
    
    # Check cache for options chain
    # Include provider in cache key to separate Massive vs Alpaca data
    provider_config_hash = f"{active_provider}_{config_hash}"
    cached_options = get_cached_options_chain(symbol, provider_config_hash)
    if cached_options is not None:
        print(f"[CACHE HIT] Options chain for {symbol} ({len(cached_options)} options)")
        options = pd.DataFrame(cached_options)
    else:
        # Get options chain from active API provider
        if active_provider == "alpaca":
            options = get_options_chain_alpaca(symbol, config)
        else:
            options = get_options_chain_massive(symbol, config)
        
        # Yahoo fallback if primary provider fails
        if options.empty:
            options = get_options_chain_yahoo(symbol, config)
            if not options.empty:
                used_yahoo = True
        
        if not options.empty:
            # Cache the raw options data
            set_cached_options_chain(symbol, provider_config_hash, options.to_dict(orient='records'))
            print(f"[CACHE SET] Options chain for {symbol} ({len(options)} options)")
    
    if options.empty:
        return [], used_yahoo
    
    # Calculate metrics and filter (always done fresh since these depend on current price)
    options = calculate_metrics(options, current_price)
    # Pass api_source to enable volume fetching for Alpaca after other filters
    filtered = filter_options(options, config, api_source=active_provider)

    # Track whether this symbol's options fully meet the screening criteria.
    # When nothing fully qualifies, fall back to contracts that match every
    # criterion EXCEPT the minimum annualized return so the ticker remains
    # visible in the results dropdown (excluded from the Summary and pushed to
    # the end by the frontend). If even that relaxed set is empty, the ticker
    # does not appear at all.
    meets_criteria = not filtered.empty
    if filtered.empty:
        filtered = get_fallback_options(options, config, api_source=active_provider)

    formatted = format_output(filtered, current_price)
    
    if formatted.empty:
        return [], used_yahoo
    
    # Convert DataFrame to list of dicts and add price_change_percent to each row
    results = formatted.to_dict(orient='records')
    for row in results:
        row['price_change_percent'] = price_change_percent
        row['meets_criteria'] = meets_criteria
    
    return results, used_yahoo


def get_news(symbol: str, limit: int = 10, max_age_days: int = 7) -> List[Dict[str, Any]]:
    """
    Get news for a symbol with caching.
    Routes to active API provider (Massive or Alpaca).
    
    Args:
        symbol: Stock symbol
        limit: Maximum number of news items
        max_age_days: Maximum age of news in days
    
    Returns:
        List of news item dicts
    """
    active_provider = get_active_provider()
    
    # Check cache first (use provider-specific cache key)
    cached_news = get_cached_news(symbol)
    if cached_news is not None:
        print(f"[CACHE HIT] News for {symbol} ({len(cached_news)} items)")
        return cached_news[:limit]  # Respect limit even from cache
    
    news = []
    
    if active_provider == "alpaca":
        # Use Alpaca for news
        alpaca_client = get_alpaca_client(use_midpoint_pricing=get_use_midpoint_pricing())
        if alpaca_client:
            try:
                news = alpaca_client.get_ticker_news(symbol, limit=limit, max_age_days=max_age_days)
            except Exception as e:
                print(f"Error fetching Alpaca news for {symbol}: {e}")
    else:
        # Use Massive for news
        massive_client = get_massive_client()
        if massive_client:
            try:
                news = massive_client.get_ticker_news(symbol, limit=limit, max_age_days=max_age_days)
            except Exception as e:
                print(f"Error fetching Massive news for {symbol}: {e}")
    
    if news:
        # Cache news
        set_cached_news(symbol, news)
        print(f"[CACHE SET] News for {symbol} ({len(news)} items)")
    
    return news
