"""
Stock Analyzer Service - Orchestrates AI-powered stock analysis
- Portions generated by AI
"""

from typing import Dict, Any, Optional, Union
from datetime import datetime, timezone
import logging

from .data_fetcher import get_all_analysis_data
from .llm import (
    get_active_provider_or_raise,
    AnalysisError,
    DataFetchError,
    LLMUnavailableError,
)
from ..core.api_provider import is_massive_active, is_alpaca_active

logger = logging.getLogger(__name__)

# Standard disclaimer for all analyses
DISCLAIMER = """DISCLAIMER: This AI-generated analysis is for informational purposes only and does not constitute financial advice. Past performance does not guarantee future results. Options trading involves significant risk of loss. Always do your own research and consider consulting a licensed financial advisor before making investment decisions. The developers of this tool are not responsible for any trading losses."""


def get_news_for_analysis(symbol: str, limit: int = 15) -> list:
    """
    Fetch news from the currently active API provider.
    
    Args:
        symbol: Stock ticker symbol
        limit: Maximum number of news items
        
    Returns:
        List of news items
    """
    try:
        if is_massive_active():
            from .massive_api_client import get_massive_client
            client = get_massive_client()
            if client:
                return client.get_ticker_news(symbol, limit=limit)
        elif is_alpaca_active():
            from .alpaca_api_client import get_alpaca_client
            client = get_alpaca_client()
            if client:
                return client.get_ticker_news(symbol, limit=limit)
    except Exception as e:
        logger.warning(f"Failed to fetch news for {symbol}: {e}")
    
    return []


def get_massive_extended_data(symbol: str) -> Dict[str, Any]:
    """
    Fetch extended data from Massive API (short interest, analyst ratings, earnings).
    
    Args:
        symbol: Stock ticker symbol
        
    Returns:
        Dictionary with extended data
    """
    data = {}
    
    if not is_massive_active():
        return data
    
    try:
        from .massive_api_client import get_massive_client
        client = get_massive_client()
        
        if client:
            data['short_interest'] = client.get_short_interest(symbol)
            data['analyst_ratings'] = client.get_analyst_ratings(symbol)
            data['earnings'] = client.get_earnings_data(symbol)
    except Exception as e:
        logger.warning(f"Failed to fetch Massive extended data for {symbol}: {e}")
    
    return data


def validate_analysis(analysis: Dict[str, Any], raw_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Validate and fix LLM output against real data.
    
    Args:
        analysis: Raw LLM output
        raw_data: Original data used for analysis
        
    Returns:
        Validated and corrected analysis
    """
    yahoo_data = raw_data.get('yahoo', {})
    technicals = raw_data.get('technicals', {})
    current_price = yahoo_data.get('current_price', 0)
    
    # 1. Ensure scenarios exist and probabilities sum to 1.0
    scenarios = analysis.get('scenarios', [])
    if scenarios:
        total_prob = sum(s.get('probability', 0) for s in scenarios)
        if total_prob > 0 and abs(total_prob - 1.0) > 0.01:
            # Normalize probabilities
            for s in scenarios:
                s['probability'] = s.get('probability', 0) / total_prob
    
    # 2. Validate price targets are reasonable (within 50% of current price)
    if current_price > 0:
        for scenario in scenarios:
            target = scenario.get('price_target', current_price)
            if target:
                change_pct = abs((target - current_price) / current_price)
                days_to_earnings = yahoo_data.get('days_to_earnings', 999)
                max_move = 0.75 if days_to_earnings and days_to_earnings <= 7 else 0.5
                
                if change_pct > max_move:
                    if target > current_price:
                        scenario['price_target'] = round(current_price * (1 + max_move), 2)
                    else:
                        scenario['price_target'] = round(current_price * (1 - max_move), 2)
                
                # Recalculate return percent
                scenario['return_percent'] = round(
                    ((scenario['price_target'] - current_price) / current_price) * 100, 2
                )
    
    # 3. Validate trade recommendation
    rec = analysis.get('trade_recommendation', {})
    if rec and current_price > 0:
        entry_zone = rec.get('entry_zone', {})
        entry_low = entry_zone.get('low', current_price * 0.95)
        entry_high = entry_zone.get('high', current_price * 1.05)
        stop_loss = rec.get('stop_loss', 0)
        
        # Ensure stop loss is below entry
        if stop_loss >= entry_low:
            support = technicals.get('support_level', current_price * 0.9)
            stop_loss = min(support, entry_low * 0.9)
            rec['stop_loss'] = round(stop_loss, 2)
        
        # Recalculate stop loss percent
        entry_mid = (entry_low + entry_high) / 2
        rec['stop_loss_percent'] = round(((entry_mid - stop_loss) / entry_mid) * 100, 2)
        
        # Recalculate risk/reward
        targets = rec.get('targets', [])
        if targets:
            avg_target = sum(t.get('price', entry_mid) for t in targets) / len(targets)
            risk = entry_mid - stop_loss
            reward = avg_target - entry_mid
            rec['risk_reward_ratio'] = round(reward / risk, 2) if risk > 0 else 0
    
    # 4. Build key_metrics from real data (override any LLM hallucinations)
    analysis['key_metrics'] = {
        'current_price': yahoo_data.get('current_price'),
        'price_change_percent': yahoo_data.get('change_percent'),
        'fifty_two_week_high': yahoo_data.get('fifty_two_week_high'),
        'fifty_two_week_low': yahoo_data.get('fifty_two_week_low'),
        'volume': yahoo_data.get('volume'),
        'avg_volume': yahoo_data.get('avg_volume'),
        'market_cap': yahoo_data.get('market_cap'),
        'pe_ratio': yahoo_data.get('pe_ratio'),
        'beta': yahoo_data.get('beta'),
        'short_interest_percent': raw_data.get('short_interest', {}).get('short_interest_percent') if raw_data.get('short_interest') else None,
        'analyst_rating': raw_data.get('analyst_ratings', {}).get('rating') if raw_data.get('analyst_ratings') else None,
        'avg_price_target': raw_data.get('analyst_ratings', {}).get('target_price') if raw_data.get('analyst_ratings') else None,
        'price_target_upside': None,  # Calculate below
    }
    
    # Calculate price target upside
    if analysis['key_metrics']['avg_price_target'] and current_price:
        upside = ((analysis['key_metrics']['avg_price_target'] - current_price) / current_price) * 100
        analysis['key_metrics']['price_target_upside'] = round(upside, 2)
    
    # 5. Use calculated technicals (not LLM guesses)
    analysis['technicals'] = {
        'rsi_14': technicals.get('rsi_14'),
        'sma_20': technicals.get('sma_20'),
        'sma_50': technicals.get('sma_50'),
        'sma_200': technicals.get('sma_200'),
        'trend': technicals.get('trend', 'SIDEWAYS'),
        'support_level': technicals.get('support_level'),
        'resistance_level': technicals.get('resistance_level'),
    }
    
    return analysis


async def analyze_stock(
    symbol: str,
    preferred_provider: str = 'gemini'
) -> Dict[str, Any]:
    """
    Perform AI-powered stock analysis.
    
    Args:
        symbol: Stock ticker symbol
        preferred_provider: Preferred LLM provider name
        
    Returns:
        Complete analysis dictionary
        
    Raises:
        DataFetchError: If required data cannot be fetched
        LLMUnavailableError: If no LLM provider is available
        AnalysisError: If analysis generation fails
    """
    symbol = symbol.upper().strip()
    
    # 1. Fetch all data
    logger.info(f"Fetching data for {symbol}...")
    
    # Yahoo Finance data (always used)
    base_data = get_all_analysis_data(symbol)
    
    if not base_data.get('yahoo') or not base_data['yahoo'].get('current_price'):
        raise DataFetchError(f"Could not fetch price data for {symbol}. Please verify the symbol is valid.")
    
    # News from active API provider
    base_data['news'] = get_news_for_analysis(symbol)
    
    # Extended data from Massive API (if active)
    massive_data = get_massive_extended_data(symbol)
    base_data.update(massive_data)
    
    # Track data sources
    data_sources = ['Yahoo Finance']
    if base_data.get('news'):
        data_sources.append('Massive API' if is_massive_active() else 'Alpaca API')
    if base_data.get('short_interest') or base_data.get('analyst_ratings'):
        if 'Massive API' not in data_sources:
            data_sources.append('Massive API')
    
    # 2. Get LLM provider
    provider = get_active_provider_or_raise(preferred_provider)
    logger.info(f"Using LLM provider: {provider.name}")
    
    # 3. Build prompt and generate analysis
    prompt = provider.get_analysis_prompt(symbol, base_data)
    
    try:
        raw_analysis = await provider.generate_analysis(prompt)
    except AnalysisError:
        raise
    except Exception as e:
        raise AnalysisError(f"Analysis generation failed: {str(e)}")
    
    # 4. Validate and enhance analysis
    analysis = validate_analysis(raw_analysis, base_data)
    
    # 5. Add metadata
    now = datetime.now(timezone.utc)
    analysis['symbol'] = symbol
    analysis['analysis_date'] = now.isoformat()
    analysis['data_sources'] = data_sources
    analysis['llm_provider'] = provider.name
    analysis['disclaimer'] = DISCLAIMER
    
    return analysis


async def analyze_stock_safe(
    symbol: str,
    preferred_provider: str = 'gemini'
) -> Union[Dict[str, Any], Dict[str, str]]:
    """
    Analyze stock with graceful error handling.
    
    Args:
        symbol: Stock ticker symbol
        preferred_provider: Preferred LLM provider name
        
    Returns:
        Analysis dictionary or error dictionary
    """
    try:
        return await analyze_stock(symbol, preferred_provider)
    except LLMUnavailableError as e:
        return {
            'error': str(e),
            'error_type': 'configuration',
            'symbol': symbol
        }
    except DataFetchError as e:
        return {
            'error': str(e),
            'error_type': 'data',
            'symbol': symbol
        }
    except AnalysisError as e:
        return {
            'error': str(e),
            'error_type': 'analysis',
            'symbol': symbol
        }
    except Exception as e:
        logger.exception(f"Unexpected error analyzing {symbol}")
        return {
            'error': 'Analysis temporarily unavailable. Please try again.',
            'error_type': 'system',
            'symbol': symbol
        }
