/**
 * TypeScript types for PutYield
 * - Portions generated by AI
 */

// User settings (legacy + new fields)
export interface UserSettings {
  // Legacy fields for backward compatibility
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
  
  // New fields for filters and trade ideas
  selected_filter_id?: string | null;
  selected_trade_idea_id?: string | null;
}

// Filter model
export interface Filter {
  id: string;
  name: string;
  is_system: boolean;
  is_default: boolean;
  display_order: number;
  user_id?: string | null;
  min_dte: number;
  max_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
  created_at?: string;
  updated_at?: string;
}

// Filter list response
export interface FilterListResponse {
  system_filters: Filter[];
  user_filters: Filter[];
  default_filter_id?: string | null;
}

// Trade Idea model
export interface TradeIdea {
  id: string;
  name: string;
  description?: string | null;
  is_system: boolean;
  is_default: boolean;
  display_order: number;
  user_id?: string | null;
  symbols: string[];
  created_at?: string;
  updated_at?: string;
}

// Trade Idea list response
export interface TradeIdeaListResponse {
  system_trade_ideas: TradeIdea[];
  user_trade_ideas: TradeIdea[];
  default_trade_idea_id?: string | null;
}

// Filter create/update request
export interface FilterCreateRequest {
  name?: string;
  min_dte: number;
  max_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// Trade Idea create/update request
export interface TradeIdeaCreateRequest {
  name: string;
  description?: string;
  symbols: string[];
}

// User info
export interface UserInfo {
  id: string;
  email: string | null;
  subscription_status: 'free' | 'pro' | 'cancelled';
  screens_today: number;
  screens_remaining: number;
  settings: UserSettings | null;
}

// Option result from screening
export interface OptionResult {
  symbol: string;
  current_price: number;
  price_change_percent?: number;  // Percent change from previous close
  strike: number;
  premium?: number;
  lastPrice?: number;
  annualized_return: number;
  daily_decay_contract?: number;
  prob_assign: number;
  expiry: string;
  calendar_days?: number;
  dte?: number;
  volume: number;
  open_interest: number;
  openInterest?: number;
  implied_volatility?: number;
  impliedVolatility?: number;
  has_earnings_before_expiry?: boolean;  // Earnings call before expiry
  has_dividend_before_expiry?: boolean;  // Ex-dividend date before expiry
  meets_criteria?: boolean;  // Unused; kept for older API responses
  sma_20?: number | null;
  sma_50?: number | null;
  sma_200?: number | null;
  rsi_14?: number | null;
}

// Screen request
export interface ScreenRequest {
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// Screen response
export interface ScreenResponse {
  success: boolean;
  results: Record<string, OptionResult[]>;
  screens_remaining: number | null;
  used_yahoo_fallback: boolean;
  message: string;
}

// News item
export interface NewsItem {
  title: string;
  url: string;
  published?: string;
  date_display?: string;
  source?: string;
}

// News response
export interface NewsResponse {
  symbol: string;
  news: NewsItem[];
  error?: string;
}

// Health check response
export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  database: string;
  massive_api: string;
  auth: string;
}

// US equities session clock (Alpaca)
export interface MarketClock {
  timestamp: string;
  is_open: boolean;
  next_open: string | null;
  next_close: string | null;
  timezone: string;
  source: 'alpaca' | 'fallback';
}

// Cache settings (admin only)
export interface CacheSettings {
  cache_enabled: boolean;
  ttl_stock_price: number;
  ttl_options_chain: number;
  ttl_news: number;
  ttl_event_dates: number;  // Earnings/dividend dates cache TTL (default 1 week)
  updated_at?: string;
}

// API provider settings (admin only)
export interface ApiProviderSettings {
  active_provider: 'massive' | 'alpaca';
  use_midpoint_pricing: boolean;
  massive_api_configured: boolean;
  alpaca_api_configured: boolean;
  updated_at?: string;
}

// Market settings (admin only)
export interface MarketSettings {
  risk_free_rate: number;  // As decimal (e.g., 0.0367 for 3.67%)
  risk_free_rate_percent: number;  // Convenience: risk_free_rate * 100
  updated_at?: string;
}

// ============== AI Stock Analysis Types ==============

// Key metrics from real data
export interface KeyMetrics {
  current_price: number | null;
  price_change_percent: number | null;
  fifty_two_week_high: number | null;
  fifty_two_week_low: number | null;
  volume: number | null;
  avg_volume: number | null;
  market_cap: number | null;
  pe_ratio: number | null;
  beta: number | null;
  short_interest_percent: number | null;
  analyst_rating: string | null;
  avg_price_target: number | null;
  price_target_upside: number | null;
}

// Technical indicators
export interface Technicals {
  // Oscillators
  rsi_14: number | null;
  rsi_signal: 'OVERSOLD' | 'OVERBOUGHT' | 'NEUTRAL' | null;
  macd_line: number | null;
  macd_signal_line: number | null;
  macd_histogram: number | null;
  macd_signal: 'BULLISH' | 'BEARISH' | 'NEUTRAL' | null;

  // Moving Averages
  sma_20: number | null;
  sma_50: number | null;
  sma_200: number | null;
  price_vs_sma20: 'ABOVE' | 'BELOW' | null;
  price_vs_sma50: 'ABOVE' | 'BELOW' | null;
  price_vs_sma200: 'ABOVE' | 'BELOW' | null;
  sma20_distance_pct: number | null;
  sma50_distance_pct: number | null;
  sma200_distance_pct: number | null;

  // Trends
  short_term_trend: 'UPTREND' | 'DOWNTREND' | null;
  long_term_trend: 'UPTREND' | 'DOWNTREND' | null;
  trend: 'UPTREND' | 'DOWNTREND' | 'SIDEWAYS' | null;

  // Support & Resistance
  near_support: number | null;
  major_support: number | null;
  near_resistance: number | null;
  major_resistance: number | null;
  support_level: number | null;
  resistance_level: number | null;

  // Volatility
  atr_14: number | null;
  volatility_level: 'LOW' | 'MODERATE' | 'HIGH' | 'EXTREME' | null;

  // Volume
  volume_signal: 'NORMAL' | 'ACCUMULATION' | 'DISTRIBUTION' | 'CAPITULATION' | null;

  // Fibonacci
  fib_high: number | null;
  fib_low: number | null;
  fib_23_6: number | null;
  fib_38_2: number | null;
  fib_50_0: number | null;
  fib_61_8: number | null;
  fib_nearest_level: string | null;
  fib_nearest_price: number | null;

  // Momentum Oscillators
  ema_9: number | null;
  price_vs_ema9: 'ABOVE' | 'BELOW' | null;
  ema9_distance_pct: number | null;
  stoch_k: number | null;
  stoch_d: number | null;
  stoch_signal: 'OVERSOLD' | 'OVERBOUGHT' | 'NEUTRAL' | 'BULLISH_CROSS' | 'BEARISH_CROSS' | null;
  roc_5d: number | null;
  roc_10d: number | null;

  // Bollinger Bands
  bb_upper: number | null;
  bb_middle: number | null;
  bb_lower: number | null;
  bb_position: 'ABOVE_UPPER' | 'UPPER_HALF' | 'LOWER_HALF' | 'BELOW_LOWER' | null;
  bb_squeeze: boolean | null;

  // Enhanced Volume
  vol_trend_3d_vs_20d: number | null;

  // Gap Analysis
  gap_direction: 'UP' | 'DOWN' | 'NONE' | null;
  gap_size_pct: number | null;

  // Market Context
  rs_vs_spy_5d: number | null;
  rs_vs_spy_10d: number | null;
  rs_vs_spy_20d: number | null;
  spy_change_5d: number | null;
  sector: string | null;
  industry: string | null;

  // Post-Earnings
  post_earnings_drift: 'UP' | 'DOWN' | 'NONE' | null;
  days_since_earnings: number | null;

  // LLM-generated interpretive fields
  candle_pattern: string | null;
  overall_signal: string | null;
  signal_note: string | null;
}

// Scenario analysis
export interface Scenario {
  name: 'Bull Case' | 'Base Case' | 'Bear Case' | string;
  probability: number;
  price_target: number;
  return_percent: number;
  conditions: string[];
  timeframe: string;
}

// Upcoming catalyst
export interface Catalyst {
  event: string;
  date: string | null;
  days_until: number | null;
  importance: 'HIGH' | 'MEDIUM' | 'LOW';
  expected_impact: string;
}

// Bullish/bearish factor
export interface Factor {
  factor: string;
  source: 'News' | 'Technical' | 'Fundamental' | 'Analyst' | string;
  weight: 'HIGH' | 'MEDIUM' | 'LOW';
}

// Price target
export interface PriceTarget {
  price: number;
  label: string;
}

// Entry zone
export interface EntryZone {
  low: number;
  high: number;
}

// Trade recommendation
export interface TradeRecommendation {
  action: 'STRONG BUY' | 'BUY' | 'HOLD' | 'SELL' | 'STRONG SELL' | 'WAIT';
  conviction: 'HIGH' | 'MEDIUM' | 'LOW';
  rationale: string;
  entry_zone: EntryZone | null;
  stop_loss: number | null;
  stop_loss_percent: number | null;
  targets: PriceTarget[];
  risk_reward_ratio: number | null;
  position_size_suggestion: string;
  timeframe: string;
  warnings: string[];
}

// Complete stock analysis
export interface StockAnalysis {
  symbol: string;
  analysis_date: string;
  data_sources: string[];
  
  // Overall assessment
  overall_sentiment: 'BULLISH' | 'NEUTRAL' | 'BEARISH';
  confidence: number;
  summary: string;
  
  // Factual data
  key_metrics: KeyMetrics | null;
  technicals: Technicals | null;
  
  // LLM-generated analysis
  scenarios: Scenario[];
  upcoming_catalysts: Catalyst[];
  bullish_factors: Factor[];
  bearish_factors: Factor[];
  trade_recommendation: TradeRecommendation | null;
  
  // Metadata
  cached_at: string | null;
  expires_at: string | null;
  llm_provider: string;
  disclaimer: string;
}

// Analysis error response
export interface AnalysisError {
  error: string;
  error_type: 'configuration' | 'data' | 'analysis' | 'system';
  symbol: string;
}

// AI provider info
export interface AIProvider {
  name: string;
  available: boolean;
  display_name: string;
}

// AI settings (admin only)
export interface AISettings {
  ai_enabled: boolean;
  active_provider: 'gemini' | 'groq' | 'openai';
  cache_enabled: boolean;
  cache_ttl_seconds: number;
  available_providers: AIProvider[];
  updated_at?: string;
}

// AI settings update request
export interface AISettingsUpdate {
  ai_enabled?: boolean;
  active_provider?: 'gemini' | 'groq' | 'openai';
  cache_enabled?: boolean;
  cache_ttl_seconds?: number;
}

// ============================================================
// Breakout Scanner (Momentum Stocks)
// ============================================================

export interface BreakoutScannerSettings {
  enabled: boolean;
  universe: string[];
  universe_mode: string;        // "curated" | "auto"
  auto_universe_size: number;   // max symbols in auto mode
  top_n: number;
  deep_dive_n: number;
  use_unusual_whales: boolean;
  weights: Record<string, number>;
  /** Weights after defaults are merged and renormalized to 1.0. */
  effective_weights: Record<string, number>;
  min_price: number;
  max_price: number;
  min_avg_volume: number;
  require_above_sma200: boolean;
  typical_csp_dte: number;
  /** Automatic scheduled scan. Manual runs work regardless of this. */
  auto_scan_enabled: boolean;
  /** "HH:MM" 24-hour, local to auto_scan_timezone. */
  auto_scan_time: string;
  /** IANA zone name, e.g. "America/New_York". */
  auto_scan_timezone: string;
  /** Python weekday numbering: 0 = Monday .. 6 = Sunday. */
  auto_scan_days: number[];
  /** Server-rendered summary, e.g. "16:30 America/New_York on Mon,Tue,Wed,Thu,Fri". */
  auto_scan_summary: string;
  last_auto_run_at: string | null;
  /** Resolved server-side so the UI never reimplements the schedule math. */
  next_auto_run_at: string | null;
  last_run_at: string | null;
  last_run_status: string;
  last_run_message: string | null;
  market_context: BreakoutMarketContext | null;
  updated_at: string | null;
  unusual_whales_configured: boolean;
}

export interface BreakoutMarketContext {
  regime?: string;
  fear_greed?: number;
  regime_scale?: number;
  spy_trend?: number | null;
  qqq_trend?: number | null;
  breadth?: number | null;
  vix?: number | null;
  vix_change_5d?: number | null;
  market_tide?: number | null;
  spike?: number | null;
  notes?: string[];
}

export interface BreakoutScannerSettingsUpdate {
  enabled?: boolean;
  universe?: string[];
  universe_mode?: string;
  auto_universe_size?: number;
  top_n?: number;
  deep_dive_n?: number;
  use_unusual_whales?: boolean;
  weights?: Record<string, number>;
  min_price?: number;
  max_price?: number;
  min_avg_volume?: number;
  require_above_sma200?: boolean;
  typical_csp_dte?: number;
  auto_scan_enabled?: boolean;
  auto_scan_time?: string;
  auto_scan_timezone?: string;
  auto_scan_days?: number[];
}

export interface BreakoutScanResultItem {
  symbol: string;
  score: number;
  rank: number;
  setup_type: string | null;
  pivot_price: number | null;
  current_price: number | null;
  volume_expansion: number | null;
  pct_from_52wk_high: number | null;
  pct_to_pivot: number | null;
  iv_rank: number | null;
  implied_move: number | null;
  iv_vs_realized: number | null;
  net_call_premium: number | null;
  bullish_flow_score: number | null;
  gex_regime: string | null;
  gamma_wall: number | null;
  max_pain: number | null;
  dark_pool_accum: boolean;
  smart_money: boolean;
  next_earnings_date: string | null;
  earnings_flag: boolean;
  suggested_put_strike: number | null;
  factor_breakdown: Record<string, number>;
  run_at: string | null;
}
