/**
 * TypeScript types for Put Options Screener
 * - Portions generated by AI
 */

// User settings (legacy + new fields)
export interface UserSettings {
  // Legacy fields for backward compatibility
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
  
  // New fields for filters and trade ideas
  selected_filter_id?: string | null;
  selected_trade_idea_id?: string | null;
}

// Filter model
export interface Filter {
  id: string;
  name: string;
  is_system: boolean;
  is_default: boolean;
  display_order: number;
  user_id?: string | null;
  min_dte: number;
  max_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
  created_at?: string;
  updated_at?: string;
}

// Filter list response
export interface FilterListResponse {
  system_filters: Filter[];
  user_filters: Filter[];
  default_filter_id?: string | null;
}

// Trade Idea model
export interface TradeIdea {
  id: string;
  name: string;
  description?: string | null;
  is_system: boolean;
  is_default: boolean;
  display_order: number;
  user_id?: string | null;
  symbols: string[];
  created_at?: string;
  updated_at?: string;
}

// Trade Idea list response
export interface TradeIdeaListResponse {
  system_trade_ideas: TradeIdea[];
  user_trade_ideas: TradeIdea[];
  default_trade_idea_id?: string | null;
}

// Filter create/update request
export interface FilterCreateRequest {
  name?: string;
  min_dte: number;
  max_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// Trade Idea create/update request
export interface TradeIdeaCreateRequest {
  name: string;
  description?: string;
  symbols: string[];
}

// User info
export interface UserInfo {
  id: string;
  email: string | null;
  subscription_status: 'free' | 'pro' | 'cancelled';
  screens_today: number;
  screens_remaining: number;
  settings: UserSettings | null;
}

// Option result from screening
export interface OptionResult {
  symbol: string;
  current_price: number;
  strike: number;
  premium?: number;
  lastPrice?: number;
  annualized_return: number;
  daily_decay_contract?: number;
  prob_assign: number;
  expiry: string;
  calendar_days?: number;
  dte?: number;
  volume: number;
  open_interest: number;
  openInterest?: number;
  implied_volatility?: number;
  impliedVolatility?: number;
}

// Screen request
export interface ScreenRequest {
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// Screen response
export interface ScreenResponse {
  success: boolean;
  results: Record<string, OptionResult[]>;
  screens_remaining: number | null;
  used_yahoo_fallback: boolean;
  message: string;
}

// News item
export interface NewsItem {
  title: string;
  url: string;
  published?: string;
  date_display?: string;
  source?: string;
}

// News response
export interface NewsResponse {
  symbol: string;
  news: NewsItem[];
  error?: string;
}

// Health check response
export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  database: string;
  massive_api: string;
  auth: string;
}

// Cache settings (admin only)
export interface CacheSettings {
  cache_enabled: boolean;
  ttl_stock_price: number;
  ttl_options_chain: number;
  ttl_news: number;
  updated_at?: string;
}
