/**
 * TypeScript types for Put Options Screener
 * - Portions generated by AI
 */

// User settings
export interface UserSettings {
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// User info
export interface UserInfo {
  id: string;
  email: string | null;
  subscription_status: 'free' | 'pro' | 'cancelled';
  screens_today: number;
  screens_remaining: number;
  settings: UserSettings | null;
}

// Option result from screening
export interface OptionResult {
  symbol: string;
  current_price: number;
  strike: number;
  premium?: number;
  lastPrice?: number;
  annualized_return: number;
  daily_decay_contract?: number;
  prob_assign: number;
  expiry: string;
  calendar_days?: number;
  dte?: number;
  volume: number;
  open_interest: number;
  openInterest?: number;
  implied_volatility?: number;
  impliedVolatility?: number;
}

// Screen request
export interface ScreenRequest {
  symbols: string[];
  max_dte: number;
  min_dte: number;
  min_volume: number;
  min_open_interest: number;
  min_annualized_return: number;
  max_assignment_probability: number;
}

// Screen response
export interface ScreenResponse {
  success: boolean;
  results: Record<string, OptionResult[]>;
  screens_remaining: number | null;
  used_yahoo_fallback: boolean;
  message: string;
}

// News item
export interface NewsItem {
  title: string;
  url: string;
  published?: string;
  date_display?: string;
  source?: string;
}

// News response
export interface NewsResponse {
  symbol: string;
  news: NewsItem[];
  error?: string;
}

// Health check response
export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  database: string;
  massive_api: string;
  auth: string;
}
