"""
Analysis-related Pydantic schemas
- Portions generated by AI
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum


class SentimentEnum(str, Enum):
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"


class ActionEnum(str, Enum):
    STRONG_BUY = "STRONG BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    STRONG_SELL = "STRONG SELL"
    WAIT = "WAIT"


class ConvictionEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TrendEnum(str, Enum):
    UPTREND = "UPTREND"
    DOWNTREND = "DOWNTREND"
    SIDEWAYS = "SIDEWAYS"


class ImportanceEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class WeightEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SourceEnum(str, Enum):
    NEWS = "News"
    TECHNICAL = "Technical"
    FUNDAMENTAL = "Fundamental"
    ANALYST = "Analyst"


class KeyMetrics(BaseModel):
    current_price: Optional[float] = None
    price_change_percent: Optional[float] = None
    fifty_two_week_high: Optional[float] = None
    fifty_two_week_low: Optional[float] = None
    volume: Optional[int] = None
    avg_volume: Optional[int] = None
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    beta: Optional[float] = None
    short_interest_percent: Optional[float] = None
    analyst_rating: Optional[str] = None
    avg_price_target: Optional[float] = None
    price_target_upside: Optional[float] = None


class Technicals(BaseModel):
    rsi_14: Optional[float] = None
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    sma_200: Optional[float] = None
    trend: Optional[str] = None
    support_level: Optional[float] = None
    resistance_level: Optional[float] = None


class Scenario(BaseModel):
    name: str
    probability: float
    price_target: float
    return_percent: float
    conditions: List[str] = []
    timeframe: str = ""


class Catalyst(BaseModel):
    event: str
    date: Optional[str] = None
    days_until: Optional[int] = None
    importance: str = "MEDIUM"
    expected_impact: str = ""


class Factor(BaseModel):
    factor: str
    source: str
    weight: str = "MEDIUM"


class PriceTarget(BaseModel):
    price: float
    label: str


class EntryZone(BaseModel):
    low: float
    high: float


class TradeRecommendation(BaseModel):
    action: str
    conviction: str = "MEDIUM"
    rationale: str = ""
    entry_zone: Optional[EntryZone] = None
    stop_loss: Optional[float] = None
    stop_loss_percent: Optional[float] = None
    targets: List[PriceTarget] = []
    risk_reward_ratio: Optional[float] = None
    position_size_suggestion: str = ""
    timeframe: str = ""
    warnings: List[str] = []


class StockAnalysis(BaseModel):
    """Complete stock analysis response"""
    symbol: str
    analysis_date: str
    data_sources: List[str] = []
    
    # Overall assessment
    overall_sentiment: str
    confidence: float
    summary: str
    
    # Factual data
    key_metrics: Optional[KeyMetrics] = None
    technicals: Optional[Technicals] = None
    
    # LLM-generated analysis
    scenarios: List[Scenario] = []
    upcoming_catalysts: List[Catalyst] = []
    bullish_factors: List[Factor] = []
    bearish_factors: List[Factor] = []
    trade_recommendation: Optional[TradeRecommendation] = None
    
    # Metadata
    cached_at: Optional[str] = None
    expires_at: Optional[str] = None
    llm_provider: str = ""
    disclaimer: str = ""
    
    class Config:
        from_attributes = True


class AnalysisRequest(BaseModel):
    """Request model for analysis"""
    symbol: str
    force_refresh: bool = False


class AnalysisErrorResponse(BaseModel):
    """Error response for analysis"""
    error: str
    error_type: str  # configuration, data, analysis, system
    symbol: str


class AISettingsResponse(BaseModel):
    """Response for AI settings"""
    ai_enabled: bool
    active_provider: str
    cache_enabled: bool
    cache_ttl_seconds: int
    available_providers: List[Dict[str, Any]]
    updated_at: Optional[str] = None


class AISettingsUpdate(BaseModel):
    """Request to update AI settings"""
    ai_enabled: Optional[bool] = None
    active_provider: Optional[str] = None
    cache_enabled: Optional[bool] = None
    cache_ttl_seconds: Optional[int] = None
