"""
Analysis-related Pydantic schemas
- Portions generated by AI
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum


class SentimentEnum(str, Enum):
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"


class ActionEnum(str, Enum):
    STRONG_BUY = "STRONG BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    STRONG_SELL = "STRONG SELL"
    WAIT = "WAIT"


class ConvictionEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class TrendEnum(str, Enum):
    UPTREND = "UPTREND"
    DOWNTREND = "DOWNTREND"
    SIDEWAYS = "SIDEWAYS"


class ImportanceEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class WeightEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SourceEnum(str, Enum):
    NEWS = "News"
    TECHNICAL = "Technical"
    FUNDAMENTAL = "Fundamental"
    ANALYST = "Analyst"


class KeyMetrics(BaseModel):
    current_price: Optional[float] = None
    price_change_percent: Optional[float] = None
    fifty_two_week_high: Optional[float] = None
    fifty_two_week_low: Optional[float] = None
    volume: Optional[int] = None
    avg_volume: Optional[int] = None
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    beta: Optional[float] = None
    short_interest_percent: Optional[float] = None
    analyst_rating: Optional[str] = None
    avg_price_target: Optional[float] = None
    price_target_upside: Optional[float] = None


class Technicals(BaseModel):
    # Oscillators
    rsi_14: Optional[float] = None
    rsi_signal: Optional[str] = None  # OVERSOLD / OVERBOUGHT / NEUTRAL
    macd_line: Optional[float] = None
    macd_signal_line: Optional[float] = None
    macd_histogram: Optional[float] = None
    macd_signal: Optional[str] = None  # BULLISH / BEARISH / NEUTRAL

    # Moving Averages
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    sma_200: Optional[float] = None
    price_vs_sma20: Optional[str] = None
    price_vs_sma50: Optional[str] = None
    price_vs_sma200: Optional[str] = None
    sma20_distance_pct: Optional[float] = None
    sma50_distance_pct: Optional[float] = None
    sma200_distance_pct: Optional[float] = None

    # Trends
    short_term_trend: Optional[str] = None
    long_term_trend: Optional[str] = None
    trend: Optional[str] = None  # kept for backward compat

    # Support & Resistance
    near_support: Optional[float] = None
    major_support: Optional[float] = None
    near_resistance: Optional[float] = None
    major_resistance: Optional[float] = None
    support_level: Optional[float] = None   # backward compat
    resistance_level: Optional[float] = None  # backward compat

    # Volatility
    atr_14: Optional[float] = None
    volatility_level: Optional[str] = None  # LOW / MODERATE / HIGH / EXTREME

    # Volume
    volume_signal: Optional[str] = None  # NORMAL / ACCUMULATION / DISTRIBUTION / CAPITULATION

    # Fibonacci
    fib_high: Optional[float] = None
    fib_low: Optional[float] = None
    fib_23_6: Optional[float] = None
    fib_38_2: Optional[float] = None
    fib_50_0: Optional[float] = None
    fib_61_8: Optional[float] = None
    fib_nearest_level: Optional[str] = None
    fib_nearest_price: Optional[float] = None

    # Momentum Oscillators
    ema_9: Optional[float] = None
    price_vs_ema9: Optional[str] = None  # ABOVE / BELOW
    ema9_distance_pct: Optional[float] = None
    stoch_k: Optional[float] = None
    stoch_d: Optional[float] = None
    stoch_signal: Optional[str] = None  # OVERSOLD / OVERBOUGHT / NEUTRAL / BULLISH_CROSS / BEARISH_CROSS
    roc_5d: Optional[float] = None
    roc_10d: Optional[float] = None

    # Bollinger Bands
    bb_upper: Optional[float] = None
    bb_middle: Optional[float] = None
    bb_lower: Optional[float] = None
    bb_position: Optional[str] = None  # ABOVE_UPPER / UPPER_HALF / LOWER_HALF / BELOW_LOWER
    bb_squeeze: Optional[bool] = None

    # Enhanced Volume
    vol_trend_3d_vs_20d: Optional[float] = None  # ratio of 3-day avg vs 20-day avg

    # Gap Analysis
    gap_direction: Optional[str] = None  # UP / DOWN / NONE
    gap_size_pct: Optional[float] = None

    # Market Context
    rs_vs_spy_5d: Optional[float] = None
    rs_vs_spy_10d: Optional[float] = None
    rs_vs_spy_20d: Optional[float] = None
    spy_change_5d: Optional[float] = None
    sector: Optional[str] = None
    industry: Optional[str] = None

    # Post-Earnings
    post_earnings_drift: Optional[str] = None  # UP / DOWN / NONE
    days_since_earnings: Optional[int] = None

    # LLM-generated interpretive fields
    candle_pattern: Optional[str] = None
    overall_signal: Optional[str] = None
    signal_note: Optional[str] = None


class Scenario(BaseModel):
    name: str
    probability: float
    price_target: float
    return_percent: float
    conditions: List[str] = []
    timeframe: str = ""


class Catalyst(BaseModel):
    event: str
    date: Optional[str] = None
    days_until: Optional[int] = None
    importance: str = "MEDIUM"
    expected_impact: str = ""


class Factor(BaseModel):
    factor: str
    source: str
    weight: str = "MEDIUM"


class PriceTarget(BaseModel):
    price: float
    label: str


class EntryZone(BaseModel):
    low: float
    high: float


class TradeRecommendation(BaseModel):
    action: str
    conviction: str = "MEDIUM"
    rationale: str = ""
    entry_zone: Optional[EntryZone] = None
    stop_loss: Optional[float] = None
    stop_loss_percent: Optional[float] = None
    targets: List[PriceTarget] = []
    risk_reward_ratio: Optional[float] = None
    position_size_suggestion: str = ""
    timeframe: str = ""
    warnings: List[str] = []


class StockAnalysis(BaseModel):
    """Complete stock analysis response"""
    symbol: str
    analysis_date: str
    data_sources: List[str] = []
    
    # Overall assessment
    overall_sentiment: str
    confidence: float
    summary: str
    
    # Factual data
    key_metrics: Optional[KeyMetrics] = None
    technicals: Optional[Technicals] = None
    
    # LLM-generated analysis
    scenarios: List[Scenario] = []
    upcoming_catalysts: List[Catalyst] = []
    bullish_factors: List[Factor] = []
    bearish_factors: List[Factor] = []
    trade_recommendation: Optional[TradeRecommendation] = None
    
    # Metadata
    cached_at: Optional[str] = None
    expires_at: Optional[str] = None
    llm_provider: str = ""
    disclaimer: str = ""
    
    class Config:
        from_attributes = True


class AnalysisRequest(BaseModel):
    """Request model for analysis"""
    symbol: str
    force_refresh: bool = False


class AnalysisErrorResponse(BaseModel):
    """Error response for analysis"""
    error: str
    error_type: str  # configuration, data, analysis, system
    symbol: str


class AISettingsResponse(BaseModel):
    """Response for AI settings"""
    ai_enabled: bool
    active_provider: str
    cache_enabled: bool
    cache_ttl_seconds: int
    available_providers: List[Dict[str, Any]]
    updated_at: Optional[str] = None


class AISettingsUpdate(BaseModel):
    """Request to update AI settings"""
    ai_enabled: Optional[bool] = None
    active_provider: Optional[str] = None
    cache_enabled: Optional[bool] = None
    cache_ttl_seconds: Optional[int] = None
