"""
Directional bias (Flow & Positioning) Pydantic schemas
- Portions generated by AI
"""

from typing import Dict, List, Optional
from pydantic import BaseModel


class DirectionSignal(BaseModel):
    """One normalized factor feeding the composite score."""
    key: str
    label: str
    weight: float
    score: Optional[float] = None  # -1..1, None when unavailable
    detail: str
    available: bool


class DirectionResponse(BaseModel):
    """Options-positioning directional read for one ticker."""
    symbol: str
    as_of: str
    direction: str  # BULLISH | NEUTRAL | BEARISH
    score: float  # -100..100
    confidence: float  # 0..1
    coverage: float  # 0..1, share of signal weight that had data
    stability: Optional[str] = None  # stabilizing | amplifying
    gamma_regime: Optional[str] = None
    signals: List[DirectionSignal]
    levels: Dict[str, Optional[float]]
    put_seller_note: str
    cached_at: Optional[str] = None
    expires_at: Optional[str] = None
    disclaimer: str
