"""
Filter-related Pydantic schemas
- Portions generated by AI
"""

from typing import Optional, List
from pydantic import BaseModel, Field
from datetime import datetime


class FilterBase(BaseModel):
    """Base filter schema with common fields"""
    name: Optional[str] = None
    min_dte: int = Field(..., ge=0, le=365)
    max_dte: int = Field(..., ge=0, le=365)
    min_volume: int = Field(..., ge=0)
    min_open_interest: int = Field(..., ge=0)
    min_annualized_return: float = Field(..., ge=0, le=1000)
    max_assignment_probability: int = Field(..., ge=0, le=100)


class FilterCreate(FilterBase):
    """Schema for creating a new filter"""
    pass


class FilterUpdate(BaseModel):
    """Schema for updating a filter (all fields optional)"""
    name: Optional[str] = None
    min_dte: Optional[int] = Field(None, ge=0, le=365)
    max_dte: Optional[int] = Field(None, ge=0, le=365)
    min_volume: Optional[int] = Field(None, ge=0)
    min_open_interest: Optional[int] = Field(None, ge=0)
    min_annualized_return: Optional[float] = Field(None, ge=0, le=1000)
    max_assignment_probability: Optional[int] = Field(None, ge=0, le=100)


class FilterResponse(BaseModel):
    """Schema for filter response"""
    id: str
    name: str
    is_system: bool
    is_default: bool
    user_id: Optional[str] = None
    min_dte: int
    max_dte: int
    min_volume: int
    min_open_interest: int
    min_annualized_return: float
    max_assignment_probability: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True


class FilterListResponse(BaseModel):
    """Schema for list of filters response"""
    system_filters: List[FilterResponse]
    user_filters: List[FilterResponse]
    default_filter_id: Optional[str] = None
