"""
TradeIdea-related Pydantic schemas
- Portions generated by AI
"""

from typing import Optional, List
from pydantic import BaseModel, Field
from datetime import datetime


class TradeIdeaBase(BaseModel):
    """Base trade idea schema with common fields"""
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    symbols: List[str] = Field(..., min_length=1)


class TradeIdeaCreate(TradeIdeaBase):
    """Schema for creating a new trade idea"""
    pass


class TradeIdeaUpdate(BaseModel):
    """Schema for updating a trade idea (all fields optional)"""
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    symbols: Optional[List[str]] = None


class TradeIdeaResponse(BaseModel):
    """Schema for trade idea response"""
    id: str
    name: str
    description: Optional[str] = None
    is_system: bool
    is_default: bool
    user_id: Optional[str] = None
    symbols: List[str]
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True


class TradeIdeaListResponse(BaseModel):
    """Schema for list of trade ideas response"""
    system_trade_ideas: List[TradeIdeaResponse]
    user_trade_ideas: List[TradeIdeaResponse]
    default_trade_idea_id: Optional[str] = None
