/**
 * Dashboard page - main screener interface
 * - Portions generated by AI
 */

import { useCallback, useEffect, useState } from 'react';
import { Play, Loader2, ChevronDown, BookOpen, X } from 'lucide-react';
import { useAppStore } from '@/stores/useAppStore';
import apiClient from '@/api/client';
import { Sidebar } from '@/components/Sidebar';
import { ResultsTable } from '@/components/ResultsTable';
import { NewsSection } from '@/components/NewsSection';
import { ScreeningProgress } from '@/components/ScreeningProgress';
import { UserMenu } from '@/components/UserMenu';
import { InstallPrompt } from '@/components/InstallPrompt';
import { ChipSelector } from '@/components/ChipSelector';
import { Modal } from '@/components/Modal';
import { FilterForm } from '@/components/FilterForm';
import { TradeIdeaForm } from '@/components/TradeIdeaForm';
import { StockAnalysisPanel } from '@/components/StockAnalysisPanel';
import { useAuthSync } from '@/hooks/useAuthSync';
import { useFiltersAndIdeas } from '@/hooks/useFiltersAndIdeas';
import { buildRankedResults, resultsViewLabel, SUMMARY_VIEW } from '@/utils/resultsSummary';
import type { OptionResult, Filter, TradeIdea, FilterCreateRequest, TradeIdeaCreateRequest } from '@/types';

export function Dashboard() {
  // Sync auth and settings with backend
  useAuthSync();

  const {
    results,
    setResults,
    selectedSymbol,
    setSelectedSymbol,
    selectedView,
    setSelectedView,
    isScreening,
    usedYahooFallback,
    setUsedYahooFallback,
    sidebarOpen,
    toggleSidebar,
    screeningProgress,
    startScreening,
    updateScreeningSymbol,
    incrementProgress,
    stopScreening,
  } = useAppStore();

  // Filters and Trade Ideas
  const {
    allFilters,
    selectedFilter,
    filtersLoading,
    loadFilters,
    createFilter,
    editFilter,
    deleteFilter,
    handleSelectFilter,
    allTradeIdeas,
    selectedTradeIdea,
    tradeIdeasLoading,
    loadTradeIdeas,
    createTradeIdea,
    editTradeIdea,
    deleteTradeIdea,
    handleSelectTradeIdea,
  } = useFiltersAndIdeas();

  // Modal state
  const [filterModalOpen, setFilterModalOpen] = useState(false);
  const [tradeIdeaModalOpen, setTradeIdeaModalOpen] = useState(false);
  const [editingFilter, setEditingFilter] = useState<Filter | null>(null);
  const [editingTradeIdea, setEditingTradeIdea] = useState<TradeIdea | null>(null);
  const [formLoading, setFormLoading] = useState(false);

  // AI Analysis panel state
  const [analysisPanelOpen, setAnalysisPanelOpen] = useState(false);
  const [analysisSymbol, setAnalysisSymbol] = useState<string>('');

  // Handle analyze button click
  const handleAnalyze = useCallback((symbol: string) => {
    setAnalysisSymbol(symbol);
    setAnalysisPanelOpen(true);
  }, []);

  // Load filters and trade ideas on mount
  useEffect(() => {
    loadFilters();
    loadTradeIdeas();
  }, [loadFilters, loadTradeIdeas]);

  // Filter modal handlers
  const handleCreateFilter = () => {
    setEditingFilter(null);
    setFilterModalOpen(true);
  };

  const handleEditFilter = (filter: Filter) => {
    setEditingFilter(filter);
    setFilterModalOpen(true);
  };

  const handleSaveFilter = async (data: FilterCreateRequest) => {
    setFormLoading(true);
    try {
      if (editingFilter) {
        await editFilter(editingFilter.id, data);
      } else {
        await createFilter(data);
      }
      setFilterModalOpen(false);
      setEditingFilter(null);
    } catch (error) {
      console.error('Failed to save filter:', error);
      alert('Failed to save filter');
    } finally {
      setFormLoading(false);
    }
  };

  const handleDeleteFilter = async (filter: Filter) => {
    try {
      await deleteFilter(filter.id);
    } catch (error) {
      console.error('Failed to delete filter:', error);
      alert('Failed to delete filter');
    }
  };

  // Trade Idea modal handlers
  const handleCreateTradeIdea = () => {
    setEditingTradeIdea(null);
    setTradeIdeaModalOpen(true);
  };

  const handleEditTradeIdea = (idea: TradeIdea) => {
    setEditingTradeIdea(idea);
    setTradeIdeaModalOpen(true);
  };

  const handleSaveTradeIdea = async (data: TradeIdeaCreateRequest) => {
    setFormLoading(true);
    try {
      if (editingTradeIdea) {
        await editTradeIdea(editingTradeIdea.id, data);
      } else {
        await createTradeIdea(data);
      }
      setTradeIdeaModalOpen(false);
      setEditingTradeIdea(null);
    } catch (error) {
      console.error('Failed to save trade idea:', error);
      alert('Failed to save trade idea');
    } finally {
      setFormLoading(false);
    }
  };

  const handleDeleteTradeIdea = async (idea: TradeIdea) => {
    try {
      await deleteTradeIdea(idea.id);
    } catch (error) {
      console.error('Failed to delete trade idea:', error);
      alert('Failed to delete trade idea');
    }
  };

  // Publish completed tickers to the table. sortByReturn is false while a
  // Screen All run is in progress so rows appear immediately; true at the end.
  const publishResults = useCallback((
    currentResults: Record<string, OptionResult[]>,
    sortByReturn: boolean,
  ) => {
    const ranked = buildRankedResults(currentResults, sortByReturn);
    const tickerViews = Object.keys(ranked).filter((key) => key !== 'Summary');

    if (tickerViews.length === 0) {
      return;
    }

    setResults(ranked);
    const currentView = useAppStore.getState().selectedView;
    if (!ranked[currentView]) {
      setSelectedView(ranked.Summary ? 'Summary' : tickerViews[0]);
    }
  }, [setResults, setSelectedView]);

  // Get symbols from selected trade idea
  const symbols = selectedTradeIdea?.symbols || [];

  // Sequential screening with progress
  const handleScreenAll = useCallback(async () => {
    if (!selectedFilter || !selectedTradeIdea || symbols.length === 0) return;

    startScreening(symbols.length);
    setSelectedView('Summary');
    let yahooUsed = false;
    const allResults: Record<string, OptionResult[]> = {};

    for (const symbol of symbols) {
      // Check if stop was requested
      if (useAppStore.getState().stopRequested) {
        break;
      }

      updateScreeningSymbol(symbol);

      try {
        const response = await apiClient.screenOptions({
          symbols: [symbol],
          max_dte: selectedFilter.max_dte,
          min_dte: selectedFilter.min_dte,
          min_volume: selectedFilter.min_volume,
          min_open_interest: selectedFilter.min_open_interest,
          min_annualized_return: 0,
          max_assignment_probability: selectedFilter.max_assignment_probability,
        });

        if (response.used_yahoo_fallback) {
          yahooUsed = true;
        }

        const symbolResults = response.results[symbol] || [];
        if (symbolResults.length > 0) {
          allResults[symbol] = symbolResults;
          publishResults(allResults, false);
        }
      } catch (error) {
        console.error(`Error screening ${symbol}:`, error);
        // Continue with next symbol
      }

      incrementProgress();
    }

    setUsedYahooFallback(yahooUsed);
    stopScreening();
    publishResults(allResults, true);
  }, [
    selectedFilter,
    selectedTradeIdea,
    symbols,
    startScreening,
    updateScreeningSymbol,
    incrementProgress,
    stopScreening,
    setUsedYahooFallback,
    setSelectedView,
    publishResults,
  ]);

  // Single symbol screening (no progress needed)
  const handleScreenSingle = useCallback(async () => {
    if (!selectedSymbol || !selectedFilter) return;

    startScreening(1);
    updateScreeningSymbol(selectedSymbol);

    try {
      const response = await apiClient.screenOptions({
        symbols: [selectedSymbol],
        max_dte: selectedFilter.max_dte,
        min_dte: selectedFilter.min_dte,
        min_volume: selectedFilter.min_volume,
        min_open_interest: selectedFilter.min_open_interest,
        min_annualized_return: 0,
        max_assignment_probability: selectedFilter.max_assignment_probability,
      });

      setUsedYahooFallback(response.used_yahoo_fallback);
      setResults(response.results);
      
      if (Object.keys(response.results).length > 0) {
        setSelectedView(selectedSymbol);
      }
    } catch (error) {
      console.error(`Error screening ${selectedSymbol}:`, error);
    }

    incrementProgress();
    stopScreening();
  }, [
    selectedSymbol,
    selectedFilter,
    startScreening,
    updateScreeningSymbol,
    setResults,
    setSelectedView,
    incrementProgress,
    stopScreening,
    setUsedYahooFallback,
  ]);

  // Build view options
  const viewOptions = Object.keys(results).filter((k) => k !== SUMMARY_VIEW);
  if (results[SUMMARY_VIEW]) {
    viewOptions.unshift(SUMMARY_VIEW);
  }

  const activeView = viewOptions.includes(selectedView)
    ? selectedView
    : (viewOptions[0] || selectedView);
  const currentResults = results[activeView] || [];

  const resultsCaption = [
    selectedTradeIdea?.name
      ? `Best cash-secured puts on ${selectedTradeIdea.name}`
      : 'Best cash-secured puts',
    selectedFilter
      ? `${selectedFilter.name} (≤${selectedFilter.max_assignment_probability}% assignment)`
      : null,
  ].filter(Boolean).join(' · ');

  return (
    <div className="flex flex-col h-screen">
      <header className="flex-shrink-0 px-4 sm:px-6 py-4 border-b border-white/5 bg-dark-950">
        <div className="flex items-center justify-between gap-2 sm:gap-3">
          <div className="flex items-center gap-2 sm:gap-3 min-w-0">
            <img
              src="/icons/icon-192.png"
              alt=""
              className="w-8 h-8 sm:w-9 sm:h-9 rounded-lg flex-shrink-0"
            />
            <div className="min-w-0">
              <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold gradient-text truncate">
                PutYield
              </h1>
              <p className="text-gray-400 text-xs sm:text-sm hidden sm:block mt-0.5">
                Get paid to own stocks at a discount.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 sm:gap-3 flex-shrink-0">
            <UserMenu />
            <button
              onClick={toggleSidebar}
              className="inline-flex items-center gap-2 p-2.5 sm:px-3 sm:py-2 bg-dark-800 hover:bg-dark-700 rounded-lg transition-colors text-gray-400 hover:text-white"
              title={sidebarOpen ? 'Close guide' : 'Open guide'}
              aria-label={sidebarOpen ? 'Close guide' : 'Open guide'}
              aria-expanded={sidebarOpen}
            >
              {sidebarOpen ? (
                <X size={22} className="sm:w-5 sm:h-5" />
              ) : (
                <BookOpen size={22} className="sm:w-5 sm:h-5" />
              )}
              <span className="hidden sm:inline text-sm font-medium">Guide</span>
            </button>
          </div>
        </div>
      </header>

      <div className="relative flex-1 min-h-0">
      {/* Main content */}
      <main className="h-full overflow-auto p-4 sm:p-6">

        {/* Filters and Trade Ideas selectors */}
        <div className="sticky left-0 z-20 space-y-3 mb-4 sm:mb-6 p-3 sm:p-4 bg-dark-800/50 rounded-xl border border-white/5 w-[calc(100dvw-2rem)] sm:w-[calc(100dvw-3rem)]">
          <ChipSelector
            label="Trade Ideas"
            items={allTradeIdeas}
            selectedId={selectedTradeIdea?.id || null}
            onSelect={handleSelectTradeIdea}
            onCreateNew={handleCreateTradeIdea}
            onEdit={(idea) => handleEditTradeIdea(idea)}
            onDelete={(idea) => handleDeleteTradeIdea(idea)}
            loading={tradeIdeasLoading}
          />
          <ChipSelector
            label="Assignment risk"
            items={allFilters}
            selectedId={selectedFilter?.id || null}
            onSelect={handleSelectFilter}
            onCreateNew={handleCreateFilter}
            onEdit={(filter) => handleEditFilter(filter)}
            onDelete={(filter) => handleDeleteFilter(filter)}
            loading={filtersLoading}
          />
        </div>

        <div className="sticky left-0 z-20 flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4 mb-4 sm:mb-6 w-[calc(100dvw-2rem)] sm:w-[calc(100dvw-3rem)]">
          <button
            onClick={handleScreenAll}
            disabled={isScreening || symbols.length === 0 || !selectedFilter}
            className="btn-primary flex items-center justify-center gap-2 w-full sm:w-auto py-3 sm:py-2.5 text-base sm:text-sm min-h-[48px] sm:min-h-0"
          >
            {isScreening ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Play size={18} />
            )}
            Screen All
          </button>

          <div className="flex items-center gap-2 w-full sm:w-auto sm:pl-3 sm:border-l sm:border-white/10">
            <div className="relative flex-1 sm:flex-none">
              <select
                value={selectedSymbol}
                onChange={(e) => setSelectedSymbol(e.target.value)}
                disabled={isScreening || symbols.length === 0}
                aria-label="Stock to screen"
                className="appearance-none bg-dark-800 border border-white/10 rounded-lg px-3 py-2.5 pr-9 text-sm text-gray-300 font-medium hover:bg-dark-700 hover:border-primary-500/50 focus:border-primary-500 focus:bg-dark-700 transition-all w-full sm:min-w-[120px] disabled:opacity-50 disabled:hover:bg-dark-800 cursor-pointer"
              >
                {symbols.map((symbol) => (
                  <option key={symbol} value={symbol}>
                    {symbol}
                  </option>
                ))}
              </select>
              <ChevronDown
                size={16}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none text-gray-500"
              />
            </div>
            <button
              onClick={handleScreenSingle}
              disabled={isScreening || !selectedSymbol || !selectedFilter}
              className="btn-secondary flex items-center justify-center gap-2 flex-1 sm:flex-none py-2.5 text-sm min-h-[44px] sm:min-h-0"
            >
              Screen {selectedSymbol || 'Stock'}
            </button>
          </div>
        </div>

        {/* Screening progress indicator */}
        {screeningProgress && screeningProgress.isActive && (
          <ScreeningProgress />
        )}

        {/* Results section */}
        {Object.keys(results).length > 0 ? (
          <>
            <div className="sticky left-0 z-20 flex items-center justify-between mb-1 sm:mb-1.5 w-[calc(100dvw-2rem)] sm:w-[calc(100dvw-3rem)]">
              <h2 className="text-lg sm:text-xl font-semibold">
                Results
                {isScreening && (
                  <span className="text-xs sm:text-sm font-normal text-gray-400 ml-2">
                    (updating...)
                  </span>
                )}
              </h2>
              
              {/* View selector */}
              {viewOptions.length > 1 && (
                <div className="relative">
                  <select
                    value={activeView}
                    onChange={(e) => setSelectedView(e.target.value)}
                    className="appearance-none bg-dark-800 border border-white/10 rounded-lg px-3 sm:px-4 py-2 pr-8 sm:pr-10 text-sm text-gray-200 font-medium hover:bg-dark-700 hover:border-primary-500/50 focus:border-primary-500 focus:bg-dark-700 transition-all min-w-[140px] sm:min-w-[160px] cursor-pointer"
                  >
                    {viewOptions.map((option) => (
                      <option key={option} value={option}>
                        {resultsViewLabel(option)}
                      </option>
                    ))}
                  </select>
                  <ChevronDown
                    size={16}
                    className="absolute right-2 sm:right-3 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400"
                  />
                </div>
              )}
            </div>
            {resultsCaption && (
              <p className="sticky left-0 z-20 text-gray-400 text-xs sm:text-sm mb-3 sm:mb-4 w-[calc(100dvw-2rem)] sm:w-[calc(100dvw-3rem)]">
                {resultsCaption}
              </p>
            )}

            <ResultsTable data={currentResults} title={resultsViewLabel(activeView)} onAnalyze={handleAnalyze} />

            {/* Yahoo fallback notice */}
            {usedYahooFallback && !isScreening && (
              <p className="text-gray-500 text-xs sm:text-sm mt-3 sm:mt-4">
                Note: When Massive.com data was unavailable, prices or options data were retrieved from Yahoo Finance.
              </p>
            )}

            {/* News section - only show when not screening */}
            {activeView !== SUMMARY_VIEW && !isScreening && (
              <NewsSection symbol={activeView} />
            )}
          </>
        ) : null}

      </main>

      <Sidebar />
      </div>

      {/* PWA Install Prompt */}
      <InstallPrompt />

      {/* Filter Modal */}
      <Modal
        isOpen={filterModalOpen}
        onClose={() => {
          setFilterModalOpen(false);
          setEditingFilter(null);
        }}
        maxWidth="md"
      >
        <FilterForm
          filter={editingFilter}
          onSave={handleSaveFilter}
          onCancel={() => {
            setFilterModalOpen(false);
            setEditingFilter(null);
          }}
          loading={formLoading}
        />
      </Modal>

      {/* Trade Idea Modal */}
      <Modal
        isOpen={tradeIdeaModalOpen}
        onClose={() => {
          setTradeIdeaModalOpen(false);
          setEditingTradeIdea(null);
        }}
        maxWidth="md"
      >
        <TradeIdeaForm
          idea={editingTradeIdea}
          onSave={handleSaveTradeIdea}
          onCancel={() => {
            setTradeIdeaModalOpen(false);
            setEditingTradeIdea(null);
          }}
          loading={formLoading}
        />
      </Modal>

      {/* AI Stock Analysis Panel */}
      <StockAnalysisPanel
        symbol={analysisSymbol}
        isOpen={analysisPanelOpen}
        onClose={() => setAnalysisPanelOpen(false)}
      />
    </div>
  );
}
