"""
PutYield - FastAPI Backend
- Portions generated by AI

Main application entry point.
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .core.config import get_settings
from .core.database import init_db
from .core.cache import get_cache, load_cache_settings_from_db
from .core.api_provider import load_api_provider_settings_from_db
from .core.market_settings import load_market_settings_from_db
from .api.v1.router import api_router

settings = get_settings()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize resources on startup"""
    print(f"Starting {settings.APP_NAME} v{settings.APP_VERSION}")
    init_db()
    
    # Load cache settings from database into memory
    load_cache_settings_from_db()
    
    # Load API provider settings from database into memory
    load_api_provider_settings_from_db()
    
    # Load market settings (risk-free rate) from database into memory
    load_market_settings_from_db()
    
    # Initialize cache connection
    cache = get_cache()
    if cache.ping():
        print(f"Cache initialized: {type(cache).__name__}")

    # Breakout scanner auto-scan schedule (no-op unless an admin enabled it)
    try:
        from .modules.breakout_scanner.scheduler import start_scheduler
        start_scheduler()
    except Exception as e:
        print(f"Auto-scan scheduler not started: {e}")

    yield

    try:
        from .modules.breakout_scanner.scheduler import stop_scheduler
        await stop_scheduler()
    except Exception:
        pass
    print("Shutting down...")


app = FastAPI(
    title=settings.APP_NAME,
    description="API for screening put options with real-time market data",
    version=settings.APP_VERSION,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# CORS configuration
# Allow all origins in development, restrict in production via CORS_ORIGINS env var
origins = settings.cors_origins_list
print(f"CORS origins configured: {origins}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
    allow_headers=["*"],
    expose_headers=["*"],
)

# Include API routes
app.include_router(api_router)


@app.get("/")
async def root():
    """Root endpoint - redirects to docs"""
    return {
        "name": settings.APP_NAME,
        "version": settings.APP_VERSION,
        "docs": "/docs",
        "health": "/health"
    }


# =============================================================================
# Run with: uvicorn app.main:app --reload
# =============================================================================

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
