/**
 * App state store using Zustand
 * - Portions generated by AI
 */

import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { UserSettings, OptionResult } from '@/types';

// Default settings matching config.json
const DEFAULT_SETTINGS: UserSettings = {
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'SPY', 'QQQ'],
  max_dte: 45,
  min_dte: 15,
  min_volume: 10,
  min_open_interest: 10,
  min_annualized_return: 20.0,
  max_assignment_probability: 20,
};

interface AppState {
  // Settings
  settings: UserSettings;
  setSettings: (settings: Partial<UserSettings>) => void;
  resetSettings: () => void;

  // Screening results
  results: Record<string, OptionResult[]>;
  setResults: (results: Record<string, OptionResult[]>) => void;
  clearResults: () => void;

  // UI state
  selectedSymbol: string;
  setSelectedSymbol: (symbol: string) => void;
  selectedView: string;
  setSelectedView: (view: string) => void;
  isScreening: boolean;
  setIsScreening: (screening: boolean) => void;
  usedYahooFallback: boolean;
  setUsedYahooFallback: (used: boolean) => void;

  // Sidebar
  sidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;
  toggleSidebar: () => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set) => ({
      // Settings
      settings: DEFAULT_SETTINGS,
      setSettings: (newSettings) =>
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        })),
      resetSettings: () => set({ settings: DEFAULT_SETTINGS }),

      // Results
      results: {},
      setResults: (results) => set({ results }),
      clearResults: () => set({ results: {} }),

      // UI state
      selectedSymbol: DEFAULT_SETTINGS.symbols[0],
      setSelectedSymbol: (symbol) => set({ selectedSymbol: symbol }),
      selectedView: 'Summary',
      setSelectedView: (view) => set({ selectedView: view }),
      isScreening: false,
      setIsScreening: (screening) => set({ isScreening: screening }),
      usedYahooFallback: false,
      setUsedYahooFallback: (used) => set({ usedYahooFallback: used }),

      // Sidebar
      sidebarOpen: true,
      setSidebarOpen: (open) => set({ sidebarOpen: open }),
      toggleSidebar: () => set((state) => ({ sidebarOpen: !state.sidebarOpen })),
    }),
    {
      name: 'put-options-screener',
      partialize: (state) => ({
        settings: state.settings,
        sidebarOpen: state.sidebarOpen,
      }),
    }
  )
);
