#!/bin/bash
# Local development script
# - Portions generated by AI
#
# This script starts both backend and frontend for local development.
# Usage: ./scripts/dev.sh

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

echo -e "${GREEN}=== Put Options Screener - Development Mode ===${NC}"
echo ""

# Check for virtual environment
if [ -d ".venv" ]; then
    source .venv/bin/activate
    echo -e "${GREEN}Virtual environment activated${NC}"
fi

# Load environment variables
if [ -f ".env" ]; then
    export $(cat .env | grep -v '^#' | xargs)
    echo -e "${GREEN}Loaded .env file${NC}"
fi

# Set development environment
export DATABASE_URL="${DATABASE_URL:-sqlite:///./backend/local_test.db}"
export CORS_ORIGINS="http://localhost:3000,http://localhost:5173"
export PYTHONPATH="$PROJECT_DIR:$PROJECT_DIR/shared"

echo ""
echo -e "${YELLOW}Starting backend...${NC}"
echo "  Database: $DATABASE_URL"
echo ""

# Kill any existing processes
pkill -f "uvicorn app.main:app" 2>/dev/null || true
pkill -f "vite" 2>/dev/null || true
sleep 1

# Start backend
cd "$PROJECT_DIR/backend"
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"
sleep 2

# Verify backend is running
if curl -s http://localhost:8000/health > /dev/null; then
    echo -e "${GREEN}Backend is running at http://localhost:8000${NC}"
else
    echo "Backend failed to start"
    exit 1
fi

# Check if frontend dependencies are installed
cd "$PROJECT_DIR/frontend"
if [ ! -d "node_modules" ]; then
    echo ""
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

echo ""
echo -e "${YELLOW}Starting frontend...${NC}"
npm run dev &
FRONTEND_PID=$!
echo "Frontend PID: $FRONTEND_PID"

echo ""
echo -e "${GREEN}=== Development servers running ===${NC}"
echo ""
echo "  Frontend:  http://localhost:5173 (or http://localhost:3000)"
echo "  Backend:   http://localhost:8000"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "Press Ctrl+C to stop both services"
echo ""

# Trap Ctrl+C to clean up
trap "echo 'Stopping...'; kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit 0" SIGINT SIGTERM

# Keep script running
wait
