/**
 * Chart analysis helpers: volume-by-price profile and support/resistance
 * levels, computed client-side from daily candles.
 * - Portions generated by AI
 */

import type { CandleBar } from '@/types';

export interface VolumeBucket {
  low: number;
  high: number;
  volume: number;
}

/** Aggregate volume into horizontal price buckets (volume-by-price profile). */
export function computeVolumeProfile(candles: CandleBar[], bucketCount = 30): VolumeBucket[] {
  if (candles.length === 0) return [];
  let min = Infinity;
  let max = -Infinity;
  for (const c of candles) {
    if (c.low < min) min = c.low;
    if (c.high > max) max = c.high;
  }
  if (!(max > min)) return [];
  const step = (max - min) / bucketCount;
  const buckets: VolumeBucket[] = Array.from({ length: bucketCount }, (_, i) => ({
    low: min + i * step,
    high: min + (i + 1) * step,
    volume: 0,
  }));
  for (const c of candles) {
    // Spread the bar's volume evenly across the buckets its high-low range spans
    const lo = Math.max(0, Math.min(bucketCount - 1, Math.floor((c.low - min) / step)));
    const hi = Math.max(lo, Math.min(bucketCount - 1, Math.floor((c.high - min) / step - 1e-9)));
    const span = hi - lo + 1;
    for (let i = lo; i <= hi; i++) buckets[i].volume += c.volume / span;
  }
  return buckets;
}

export interface SRLevel {
  price: number;
  touches: number;
  kind: 'support' | 'resistance';
}

/**
 * Pivot-based support/resistance: find local highs/lows, cluster nearby
 * pivots, rank clusters by touch count, and keep the strongest levels on
 * each side of the last close.
 */
export function computeSupportResistance(candles: CandleBar[], maxPerSide = 3): SRLevel[] {
  const n = candles.length;
  if (n < 10) return [];
  // Pivot window scales with the range so 1M isn't all noise and 5Y isn't all signal
  const k = Math.max(2, Math.floor(n / 60));
  const pivots: number[] = [];
  for (let i = k; i < n - k; i++) {
    let isHigh = true;
    let isLow = true;
    for (let j = i - k; j <= i + k; j++) {
      if (candles[j].high > candles[i].high) isHigh = false;
      if (candles[j].low < candles[i].low) isLow = false;
      if (!isHigh && !isLow) break;
    }
    if (isHigh) pivots.push(candles[i].high);
    if (isLow) pivots.push(candles[i].low);
  }
  if (pivots.length === 0) return [];

  let min = Infinity;
  let max = -Infinity;
  for (const c of candles) {
    if (c.low < min) min = c.low;
    if (c.high > max) max = c.high;
  }
  const tolerance = (max - min) * 0.02;

  pivots.sort((a, b) => a - b);
  const clusters: { sum: number; count: number }[] = [];
  for (const price of pivots) {
    const last = clusters[clusters.length - 1];
    if (last && price - last.sum / last.count <= tolerance) {
      last.sum += price;
      last.count += 1;
    } else {
      clusters.push({ sum: price, count: 1 });
    }
  }

  const current = candles[n - 1].close;
  const levels = clusters.map((c) => ({ price: c.sum / c.count, touches: c.count }));
  const strongest = (side: SRLevel['kind']) =>
    levels
      .filter((l) => (side === 'support' ? l.price < current : l.price >= current))
      .sort((a, b) => b.touches - a.touches)
      .slice(0, maxPerSide)
      .map((l) => ({ ...l, kind: side }));
  return [...strongest('support'), ...strongest('resistance')];
}

/**
 * Series primitive that draws the volume-by-price shelf as horizontal bars
 * anchored to the right edge of the chart pane.
 */
export class VolumeProfilePrimitive {
  private _buckets: VolumeBucket[] = [];
  private _maxVolume = 0;
  private _attached: { series: any; requestUpdate: () => void } | null = null;
  private _paneView: any;

  constructor() {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;
    this._paneView = {
      zOrder: () => 'bottom',
      renderer: () => ({
        draw: (target: any) => {
          if (!self._attached || self._maxVolume <= 0) return;
          const series = self._attached.series;
          target.useBitmapCoordinateSpace((scope: any) => {
            const ctx = scope.context;
            const paneWidth = scope.bitmapSize.width;
            const maxBarWidth = paneWidth * 0.22;
            ctx.fillStyle = 'rgba(102, 126, 234, 0.18)';
            for (const b of self._buckets) {
              const yHigh = series.priceToCoordinate(b.high);
              const yLow = series.priceToCoordinate(b.low);
              if (yHigh === null || yLow === null) continue;
              const top = Math.min(yHigh, yLow) * scope.verticalPixelRatio;
              const height = Math.max(1, Math.abs(yLow - yHigh) * scope.verticalPixelRatio - 1);
              const width = (b.volume / self._maxVolume) * maxBarWidth;
              ctx.fillRect(paneWidth - width, top, width, height);
            }
          });
        },
      }),
    };
  }

  attached(param: { series: any; requestUpdate: () => void }) {
    this._attached = param;
  }

  detached() {
    this._attached = null;
  }

  paneViews() {
    return [this._paneView];
  }

  setBuckets(buckets: VolumeBucket[]) {
    this._buckets = buckets;
    this._maxVolume = buckets.reduce((m, b) => Math.max(m, b.volume), 0);
    this._attached?.requestUpdate();
  }
}
