/**
 * Build the Summary view: one best trade per ticker, ranked by return.
 * - Portions generated by AI
 */

import type { OptionResult } from '@/types';

export function pickBestResult(rows: OptionResult[]): OptionResult {
  return rows.reduce((best, row) =>
    row.annualized_return > best.annualized_return ? row : best
  );
}

/**
 * Build ticker views plus a Summary row (best contract per ticker).
 * Pass sortByReturn=false while a Screen All run is still in progress so
 * completed tickers appear immediately in completion order. Sort only when
 * the run finishes.
 */
export function buildRankedResults(
  currentResults: Record<string, OptionResult[]>,
  sortByReturn = true,
): Record<string, OptionResult[]> {
  let ranked = Object.entries(currentResults)
    .filter(([symbol, rows]) => symbol !== 'Summary' && rows && rows.length > 0)
    .map(([symbol, rows]) => ({
      symbol,
      rows,
      best: pickBestResult(rows),
    }));

  if (sortByReturn) {
    ranked = ranked.sort((a, b) => b.best.annualized_return - a.best.annualized_return);
  }

  const ordered: Record<string, OptionResult[]> = {};
  for (const item of ranked) {
    ordered[item.symbol] = item.rows;
  }

  // Always show Summary while results are streaming in. After the final sort,
  // keep Summary only when more than one ticker qualified.
  if (ranked.length > 1 || (!sortByReturn && ranked.length > 0)) {
    ordered.Summary = ranked.map((item) => item.best);
  }

  return ordered;
}
