"""
LLM Provider package for AI stock analysis
- Portions generated by AI
"""

from .base import BaseLLMProvider, AnalysisError, LLMUnavailableError, DataFetchError
from .gemini_provider import GeminiProvider
from .groq_provider import GroqProvider
from .openai_provider import OpenAIProvider
from .provider_manager import (
    get_active_provider,
    get_active_provider_or_raise,
    get_available_providers,
)

__all__ = [
    "BaseLLMProvider",
    "AnalysisError",
    "DataFetchError",
    "LLMUnavailableError",
    "GeminiProvider",
    "GroqProvider",
    "OpenAIProvider",
    "get_active_provider",
    "get_active_provider_or_raise",
    "get_available_providers",
]
