"""
Base LLM Provider interface for AI stock analysis
- Portions generated by AI
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
import json
import re


class AnalysisError(Exception):
    """Base exception for analysis errors."""
    pass


class DataFetchError(AnalysisError):
    """Failed to fetch required data."""
    pass


class LLMUnavailableError(AnalysisError):
    """No LLM provider is available or configured."""
    pass


class BaseLLMProvider(ABC):
    """Abstract base class for LLM providers."""
    
    # Provider name for logging and display
    name: str = "base"
    
    @abstractmethod
    async def generate_analysis(self, prompt: str) -> Dict[str, Any]:
        """
        Generate stock analysis from prompt.
        
        Args:
            prompt: The analysis prompt with all stock data
            
        Returns:
            Parsed JSON dictionary with analysis results
            
        Raises:
            AnalysisError: If generation fails
        """
        pass
    
    @abstractmethod
    def is_available(self) -> bool:
        """
        Check if provider is configured and available.
        
        Returns:
            True if the provider has required API keys and can be used
        """
        pass
    
    def extract_json_from_response(self, response_text: str) -> Dict[str, Any]:
        """
        Extract JSON from LLM response text.
        Handles responses wrapped in markdown code blocks or raw JSON.
        
        Args:
            response_text: Raw text response from LLM
            
        Returns:
            Parsed JSON dictionary
            
        Raises:
            AnalysisError: If JSON cannot be extracted/parsed
        """
        text = response_text.strip()
        
        # Try to extract JSON from markdown code block
        json_match = re.search(r'```(?:json)?\s*\n?(.*?)\n?```', text, re.DOTALL)
        if json_match:
            text = json_match.group(1).strip()
        
        # Try to find JSON object boundaries
        start_idx = text.find('{')
        end_idx = text.rfind('}')
        
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            text = text[start_idx:end_idx + 1]
        
        # Clean up common JSON issues from LLMs
        text = self._fix_json_issues(text)
        
        # Try parsing
        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            # Log error details for debugging
            error_pos = e.pos if hasattr(e, 'pos') else 0
            context_start = max(0, error_pos - 100)
            context_end = min(len(text), error_pos + 100)
            error_context = text[context_start:context_end]
            print(f"[LLM JSON Error] Position {error_pos}: {e.msg}")
            print(f"[LLM JSON Error] Context around error: ...{error_context}...")
            
            # Try more aggressive fixes
            fixed_text = self._aggressive_json_fix(text)
            try:
                return json.loads(fixed_text)
            except json.JSONDecodeError as e2:
                # Log what character is at the error position
                if error_pos < len(text):
                    print(f"[LLM JSON Error] Character at position: '{text[error_pos]}' (ord={ord(text[error_pos])})")
                    # Show surrounding 20 chars
                    nearby_start = max(0, error_pos - 10)
                    nearby_end = min(len(text), error_pos + 10)
                    print(f"[LLM JSON Error] Nearby chars: '{text[nearby_start:nearby_end]}'")
                raise AnalysisError(f"Failed to parse LLM response as JSON: {e}")
    
    def _fix_json_issues(self, text: str) -> str:
        """
        Fix common JSON issues that LLMs produce.
        
        Args:
            text: Raw JSON string
            
        Returns:
            Cleaned JSON string
        """
        # Remove trailing commas before closing brackets/braces
        # This handles: [item1, item2,] and {key: value,}
        text = re.sub(r',\s*}', '}', text)
        text = re.sub(r',\s*]', ']', text)
        
        # Remove JavaScript-style comments
        # Single-line comments: // comment
        text = re.sub(r'//[^\n]*', '', text)
        # Multi-line comments: /* comment */
        text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
        
        # Fix unquoted keys (rare but happens): {key: value} -> {"key": value}
        # Only match keys that look like identifiers
        text = re.sub(r'([{,]\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s*:', r'\1"\2":', text)
        
        # Remove control characters that might sneak in (except newlines and tabs)
        text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
        
        return text
    
    def _aggressive_json_fix(self, text: str) -> str:
        """
        More aggressive JSON fixes for stubborn malformed responses.
        
        Args:
            text: JSON string that failed initial parsing
            
        Returns:
            Cleaned JSON string
        """
        # Replace single quotes with double quotes (but carefully)
        # This handles: {'key': 'value'} -> {"key": "value"}
        # Be careful not to replace single quotes inside strings
        text = re.sub(r"(?<![\\])\'", '"', text)
        
        # Fix missing commas between objects/arrays (including with newlines)
        # e.g., }\n  { -> },\n  {  or ][ -> ],[
        text = re.sub(r'\}(\s*)\{', r'},\1{', text)
        text = re.sub(r'\](\s*)\[', r'],\1[', text)
        text = re.sub(r'\}(\s*)\[', r'},\1[', text)
        text = re.sub(r'\](\s*)\{', r'],\1{', text)
        
        # Fix missing commas after closing brace/bracket before a key
        # e.g., }\n  "key" -> },\n  "key"
        text = re.sub(r'\}(\s*)"([a-zA-Z_])', r'},\1"\2', text)
        text = re.sub(r'\](\s*)"([a-zA-Z_])', r'],\1"\2', text)
        
        # Fix missing commas after values before keys
        # e.g., "value""key" -> "value","key"
        text = re.sub(r'"(\s*)"([a-zA-Z_])', r'",\1"\2', text)
        
        # Fix numbers followed directly by keys without comma
        # e.g., 123"key" -> 123,"key"
        text = re.sub(r'(\d)(\s*)"([a-zA-Z_])', r'\1,\2"\3', text)
        
        # Fix booleans/null followed directly by keys without comma
        text = re.sub(r'(true|false|null)(\s*)"([a-zA-Z_])', r'\1,\2"\3', text)
        
        # Remove any remaining trailing commas (run again after other fixes)
        text = re.sub(r',\s*}', '}', text)
        text = re.sub(r',\s*]', ']', text)
        
        return text
    
    def get_system_prompt(self) -> str:
        """
        Get the system prompt for stock analysis.
        
        Returns:
            System prompt instructing the LLM how to analyze stocks
        """
        return """You are a professional stock analyst providing actionable trading recommendations focused on SHORT-TERM MOMENTUM (1-2 week timeframe).

YOUR ROLE:
You are expected to apply your expertise in technical analysis, market dynamics, and sector knowledge to synthesize the provided data into a coherent, insightful analysis. Go beyond restating numbers — interpret what the indicators mean together, identify confluences and divergences, and explain the "so what" for a trader.

DATA INTEGRITY RULES:
- All FACTUAL CLAIMS (specific numbers, dates, news events, analyst ratings, price targets) MUST come from the data provided below. Do NOT invent or fabricate any facts.
- If a data section says "Data unavailable" or is empty, acknowledge the gap and reduce your confidence accordingly. Do NOT fill in missing facts with guesses.
- Do NOT reference specific events, partnerships, contracts, product launches, or management changes unless they appear in the news section below.
- Every bullish/bearish factor MUST cite a specific data point (number, indicator value, or headline) from the provided data.
- You MAY use your general knowledge of how sectors, industries, and market conditions typically behave to provide context and interpretation — but clearly distinguish between data-driven observations and general market reasoning.
- For the "candle_pattern" field: only name a pattern if the recent price action data (open/high/low/close) clearly supports it. Use null if unsure.
- For "overall_signal" and "signal_note": base these on the indicators provided (RSI, MACD, SMAs, EMA 9, Stochastic, ROC, Bollinger Bands, ATR, Fibonacci, volume, support/resistance, relative strength vs SPY). You may reference well-known technical concepts (e.g., golden cross, death cross, mean reversion) when the data supports them.

SHORT-TERM MOMENTUM ANALYSIS PRIORITIES:
- Weight EMA 9, Stochastic, ROC, and Bollinger Bands heavily — these are the primary short-term momentum gauges.
- Stochastic oversold (<20) + bullish cross = strong short-term buy signal. Overbought (>80) + bearish cross = strong short-term sell signal.
- ROC 5-day measures immediate momentum; ROC 10-day measures intermediate. Divergences between them matter.
- Bollinger Band squeeze often precedes explosive moves. Position near lower band with positive ROC = potential bounce.
- Price above EMA 9 with positive ROC = active short-term uptrend. Below EMA 9 with negative ROC = active downtrend.
- Relative strength vs SPY shows whether the stock is leading or lagging the market — critical for momentum trades.
- Gap analysis and post-earnings drift are high-probability short-term setups when present.
- Volume trend (3-day vs 20-day) confirms or denies momentum signals.

IMPORTANT RULES:
1. All scenario probabilities MUST sum to exactly 1.0
2. Price targets should be realistic for a 1-2 week timeframe (typically within 10-15% of current price)
3. Stop loss MUST be below the entry zone
4. If data quality is poor or limited, set confidence LOW (0.3-0.5) — do NOT inflate confidence to seem authoritative

CONFIDENCE SCORING (0.0 to 1.0):
- 0.85-1.0: Very strong conviction - multiple aligned signals, clear trend, supportive news, analyst consensus
- 0.70-0.84: Good conviction - mostly aligned signals with minor concerns
- 0.55-0.69: Moderate conviction - mixed signals, some uncertainty
- 0.40-0.54: Low conviction - conflicting signals, high uncertainty
- Below 0.40: Very low conviction - insufficient or contradictory data

BE SPECIFIC with confidence - do NOT default to 0.7. Vary based on actual data quality and signal alignment.

Respond ONLY with valid JSON matching the exact schema provided. No additional text."""
    
    def get_analysis_prompt(self, symbol: str, data: Dict[str, Any]) -> str:
        """
        Build the analysis prompt with all stock data.
        
        Args:
            symbol: Stock ticker symbol
            data: Dictionary containing all fetched stock data
            
        Returns:
            Complete prompt for the LLM
        """
        # Format price data
        price_section = self._format_price_data(data.get('yahoo', {}))
        
        # Format technical indicators
        technicals_section = self._format_technicals(data.get('technicals', {}))
        
        # Format news
        news_section = self._format_news(data.get('news', []))
        
        # Format analyst ratings (Massive API or Yahoo Finance fallback)
        analyst_section = self._format_analyst_ratings(data.get('analyst_ratings'))
        
        # Format short interest (Massive API or Yahoo Finance fallback)
        short_section = self._format_short_interest(data.get('short_interest'))
        
        # Format events
        events_section = self._format_events(data)
        
        # Format market context (SPY, relative strength, sector)
        market_context_section = self._format_market_context(data)
        
        # Format recent price action (last 5 days OHLCV)
        recent_price_section = self._format_recent_price_action(data)
        
        prompt = f"""Analyze {symbol} and provide a SHORT-TERM (1-2 week) momentum-based trading recommendation.

=== PRICE DATA ===
{price_section}

=== TECHNICAL INDICATORS ===
{technicals_section}

=== MARKET CONTEXT ===
{market_context_section}

=== RECENT PRICE ACTION (Last 5 Days) ===
{recent_price_section}

=== ANALYST RATINGS ===
{analyst_section}

=== SHORT INTEREST ===
{short_section}

=== RECENT NEWS (Last 7 Days) ===
{news_section}

=== UPCOMING EVENTS ===
{events_section}

Based on this data, provide your analysis in the following JSON format:

{{
  "overall_sentiment": "BULLISH" | "NEUTRAL" | "BEARISH",
  "confidence": 0.0 to 1.0,
  "summary": "2-3 sentence summary of the analysis",
  "scenarios": [
    {{
      "name": "Bull Case",
      "probability": 0.0 to 1.0,
      "price_target": number,
      "return_percent": number,
      "conditions": ["condition1", "condition2"],
      "timeframe": "e.g., 2-4 weeks"
    }},
    {{
      "name": "Base Case",
      "probability": 0.0 to 1.0,
      "price_target": number,
      "return_percent": number,
      "conditions": ["condition1", "condition2"],
      "timeframe": "e.g., 2-4 weeks"
    }},
    {{
      "name": "Bear Case",
      "probability": 0.0 to 1.0,
      "price_target": number,
      "return_percent": number,
      "conditions": ["condition1", "condition2"],
      "timeframe": "e.g., 2-4 weeks"
    }}
  ],
  "upcoming_catalysts": [
    {{
      "event": "event description",
      "date": "YYYY-MM-DD or null",
      "days_until": number or null,
      "importance": "HIGH" | "MEDIUM" | "LOW",
      "expected_impact": "description of expected impact"
    }}
  ],
  "bullish_factors": [
    {{
      "factor": "description",
      "source": "News" | "Technical" | "Fundamental" | "Analyst",
      "weight": "HIGH" | "MEDIUM" | "LOW"
    }}
  ],
  "bearish_factors": [
    {{
      "factor": "description",
      "source": "News" | "Technical" | "Fundamental" | "Analyst",
      "weight": "HIGH" | "MEDIUM" | "LOW"
    }}
  ],
  "trade_recommendation": {{
    "action": "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL" | "WAIT",
    "conviction": "HIGH" | "MEDIUM" | "LOW",
    "rationale": "explanation of recommendation",
    "entry_zone": {{ "low": number, "high": number }},
    "stop_loss": number,
    "stop_loss_percent": number,
    "targets": [
      {{ "price": number, "label": "T1" }},
      {{ "price": number, "label": "T2" }},
      {{ "price": number, "label": "T3" }}
    ],
    "risk_reward_ratio": number,
    "position_size_suggestion": "e.g., 100% normal position or 50% due to earnings risk",
    "timeframe": "e.g., 2-4 weeks",
    "warnings": ["warning1", "warning2"]
  }},
  "candle_pattern": "Name of any significant recent candlestick pattern (e.g. Hammer, Doji, Three Black Crows) or null if none",
  "overall_signal": "Short phrase summarizing the technical setup (e.g. OVERSOLD BOUNCE CANDIDATE, BEARISH BREAKDOWN, BULLISH CONTINUATION) or null",
  "signal_note": "1-2 sentence explanation of the overall technical signal, referencing specific indicators from the data provided, or null"
}}

REMEMBER:
- Probabilities MUST sum to 1.0
- Stop loss MUST be below entry zone
- Every factor MUST cite a specific data point from above (e.g., "RSI at 40.9 is neutral", "Stochastic %K at 22 is oversold", "ROC 5d at +3.2% shows positive momentum")
- Do NOT fabricate news, events, analyst opinions, earnings dates, or price targets not in the data above
- If news section is empty or unavailable, do NOT make up news-based factors
- You MAY apply sector/industry knowledge and general market reasoning to interpret the data — just don't invent facts
- Confidence should reflect actual signal strength (0.5-0.6 for mixed signals, 0.8+ for strong alignment, 0.4 or below for weak/conflicting data) — do NOT default to 0.7
- For candle_pattern: use null unless the recent 5-day OHLC data clearly supports a specific pattern
- For overall_signal and signal_note: synthesize the technical indicators into a clear trading thesis — reference specific values and explain what they mean together
- PRIORITIZE short-term momentum indicators (EMA 9, Stochastic, ROC, Bollinger Bands) for the 1-2 week trade recommendation
- Use the MARKET CONTEXT section to assess whether the stock is leading or lagging the broader market
- Provide ACTIONABLE insight — don't just restate numbers, explain what they mean for a trader's decision"""
        
        return prompt
    
    def _format_price_data(self, yahoo_data: Dict[str, Any]) -> str:
        """Format Yahoo Finance price data for prompt."""
        if not yahoo_data:
            return "Data unavailable"
        
        lines = []
        if yahoo_data.get('current_price') is not None:
            lines.append(f"Current Price: ${yahoo_data['current_price']:.2f}")
        if yahoo_data.get('previous_close') is not None:
            lines.append(f"Previous Close: ${yahoo_data['previous_close']:.2f}")
        if yahoo_data.get('change_percent') is not None:
            lines.append(f"Change: {yahoo_data['change_percent']:+.2f}%")
        if yahoo_data.get('fifty_two_week_high') is not None:
            lines.append(f"52-Week High: ${yahoo_data['fifty_two_week_high']:.2f}")
        if yahoo_data.get('fifty_two_week_low') is not None:
            lines.append(f"52-Week Low: ${yahoo_data['fifty_two_week_low']:.2f}")
        if yahoo_data.get('volume') is not None:
            lines.append(f"Volume: {yahoo_data['volume']:,}")
        if yahoo_data.get('avg_volume') is not None:
            lines.append(f"Avg Volume: {yahoo_data['avg_volume']:,}")
        if yahoo_data.get('market_cap') is not None:
            lines.append(f"Market Cap: ${yahoo_data['market_cap']:,.0f}")
        if yahoo_data.get('pe_ratio'):
            lines.append(f"P/E Ratio: {yahoo_data['pe_ratio']:.2f}")
        if yahoo_data.get('beta'):
            lines.append(f"Beta: {yahoo_data['beta']:.2f}")
        
        return "\n".join(lines) if lines else "Data unavailable"
    
    def _format_technicals(self, technicals: Dict[str, Any]) -> str:
        """Format technical indicators for prompt."""
        if not technicals:
            return "Data unavailable"
        
        lines = []
        
        # RSI
        if technicals.get('rsi_14') is not None:
            rsi_label = f" ({technicals.get('rsi_signal', '')})" if technicals.get('rsi_signal') else ""
            lines.append(f"RSI(14): {technicals['rsi_14']:.1f}{rsi_label}")
        
        # MACD
        if technicals.get('macd_line') is not None:
            lines.append(f"MACD Line: {technicals['macd_line']:.4f}")
            lines.append(f"MACD Signal Line: {technicals['macd_signal_line']:.4f}")
            lines.append(f"MACD Histogram: {technicals['macd_histogram']:.4f}")
            lines.append(f"MACD Signal: {technicals.get('macd_signal', 'N/A')}")
        
        # SMAs with interpretation
        for period, key, short in [(20, 'sma_20', 'sma20'), (50, 'sma_50', 'sma50'), (200, 'sma_200', 'sma200')]:
            if technicals.get(key) is not None:
                vs = technicals.get(f'price_vs_{short}', '')
                dist = technicals.get(f'{short}_distance_pct')
                dist_str = f" ({dist:+.1f}%)" if dist is not None else ""
                lines.append(f"SMA({period}): ${technicals[key]:.2f} - Price {vs}{dist_str}")
        
        # Trends
        if technicals.get('short_term_trend'):
            lines.append(f"Short-Term Trend: {technicals['short_term_trend']}")
        if technicals.get('long_term_trend'):
            lines.append(f"Long-Term Trend: {technicals['long_term_trend']}")
        
        # ATR / Volatility
        if technicals.get('atr_14') is not None:
            vol_label = f" ({technicals.get('volatility_level', '')})" if technicals.get('volatility_level') else ""
            lines.append(f"ATR(14): ${technicals['atr_14']:.2f}{vol_label}")
        
        # Fibonacci
        if technicals.get('fib_high') is not None and technicals.get('fib_low') is not None:
            lines.append(f"Fibonacci Range: ${technicals['fib_low']:.2f} - ${technicals['fib_high']:.2f}")
            for label, key in [('23.6%', 'fib_23_6'), ('38.2%', 'fib_38_2'), ('50.0%', 'fib_50_0'), ('61.8%', 'fib_61_8')]:
                if technicals.get(key) is not None:
                    lines.append(f"  {label}: ${technicals[key]:.2f}")
            if technicals.get('fib_nearest_level') and technicals.get('fib_nearest_price') is not None:
                lines.append(f"  Nearest Level: {technicals['fib_nearest_level']} (${technicals['fib_nearest_price']:.2f})")
        
        # Volume Signal
        if technicals.get('volume_signal'):
            lines.append(f"Volume Signal: {technicals['volume_signal']}")
        
        # Support and Resistance
        if technicals.get('near_support') is not None:
            lines.append(f"Near Support: ${technicals['near_support']:.2f}")
        if technicals.get('near_resistance') is not None:
            lines.append(f"Near Resistance: ${technicals['near_resistance']:.2f}")
        if technicals.get('major_support') is not None:
            lines.append(f"Major Support: ${technicals['major_support']:.2f}")
        if technicals.get('major_resistance') is not None:
            lines.append(f"Major Resistance: ${technicals['major_resistance']:.2f}")
        
        # ── EMA 9 (short-term momentum) ──
        if technicals.get('ema_9') is not None:
            vs = technicals.get('price_vs_ema9', '')
            dist = technicals.get('ema9_distance_pct')
            dist_str = f" ({dist:+.1f}%)" if dist is not None else ""
            lines.append(f"EMA(9): ${technicals['ema_9']:.2f} - Price {vs}{dist_str}")
        
        # ── Stochastic Oscillator ──
        if technicals.get('stoch_k') is not None:
            lines.append(f"Stochastic %K: {technicals['stoch_k']:.1f}")
            lines.append(f"Stochastic %D: {technicals['stoch_d']:.1f}")
            lines.append(f"Stochastic Signal: {technicals.get('stoch_signal', 'N/A')}")
        
        # ── Rate of Change ──
        if technicals.get('roc_5d') is not None:
            lines.append(f"ROC(5-day): {technicals['roc_5d']:+.2f}%")
        if technicals.get('roc_10d') is not None:
            lines.append(f"ROC(10-day): {technicals['roc_10d']:+.2f}%")
        
        # ── Bollinger Bands ──
        if technicals.get('bb_upper') is not None:
            lines.append(f"Bollinger Upper: ${technicals['bb_upper']:.2f}")
            lines.append(f"Bollinger Middle: ${technicals['bb_middle']:.2f}")
            lines.append(f"Bollinger Lower: ${technicals['bb_lower']:.2f}")
            lines.append(f"Bollinger Position: {technicals.get('bb_position', 'N/A')}")
            if technicals.get('bb_squeeze'):
                lines.append("Bollinger Squeeze: YES (low volatility, potential breakout)")
        
        # ── Enhanced Volume ──
        if technicals.get('vol_trend_3d_vs_20d') is not None:
            ratio = technicals['vol_trend_3d_vs_20d']
            label = "ABOVE AVERAGE" if ratio > 1.2 else "BELOW AVERAGE" if ratio < 0.8 else "NORMAL"
            lines.append(f"3-Day Volume Trend: {ratio:.2f}x 20-day avg ({label})")
        
        # ── Gap Analysis ──
        if technicals.get('gap_direction') and technicals['gap_direction'] != 'NONE':
            lines.append(f"Gap Detected: {technicals['gap_direction']} gap of {technicals.get('gap_size_pct', 0):.1f}% in last 5 days")
        
        # ── Post-Earnings Drift ──
        if technicals.get('post_earnings_drift') and technicals['post_earnings_drift'] != 'NONE':
            days = technicals.get('days_since_earnings', '?')
            lines.append(f"Post-Earnings Drift: {technicals['post_earnings_drift']} ({days} days since earnings)")
        
        return "\n".join(lines) if lines else "Data unavailable"
    
    def _format_market_context(self, data: Dict[str, Any]) -> str:
        """Format market context (SPY relative strength, sector) for prompt."""
        technicals = data.get('technicals', {})
        market_ctx = data.get('market_context', {})
        
        def _get(key: str):
            """Get from technicals first, fallback to market_context (None-safe)."""
            val = technicals.get(key)
            return val if val is not None else market_ctx.get(key)
        
        lines = []
        
        # SPY performance
        spy_5d = _get('spy_change_5d')
        if spy_5d is not None:
            lines.append(f"SPY 5-Day Change: {spy_5d:+.2f}%")
        
        # Relative strength vs SPY
        for period in [5, 10, 20]:
            val = _get(f'rs_vs_spy_{period}d')
            if val is not None:
                label = "OUTPERFORMING" if val > 0 else "UNDERPERFORMING"
                lines.append(f"Relative Strength vs SPY ({period}d): {val:+.2f}% ({label})")
        
        # Sector / Industry
        sector = _get('sector')
        industry = _get('industry')
        if sector:
            lines.append(f"Sector: {sector}")
        if industry:
            lines.append(f"Industry: {industry}")
        
        return "\n".join(lines) if lines else "Data unavailable"
    
    def _format_recent_price_action(self, data: Dict[str, Any]) -> str:
        """Format recent 5-day OHLCV for prompt."""
        recent = data.get('recent_price_action', [])
        if not recent:
            return "Data unavailable"
        
        lines = ["Date       | Open    | High    | Low     | Close   | Volume"]
        lines.append("-" * 65)
        for day in recent:
            date = day.get('date', 'N/A')
            o = day.get('open', 0)
            h = day.get('high', 0)
            l = day.get('low', 0)
            c = day.get('close', 0)
            v = day.get('volume', 0)
            lines.append(f"{date} | ${o:7.2f} | ${h:7.2f} | ${l:7.2f} | ${c:7.2f} | {v:>10,}")
        
        return "\n".join(lines)
    
    def _format_news(self, news: list) -> str:
        """Format news items for prompt."""
        if not news:
            return "No recent news available"
        
        lines = []
        for item in news[:10]:  # Limit to 10 items
            title = item.get('title', 'Unknown')
            date = item.get('date_display', '')
            source = item.get('source', '')
            source_str = f" ({source})" if source else ""
            date_str = f" [{date}]" if date else ""
            lines.append(f"- {title}{source_str}{date_str}")
        
        return "\n".join(lines)
    
    def _format_analyst_ratings(self, ratings: Optional[Dict[str, Any]]) -> str:
        """Format analyst ratings for prompt."""
        if not ratings:
            return "Data unavailable"
        
        lines = []
        if ratings.get('rating'):
            lines.append(f"Consensus Rating: {ratings['rating']}")
        if ratings.get('target_price'):
            lines.append(f"Average Price Target: ${ratings['target_price']:.2f}")
        
        buy = ratings.get('buy_count', 0)
        hold = ratings.get('hold_count', 0)
        sell = ratings.get('sell_count', 0)
        if buy or hold or sell:
            lines.append(f"Analyst Distribution: Buy={buy}, Hold={hold}, Sell={sell}")
        
        return "\n".join(lines) if lines else "Data unavailable"
    
    def _format_short_interest(self, short_data: Optional[Dict[str, Any]]) -> str:
        """Format short interest data for prompt."""
        if not short_data:
            return "Data unavailable"
        
        lines = []
        if short_data.get('short_interest'):
            lines.append(f"Short Volume: {short_data['short_interest']:,}")
        if short_data.get('short_interest_percent'):
            lines.append(f"Short Interest %: {short_data['short_interest_percent']:.2f}%")
        if short_data.get('date'):
            lines.append(f"As of: {short_data['date']}")
        
        return "\n".join(lines) if lines else "Data unavailable"
    
    def _format_events(self, data: Dict[str, Any]) -> str:
        """Format upcoming events for prompt."""
        lines = []
        
        yahoo = data.get('yahoo', {})
        if yahoo.get('earnings_date'):
            days = yahoo.get('days_to_earnings')
            days_str = f" ({days} days away)" if days is not None else ""
            lines.append(f"Earnings: {yahoo['earnings_date']}{days_str}")
        
        if yahoo.get('ex_dividend_date'):
            lines.append(f"Ex-Dividend: {yahoo['ex_dividend_date']}")
        
        return "\n".join(lines) if lines else "No upcoming events found"
