"""
Google Gemini LLM Provider for AI stock analysis
- Portions generated by AI

Free tier: 15 RPM, 1M tokens/day
"""

import time
from typing import Dict, Any
import google.generativeai as genai

from .base import BaseLLMProvider, AnalysisError
from ...core.config import get_settings


class GeminiProvider(BaseLLMProvider):
    """Google Gemini provider for stock analysis."""
    
    name = "gemini"
    
    def __init__(self):
        self.settings = get_settings()
        self._model = None
        
        if self.is_available():
            genai.configure(api_key=self.settings.GEMINI_API_KEY)
            self._model = genai.GenerativeModel(
                'gemini-2.5-flash',
                system_instruction=self.get_system_prompt()
            )
    
    def is_available(self) -> bool:
        """Check if Gemini is configured."""
        return bool(self.settings.GEMINI_API_KEY)
    
    async def generate_analysis(self, prompt: str) -> Dict[str, Any]:
        """Generate analysis using Gemini."""
        if not self.is_available():
            raise AnalysisError("Gemini API key not configured")
        
        try:
            start_time = time.time()
            
            # Use JSON response mode for structured output
            response = self._model.generate_content(
                prompt,
                generation_config=genai.GenerationConfig(
                    temperature=0.2,  # Lower temperature for more consistent JSON output
                    max_output_tokens=4096,
                    response_mime_type="application/json",
                )
            )
            
            elapsed = time.time() - start_time
            print(f"[Gemini] Response time: {elapsed:.2f}s")
            
            if not response.text:
                raise AnalysisError("Empty response from Gemini")
            
            return self.extract_json_from_response(response.text)
            
        except AnalysisError:
            raise
        except Exception as e:
            error_msg = str(e)
            if "API key" in error_msg.lower():
                raise AnalysisError("Invalid Gemini API key")
            if "quota" in error_msg.lower() or "rate" in error_msg.lower():
                raise AnalysisError("Gemini API rate limit exceeded. Please try again later.")
            raise AnalysisError(f"Gemini analysis failed: {error_msg}")
