"""
Application configuration
- Portions generated by AI
"""

import os
import json
from typing import List, Optional
from pydantic_settings import BaseSettings
from functools import lru_cache


class Settings(BaseSettings):
    """Application settings loaded from environment variables"""
    
    # Application
    APP_NAME: str = "Put Options Screener API"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False
    
    # Database
    DATABASE_URL: str = "sqlite:///./local_test.db"
    
    # Authentication (Clerk)
    CLERK_SECRET_KEY: Optional[str] = None
    
    # External APIs
    MASSIVE_API_KEY: Optional[str] = None
    
    # Stripe (Phase 3)
    STRIPE_SECRET_KEY: Optional[str] = None
    STRIPE_WEBHOOK_SECRET: Optional[str] = None
    STRIPE_PRICE_ID: Optional[str] = None
    
    # CORS
    CORS_ORIGINS: str = "*"
    
    # Rate limiting
    RATE_LIMIT_PER_MINUTE: int = 60
    
    # Free tier limits
    FREE_SCREENS_PER_DAY: int = 5
    FREE_MAX_SYMBOLS: int = 5
    PRO_MAX_SYMBOLS: int = 50
    
    @property
    def cors_origins_list(self) -> List[str]:
        """Parse CORS origins from comma-separated string"""
        if self.CORS_ORIGINS == "*":
            return ["*"]
        return [origin.strip() for origin in self.CORS_ORIGINS.split(",")]
    
    class Config:
        env_file = ".env"
        case_sensitive = True


@lru_cache()
def get_settings() -> Settings:
    """Get cached settings instance"""
    return Settings()


def load_default_config() -> dict:
    """Load default screening configuration from config.json"""
    # Look for config.json in backend directory
    config_path = os.path.join(os.path.dirname(__file__), "..", "..", "config.json")
    config_path = os.path.abspath(config_path)
    
    if os.path.exists(config_path):
        try:
            with open(config_path, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Could not load config.json from {config_path}: {e}")
    
    # Return default configuration if file not found
    return {
        "data": {
            "symbols": ["AAPL", "MSFT", "GOOGL", "SPY", "QQQ"]
        },
        "options_strategy": {
            "max_dte": 45,
            "min_dte": 15,
            "min_volume": 10,
            "min_open_interest": 10
        },
        "screening_criteria": {
            "min_annualized_return": 20.0,
            "max_assignment_probability": 20
        },
        "output": {
            "sort_by": ["annualized_return"],
            "sort_order": "descending",
            "max_results": 50
        }
    }


# Load default config at module level
DEFAULT_CONFIG = load_default_config()
